// Package testdatagarm supplies the declared taxonomy of the testdata proto
// package to toolpolicy's tests.
//
// In the daemon's repository this package is GENERATED by the tool plugin,
// and carries the service registry as well — Tools, Mount, RegisterTestService
// and a NATS client. All of that imports the enforcing package, which this
// repository must not depend on: the contract language compiles and validates
// declarations, and the runtime enforces them.
//
// The tests here only ever needed the taxonomy, so that is all this holds. The
// generated registry and the tests that exercise it belong beside the code
// they register into. See KNOWN-GAPS.md.
package testdatagarm

import toolv1 "github.com/garm-ai/garm/contracts/garm/tool/v1"

// Compartments is the taxonomy declared by testdata/fixture.proto, kept
// byte-identical to what the plugin emits for that file.
var Compartments = []*toolv1.Decl{
	{Name: "financial"},
	{Name: "pii-contact"},
	{Name: "support"},
}
