package compiler

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"path"
	"sort"
	"unicode"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// toolbindPkg is where a generated binding registers itself.
//
// It points at the tool runtime's repository, not this one. Registration is
// something a TOOL SERVICE does, so the seam lives on the tool side — and
// this is an emitted import path rather than a dependency of the generator,
// so naming a package in another repository costs nothing here.
const toolbindPkg = protogen.GoImportPath("github.com/garm-ai/tool-go/toolbind")

// EmitMicro writes the tool-side binding for every tool declared across
// files sharing one Go package: one Handler interface per service, one
// method per tool in plain proto signatures with no Unimplemented embed, a
// ServeX that registers each tool against a toolbind.Registrar, and the
// package's contract identity (ContractVersion, DescriptorHash) plus each
// service's tool references (XTools).
//
// With MicroOptions.ConnectAdapter it also writes XAsConnect. That is off by
// default; see MicroOptions for why.
//
// EmitMicro is the tool-author-facing sibling of Emit: Emit produces
// garm's OWN wiring (Mount, RegisterXService — imports toolplane, stays in
// the parent module's gen/ tree); EmitMicro produces what a tool author
// implements against, in the contracts module. Neither replaces the other;
// they read the same tools off the same files and emit into different
// packages for different audiences.
//
// EmitMicro deliberately emits none of the governance metadata Emit's
// ToolDef carries — no clearance, no compartments, no verb, no approval
// mode. The tool side never re-decides access: it only needs enough to
// dispatch a call (ToolRef's FQN/Subject/Method/Service) and enforce the
// wire shape (DescriptorHash), which is exactly what Handler/ServeX/XTools
// give it and nothing more.
//
// Like Emit, this is called once per Go package, not once per proto file:
// ContractVersion and DescriptorHash are package-scoped constants (the
// package's identity as a whole, not any one service's), and a package
// with more than one tool-bearing service — every package in this
// tree — would redeclare them on every additional file emitted into it.
// files, outPkg and tools carry the exact same contract as Emit's
// same-named parameters; see that function's doc comment.
// MicroOptions are EmitMicro's optional behaviours.
type MicroOptions struct {
	// ConnectAdapter emits XAsConnect alongside the binding.
	//
	// Off by default, and the default is the interesting part. The adapter
	// forces two costs on every tool module that does not want it: a second
	// protoc plugin in buf.gen.yaml, and a dependency on connectrpc.com/connect
	// inherited by anyone importing the binding. It also forces the binding
	// into a sibling package — colocated, it would reference the connect
	// handler in its own package's connect sibling, which imports the base
	// package back for message types.
	//
	// It was on unconditionally because garm once had a connect surface to
	// mount the result on. It does not: garmd builds messages from catalogue
	// descriptors with dynamicpb, and connect's generated handlers are
	// generic over types this binary has never seen.
	//
	// It remains available because a tool author may still want to serve
	// connect directly — to a non-garm consumer during a migration, say.
	// That is their choice to make rather than one made for them.
	ConnectAdapter bool
}

func EmitMicro(
	g *protogen.GeneratedFile,
	files []*protogen.File,
	outPkg protogen.GoPackageName,
	tools []Tool,
	contractVersion string,
	opts MicroOptions,
) error {
	g.P("// Code generated by protoc-gen-garm-tools. DO NOT EDIT.")
	g.P()
	g.P("package ", outPkg)
	g.P()

	f := files[0]
	methods := methodsByFullName(files)
	order, byService := ServicesInOrder(tools)

	resolved := map[string][]microTool{}
	for _, svc := range order {
		rs, err := resolveMicroTools(methods, byService[svc])
		if err != nil {
			return err
		}
		resolved[svc] = rs
	}

	for _, svc := range order {
		emitMicroHandler(g, svc, resolved[svc])
	}
	for _, svc := range order {
		emitMicroServe(g, svc, resolved[svc])
	}
	if opts.ConnectAdapter {
		for _, svc := range order {
			emitMicroConnectAdapter(g, f, svc, resolved[svc])
		}
	}

	hash := descriptorHash(tools)
	g.P("// ContractVersion is the tag this binding was generated from, stamped")
	g.P("// from the contract_version plugin parameter, or \"dev\" when that is")
	g.P("// unset (no tagged build, e.g. this branch).")
	g.P("const ContractVersion = ", fmt.Sprintf("%q", contractVersion))
	g.P()
	g.P("// DescriptorHash is a SHA-256 digest over the WIRE-RELEVANT shape of")
	g.P("// every tool's input and output message in this package, transitively:")
	g.P("// field number, name, cardinality and kind, in field-number order.")
	g.P("//")
	g.P("// It deliberately excludes comments, options and the garm policy")
	g.P("// annotations: those change redaction, which happens after the")
	g.P("// response returns and is garm's business, not the wire's. A hash that")
	g.P("// moved when a read: clearance changed would mark every service")
	g.P("// incompatible over a change that cannot break unmarshalling.")
	g.P("const DescriptorHash = ", fmt.Sprintf("%q", hash))
	g.P()

	for _, svc := range order {
		emitMicroToolRefs(g, svc, resolved[svc])
	}
	return nil
}

// microTool pairs a Tool with protogen's own view of its method, resolved
// once per EmitMicro call rather than re-looked-up by each of the four
// per-service emitters below.
type microTool struct {
	Tool
	m *protogen.Method
}

// resolveMicroTools mirrors emitResolver's two generation-time refusals
// (emit.go): a tool with no generated method in this file set, and a
// streaming RPC, which L4 already refuses at lint time — reaching either
// here means EmitMicro was called without Lint, or on a file set that
// split a tool's method from its own service.
func resolveMicroTools(methods map[protoreflect.FullName]*protogen.Method, ts []Tool) ([]microTool, error) {
	out := make([]microTool, 0, len(ts))
	for _, t := range ts {
		m, ok := methods[t.Method.FullName()]
		if !ok {
			return nil, fmt.Errorf("garm-tools: %s: no generated method for this tool "+
				"(is its service in a different Go package?)", t.Method.FullName())
		}
		if m.Desc.IsStreamingClient() || m.Desc.IsStreamingServer() {
			return nil, fmt.Errorf("garm-tools: %s: a streaming RPC cannot be a tool "+
				"(lint rule L4); set exclude: true", t.Method.FullName())
		}
		out = append(out, microTool{Tool: t, m: m})
	}
	return out, nil
}

// toolRefLiteral computes the four toolbind.ToolRef fields for one tool.
// Subject and FQN are both dot-separated because proto names already are:
// there is nothing to configure and nothing to drift (toolbind.ToolRef's
// own doc comment).
func toolRefLiteral(t Tool) (fqn, subject, method, service string) {
	service = string(t.Method.Parent().FullName())
	method = string(t.Method.Name())
	subject = service + "." + method
	fqn = string(t.Method.ParentFile().Package()) + "." + t.Name
	return fqn, subject, method, service
}

// emitMicroHandler writes svc's Handler interface: one method per tool, in
// plain proto signatures (context.Context, *Req) (*Res, error) — no
// connect.Request/connect.Response wrapper, and above all no Unimplemented
// embed. That absence is the entire point: a tool added to the .proto and
// not implemented here is a compile error at every call site that embeds
// this interface, not a runtime Unimplemented answered to a real caller —
// the exact failure emitMount's own Mount refuses on the garm side.
func emitMicroHandler(g *protogen.GeneratedFile, svc string, tools []microTool) {
	g.P("// ", svc, "Handler implements every tool ", svc, " declares, in plain")
	g.P("// proto signatures with no transport wrapper. There is no")
	g.P("// Unimplemented embed: a tool added to the .proto and not implemented")
	g.P("// here fails to COMPILE, rather than mounting and answering")
	g.P("// Unimplemented to a real caller at runtime.")
	g.P("type ", svc, "Handler interface {")
	for _, t := range tools {
		in := g.QualifiedGoIdent(t.m.Input.GoIdent)
		out := g.QualifiedGoIdent(t.m.Output.GoIdent)
		g.P(t.m.GoName, "(", g.QualifiedGoIdent(contextPkg.Ident("Context")), ", *", in, ") (*", out, ", error)")
	}
	g.P("}")
	g.P()
}

// emitMicroServe writes ServeX: one r.Endpoint call per tool, each with a
// request factory and a closure that type-asserts the untyped request,
// calls the handler's own method directly (no connect wrapper), and
// refuses a nil response by naming the procedure rather than dereferencing
// it one line down — mirroring emitResolver's two refusals (emit.go)
// exactly, at the untyped toolbind.Invoke boundary instead of Core's.
//
// ServeX takes a toolbind.Registrar, not a concrete runtime: that is the
// dependency inversion this whole file exists for (package doc comment).
func emitMicroServe(g *protogen.GeneratedFile, svc string, tools []microTool) {
	g.P("// Serve", svc, " registers one micro endpoint per tool ", svc, " declares.")
	g.P("func Serve", svc, "(r ", g.QualifiedGoIdent(toolbindPkg.Ident("Registrar")), ", h ", svc, "Handler) error {")
	for _, t := range tools {
		fqn, subject, method, service := toolRefLiteral(t.Tool)
		in := g.QualifiedGoIdent(t.m.Input.GoIdent)

		g.P("if err := r.Endpoint(")
		g.P(g.QualifiedGoIdent(toolbindPkg.Ident("ToolRef")), "{")
		g.P("FQN: ", fmt.Sprintf("%q", fqn), ",")
		g.P("Subject: ", fmt.Sprintf("%q", subject), ",")
		g.P("Method: ", fmt.Sprintf("%q", method), ",")
		g.P("Service: ", fmt.Sprintf("%q", service), ",")
		g.P("ContractVersion: ContractVersion,")
		g.P("DescriptorHash: DescriptorHash,")
		g.P("},")
		g.P("func() ", g.QualifiedGoIdent(protoPkg.Ident("Message")), " { return new(", in, ") },")
		g.P("func(ctx ", g.QualifiedGoIdent(contextPkg.Ident("Context")), ", req ",
			g.QualifiedGoIdent(protoPkg.Ident("Message")), ") (",
			g.QualifiedGoIdent(protoPkg.Ident("Message")), ", error) {")
		g.P("in, ok := req.(*", in, ")")
		g.P("if !ok {")
		g.P("return nil, ", g.QualifiedGoIdent(fmtPkg.Ident("Errorf")), "(",
			fmt.Sprintf("%q", subject+": request is %T, want %T"), ", req, (*", in, ")(nil))")
		g.P("}")
		g.P("res, err := h.", t.m.GoName, "(ctx, in)")
		g.P("if err != nil {")
		g.P("return nil, err")
		g.P("}")
		g.P("if res == nil {")
		// connect's own unary handler panics on (nil, nil) rather than
		// serialising it; here it would be a nil-pointer dereference one
		// line down (the `return res, nil` below). Name the procedure
		// instead of reaching it.
		g.P("return nil, ", g.QualifiedGoIdent(fmtPkg.Ident("Errorf")), "(",
			fmt.Sprintf("%q", subject+": handler returned no response and no error"), ")")
		g.P("}")
		g.P("return res, nil")
		g.P("},")
		g.P("); err != nil {")
		g.P("return err")
		g.P("}")
	}
	g.P("return nil")
	g.P("}")
	g.P()
}

// emitMicroConnectAdapter writes XAsConnect and its unexported adapter
// type, so one Handler implementation stays servable three ways (over
// micro via ServeX, and over HTTP/connect via garm's own toolplane
// wiring) without forcing connect.Request/connect.Response wrappers into a
// signature that never speaks HTTP (tools-server-design 2.5).
func emitMicroConnectAdapter(g *protogen.GeneratedFile, f *protogen.File, svc string, tools []microTool) {
	pkgName, iface := ConnectNames(string(f.GoPackageName), svc)
	connectIdent := protogen.GoImportPath(path.Join(string(f.GoImportPath), pkgName)).Ident(iface)
	adapterType := lowerFirst(svc) + "Adapter"

	g.P("// ", svc, "AsConnect adapts h to ", pkgName, ".", iface, ", so the same")
	g.P("// implementation can be mounted on garm's own connect surface as well")
	g.P("// as served over micro.")
	g.P("func ", svc, "AsConnect(h ", svc, "Handler) ", g.QualifiedGoIdent(connectIdent), " {")
	g.P("return &", adapterType, "{h: h}")
	g.P("}")
	g.P()
	g.P("type ", adapterType, " struct{ h ", svc, "Handler }")
	g.P()
	for _, t := range tools {
		in := g.QualifiedGoIdent(t.m.Input.GoIdent)
		out := g.QualifiedGoIdent(t.m.Output.GoIdent)
		g.P("func (a *", adapterType, ") ", t.m.GoName, "(ctx ", g.QualifiedGoIdent(contextPkg.Ident("Context")),
			", req *", g.QualifiedGoIdent(connectRPCPkg.Ident("Request")), "[", in, "]) (*",
			g.QualifiedGoIdent(connectRPCPkg.Ident("Response")), "[", out, "], error) {")
		g.P("res, err := a.h.", t.m.GoName, "(ctx, req.Msg)")
		g.P("if err != nil {")
		g.P("return nil, err")
		g.P("}")
		g.P("return ", g.QualifiedGoIdent(connectRPCPkg.Ident("NewResponse")), "(res), nil")
		g.P("}")
		g.P()
	}
}

// emitMicroToolRefs writes XTools: svc's tool identities as data, so a
// runtime can enumerate what ServeX registers without calling it (e.g. for
// $SRV.INFO's declared-tool-FQN advertisement).
func emitMicroToolRefs(g *protogen.GeneratedFile, svc string, tools []microTool) {
	g.P("var ", svc, "Tools = []", g.QualifiedGoIdent(toolbindPkg.Ident("ToolRef")), "{")
	for _, t := range tools {
		fqn, subject, method, service := toolRefLiteral(t.Tool)
		g.P("{")
		g.P("FQN: ", fmt.Sprintf("%q", fqn), ",")
		g.P("Subject: ", fmt.Sprintf("%q", subject), ",")
		g.P("Method: ", fmt.Sprintf("%q", method), ",")
		g.P("Service: ", fmt.Sprintf("%q", service), ",")
		g.P("ContractVersion: ContractVersion,")
		g.P("DescriptorHash: DescriptorHash,")
		g.P("},")
	}
	g.P("}")
	g.P()
}

// descriptorHash is a SHA-256 digest over the WIRE-RELEVANT shape of every
// tool's input and output message, transitively: field number, field
// name, cardinality and kind, in field-number order. It walks each
// distinct message exactly once (by full name), which both dedupes a
// message reached from more than one tool and breaks cycles in a
// self- or mutually-referential message graph.
//
// It deliberately never touches a FieldDescriptor's Options() or a
// MessageDescriptor's own comments/options: those carry the garm policy
// annotations (read/write clearance, compartments, redaction), which
// change what a caller is ALLOWED to see, not what can be unmarshalled off
// the wire. Hashing them would move DescriptorHash on a clearance change
// that cannot break a single client — see this function's callers' doc
// comment.
// DescriptorHash is the digest a service advertises and a catalogue records.
//
// Exported so the catalogue builder can stamp the same value the generator
// emits. One implementation, deliberately: a hash computed two ways is a hash
// that eventually disagrees with itself, and the whole point of this one is
// that two sides can compare it.
func DescriptorHash(tools []Tool) string { return descriptorHash(tools) }

func descriptorHash(tools []Tool) string {
	h := sha256.New()
	visited := map[protoreflect.FullName]bool{}

	var walk func(md protoreflect.MessageDescriptor)
	walk = func(md protoreflect.MessageDescriptor) {
		if visited[md.FullName()] {
			return
		}
		visited[md.FullName()] = true

		fields := md.Fields()
		ordered := make([]protoreflect.FieldDescriptor, fields.Len())
		for i := range ordered {
			ordered[i] = fields.Get(i)
		}
		sort.Slice(ordered, func(i, j int) bool { return ordered[i].Number() < ordered[j].Number() })

		fmt.Fprintf(h, "message %s\n", md.FullName())
		for _, fd := range ordered {
			fmt.Fprintf(h, "field %d %s %s %s\n", fd.Number(), fd.Name(), fd.Cardinality(), fd.Kind())
		}
		// Recurse after this message's own field list is fully written, so
		// one message's shape is never interleaved with another's in the
		// hashed stream.
		for _, fd := range ordered {
			if fd.Kind() == protoreflect.MessageKind || fd.Kind() == protoreflect.GroupKind {
				walk(fd.Message())
			}
		}
	}

	for _, t := range tools {
		walk(t.Method.Input())
		walk(t.Method.Output())
	}
	return hex.EncodeToString(h.Sum(nil))
}

// lowerFirst lower-cases a Go identifier's leading rune, for an unexported
// name derived from an exported one (a service name, here) — "Accounts
// Service" -> "accountsService".
func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	r[0] = unicode.ToLower(r[0])
	return string(r)
}
