// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: fixture.proto

package testdata

import (
	_ "github.com/garm-ai/garm/contracts/garm/tool/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Profile struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Locale     string                 `protobuf:"bytes,2,opt,name=locale,proto3" json:"locale,omitempty"` // inherits INTERNAL
	Email      *string                `protobuf:"bytes,3,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Billing    *Billing               `protobuf:"bytes,4,opt,name=billing,proto3,oneof" json:"billing,omitempty"`
	NationalId *string                `protobuf:"bytes,5,opt,name=national_id,json=nationalId,proto3,oneof" json:"national_id,omitempty"`
	Tags       map[string]string      `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // inherits INTERNAL
	// Deliberately named to share a dotted-prefix with the "billing" subtree
	// ("billing_summary" starts with "billing" as a string but is not beneath
	// it as a path: "billing." is not a prefix of "billing_summary"). Denied
	// on its own terms (RESTRICTED) so a resolver that mistakenly treats
	// string-prefix as path-prefix will wrongly prune it from Deny.
	BillingSummary *string `protobuf:"bytes,7,opt,name=billing_summary,json=billingSummary,proto3,oneof" json:"billing_summary,omitempty"`
	// Message-valued map: Compile must recurse into the value type (Billing),
	// and denial of the map field itself must gate (and clear) the whole map,
	// exactly like a non-map message-typed field does.
	BillingById map[string]*Billing `protobuf:"bytes,8,rep,name=billing_by_id,json=billingById,proto3" json:"billing_by_id,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Scalar-valued map with a non-omit redaction, so the sanitizer's map
	// branch can be exercised end to end through the real Compile/Resolve
	// pipeline rather than a hand-built Action.
	Attributes    map[string]string `protobuf:"bytes,9,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_fixture_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_fixture_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_fixture_proto_rawDescGZIP(), []int{0}
}

func (x *Profile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Profile) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *Profile) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *Profile) GetBilling() *Billing {
	if x != nil {
		return x.Billing
	}
	return nil
}

func (x *Profile) GetNationalId() string {
	if x != nil && x.NationalId != nil {
		return *x.NationalId
	}
	return ""
}

func (x *Profile) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Profile) GetBillingSummary() string {
	if x != nil && x.BillingSummary != nil {
		return *x.BillingSummary
	}
	return ""
}

func (x *Profile) GetBillingById() map[string]*Billing {
	if x != nil {
		return x.BillingById
	}
	return nil
}

func (x *Profile) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type Billing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardLast4     string                 `protobuf:"bytes,1,opt,name=card_last4,json=cardLast4,proto3" json:"card_last4,omitempty"`
	Iban          string                 `protobuf:"bytes,2,opt,name=iban,proto3" json:"iban,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Billing) Reset() {
	*x = Billing{}
	mi := &file_fixture_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Billing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Billing) ProtoMessage() {}

func (x *Billing) ProtoReflect() protoreflect.Message {
	mi := &file_fixture_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Billing.ProtoReflect.Descriptor instead.
func (*Billing) Descriptor() ([]byte, []int) {
	return file_fixture_proto_rawDescGZIP(), []int{1}
}

func (x *Billing) GetCardLast4() string {
	if x != nil {
		return x.CardLast4
	}
	return ""
}

func (x *Billing) GetIban() string {
	if x != nil {
		return x.Iban
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*Profile             `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_fixture_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fixture_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_fixture_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResponse) GetProfiles() []*Profile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

func (x *SearchResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_fixture_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fixture_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_fixture_proto_rawDescGZIP(), []int{3}
}

func (x *GetProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_fixture_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fixture_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_fixture_proto_rawDescGZIP(), []int{4}
}

func (x *GetProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type UpdateProfileRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	UserId      string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName *string                `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	// Read is cheap (INTERNAL); writing it requires much more (RESTRICTED).
	// Exists so an explicit `write:` override has at least one real exerciser
	// in the repo — every other field policy leaves write unset and inherits
	// read, which never exercises the branch in Compile that reads GetWrite().
	AdminNote     *string `protobuf:"bytes,3,opt,name=admin_note,json=adminNote,proto3,oneof" json:"admin_note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_fixture_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fixture_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_fixture_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateProfileRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *UpdateProfileRequest) GetAdminNote() string {
	if x != nil && x.AdminNote != nil {
		return *x.AdminNote
	}
	return ""
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_fixture_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fixture_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_fixture_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// Deliberately carries no field policy and no message default. Compile must
// reject it. Not reachable from any tool, so the lint in a later task will
// not walk it.
type Unlabeled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Oops          string                 `protobuf:"bytes,1,opt,name=oops,proto3" json:"oops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unlabeled) Reset() {
	*x = Unlabeled{}
	mi := &file_fixture_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unlabeled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unlabeled) ProtoMessage() {}

func (x *Unlabeled) ProtoReflect() protoreflect.Message {
	mi := &file_fixture_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unlabeled.ProtoReflect.Descriptor instead.
func (*Unlabeled) Descriptor() ([]byte, []int) {
	return file_fixture_proto_rawDescGZIP(), []int{7}
}

func (x *Unlabeled) GetOops() string {
	if x != nil {
		return x.Oops
	}
	return ""
}

// Node is self-recursive, and deliberately NOT reachable from any tool (so
// `make gen`'s lint does not walk it and the build stays green). It exists
// so TestCompileRejectsARecursiveMessage can drive the real Compile over a
// real generated descriptor.
//
// Shape taken verbatim from the leak the final branch review found: a
// classified `secret` beside a self-reference. A Compile that stopped at the
// cycle instead of erroring would emit actions for `child` and `secret` and
// nothing for `child.secret`, so a PUBLIC caller would receive every nested
// secret in the clear.
type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Child         *Node                  `protobuf:"bytes,1,opt,name=child,proto3,oneof" json:"child,omitempty"`
	Secret        *string                `protobuf:"bytes,2,opt,name=secret,proto3,oneof" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_fixture_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_fixture_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_fixture_proto_rawDescGZIP(), []int{8}
}

func (x *Node) GetChild() *Node {
	if x != nil {
		return x.Child
	}
	return nil
}

func (x *Node) GetSecret() string {
	if x != nil && x.Secret != nil {
		return *x.Secret
	}
	return ""
}

// LoopA/LoopB are the MUTUAL form of the same defect: neither message
// references itself, so a cycle check that only compared a field's type
// against its own parent would miss them entirely.
type LoopA struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	B             *LoopB                 `protobuf:"bytes,1,opt,name=b,proto3,oneof" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoopA) Reset() {
	*x = LoopA{}
	mi := &file_fixture_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoopA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoopA) ProtoMessage() {}

func (x *LoopA) ProtoReflect() protoreflect.Message {
	mi := &file_fixture_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoopA.ProtoReflect.Descriptor instead.
func (*LoopA) Descriptor() ([]byte, []int) {
	return file_fixture_proto_rawDescGZIP(), []int{9}
}

func (x *LoopA) GetB() *LoopB {
	if x != nil {
		return x.B
	}
	return nil
}

type LoopB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             *LoopA                 `protobuf:"bytes,1,opt,name=a,proto3,oneof" json:"a,omitempty"`
	Secret        *string                `protobuf:"bytes,2,opt,name=secret,proto3,oneof" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoopB) Reset() {
	*x = LoopB{}
	mi := &file_fixture_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoopB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoopB) ProtoMessage() {}

func (x *LoopB) ProtoReflect() protoreflect.Message {
	mi := &file_fixture_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoopB.ProtoReflect.Descriptor instead.
func (*LoopB) Descriptor() ([]byte, []int) {
	return file_fixture_proto_rawDescGZIP(), []int{10}
}

func (x *LoopB) GetA() *LoopA {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *LoopB) GetSecret() string {
	if x != nil && x.Secret != nil {
		return *x.Secret
	}
	return ""
}

var File_fixture_proto protoreflect.FileDescriptor

const file_fixture_proto_rawDesc = "" +
	"\n" +
	"\rfixture.proto\x12\x0fpolicy.testdata\x1a\x17garm/tool/v1/tool.proto\"\xbb\x06\n" +
	"\aProfile\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\x8a\xb5\x18\x06\b\n" +
	"\"\x02\x12\x00R\x02id\x12\x16\n" +
	"\x06locale\x18\x02 \x01(\tR\x06locale\x122\n" +
	"\x05email\x18\x03 \x01(\tB\x17\x8a\xb5\x18\x13\b\x1e\x1a\vpii-contact\"\x02\"\x00H\x00R\x05email\x88\x01\x01\x12N\n" +
	"\abilling\x18\x04 \x01(\v2\x18.policy.testdata.BillingB\x15\x8a\xb5\x18\x11\b\x1e\x1a\tfinancial\"\x02\n" +
	"\x00H\x01R\abilling\x88\x01\x01\x122\n" +
	"\vnational_id\x18\x05 \x01(\tB\f\x8a\xb5\x18\b\b(\"\x02\n" +
	"\x00(\x01H\x02R\n" +
	"nationalId\x88\x01\x01\x126\n" +
	"\x04tags\x18\x06 \x03(\v2\".policy.testdata.Profile.TagsEntryR\x04tags\x128\n" +
	"\x0fbilling_summary\x18\a \x01(\tB\n" +
	"\x8a\xb5\x18\x06\b(\"\x02\n" +
	"\x00H\x03R\x0ebillingSummary\x88\x01\x01\x12d\n" +
	"\rbilling_by_id\x18\b \x03(\v2).policy.testdata.Profile.BillingByIdEntryB\x15\x8a\xb5\x18\x11\b\x1e\x1a\tfinancial\"\x02\n" +
	"\x00R\vbillingById\x12T\n" +
	"\n" +
	"attributes\x18\t \x03(\v2(.policy.testdata.Profile.AttributesEntryB\n" +
	"\x8a\xb5\x18\x06\b\x1e\"\x02\x12\x00R\n" +
	"attributes\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aX\n" +
	"\x10BillingByIdEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.policy.testdata.BillingR\x05value:\x028\x01\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:\n" +
	"\x9a\xb5\x18\x06\b\x14\"\x02\x12\x00B\b\n" +
	"\x06_emailB\n" +
	"\n" +
	"\b_billingB\x0e\n" +
	"\f_national_idB\x12\n" +
	"\x10_billing_summary\"|\n" +
	"\aBilling\x12\x1d\n" +
	"\n" +
	"card_last4\x18\x01 \x01(\tR\tcardLast4\x12;\n" +
	"\x04iban\x18\x02 \x01(\tB'\x8a\xb5\x18#\b(\x1a\tfinancial\"\x14*\x12\b\x04\x1a\x0ereconciliationR\x04iban:\x15\x9a\xb5\x18\x11\b\x1e\x1a\tfinancial\"\x02\x12\x00\"l\n" +
	"\x0eSearchResponse\x12<\n" +
	"\bprofiles\x18\x01 \x03(\v2\x18.policy.testdata.ProfileB\x06\x8a\xb5\x18\x02\b\x14R\bprofiles\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total:\x06\x9a\xb5\x18\x02\b\n" +
	"\"8\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId:\n" +
	"\x9a\xb5\x18\x06\b\n" +
	"\"\x02\x12\x00\"P\n" +
	"\x12GetProfileResponse\x122\n" +
	"\aprofile\x18\x01 \x01(\v2\x18.policy.testdata.ProfileR\aprofile:\x06\x9a\xb5\x18\x02\b\n" +
	"\"\xb1\x01\n" +
	"\x14UpdateProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12&\n" +
	"\fdisplay_name\x18\x02 \x01(\tH\x00R\vdisplayName\x88\x01\x01\x12,\n" +
	"\n" +
	"admin_note\x18\x03 \x01(\tB\b\x8a\xb5\x18\x04\b\x14\x10(H\x01R\tadminNote\x88\x01\x01:\n" +
	"\x9a\xb5\x18\x06\b\n" +
	"\"\x02\x12\x00B\x0f\n" +
	"\r_display_nameB\r\n" +
	"\v_admin_note\"S\n" +
	"\x15UpdateProfileResponse\x122\n" +
	"\aprofile\x18\x01 \x01(\v2\x18.policy.testdata.ProfileR\aprofile:\x06\x9a\xb5\x18\x02\b\n" +
	"\"\x1f\n" +
	"\tUnlabeled\x12\x12\n" +
	"\x04oops\x18\x01 \x01(\tR\x04oops\"\x82\x01\n" +
	"\x04Node\x120\n" +
	"\x05child\x18\x01 \x01(\v2\x15.policy.testdata.NodeH\x00R\x05child\x88\x01\x01\x12'\n" +
	"\x06secret\x18\x02 \x01(\tB\n" +
	"\x8a\xb5\x18\x06\b(\"\x02\n" +
	"\x00H\x01R\x06secret\x88\x01\x01:\n" +
	"\x9a\xb5\x18\x06\b\n" +
	"\"\x02\x12\x00B\b\n" +
	"\x06_childB\t\n" +
	"\a_secret\"D\n" +
	"\x05LoopA\x12)\n" +
	"\x01b\x18\x01 \x01(\v2\x16.policy.testdata.LoopBH\x00R\x01b\x88\x01\x01:\n" +
	"\x9a\xb5\x18\x06\b\n" +
	"\"\x02\x12\x00B\x04\n" +
	"\x02_b\"x\n" +
	"\x05LoopB\x12)\n" +
	"\x01a\x18\x01 \x01(\v2\x16.policy.testdata.LoopAH\x00R\x01a\x88\x01\x01\x12'\n" +
	"\x06secret\x18\x02 \x01(\tB\n" +
	"\x8a\xb5\x18\x06\b(\"\x02\n" +
	"\x00H\x01R\x06secret\x88\x01\x01:\n" +
	"\x9a\xb5\x18\x06\b\n" +
	"\"\x02\x12\x00B\x04\n" +
	"\x02_aB\t\n" +
	"\a_secret2\xc5\x02\n" +
	"\vTestService\x12\x90\x01\n" +
	"\n" +
	"GetProfile\x12\".policy.testdata.GetProfileRequest\x1a#.policy.testdata.GetProfileResponse\"9\x92\xb5\x185\n" +
	"\vget_profile\x1a\x18Look up a profile by id. \x01(\x14B\x04\b\x01\x10\x03J\x02\b\x01\x12\xa2\x01\n" +
	"\rUpdateProfile\x12%.policy.testdata.UpdateProfileRequest\x1a&.policy.testdata.UpdateProfileResponse\"B\x92\xb5\x18>\n" +
	"\x0eupdate_profile\x1a\x1eUpdate mutable profile fields. \x02(\x1eB\x04\b\x01\x10\x03J\x02\b\x01B]\xa2\xb5\x18'\n" +
	"\v\n" +
	"\tfinancial\n" +
	"\r\n" +
	"\vpii-contact\n" +
	"\t\n" +
	"\asupportZ0github.com/garm-ai/garm/policy/testdata;testdatab\x06proto3"

var (
	file_fixture_proto_rawDescOnce sync.Once
	file_fixture_proto_rawDescData []byte
)

func file_fixture_proto_rawDescGZIP() []byte {
	file_fixture_proto_rawDescOnce.Do(func() {
		file_fixture_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fixture_proto_rawDesc), len(file_fixture_proto_rawDesc)))
	})
	return file_fixture_proto_rawDescData
}

var file_fixture_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_fixture_proto_goTypes = []any{
	(*Profile)(nil),               // 0: policy.testdata.Profile
	(*Billing)(nil),               // 1: policy.testdata.Billing
	(*SearchResponse)(nil),        // 2: policy.testdata.SearchResponse
	(*GetProfileRequest)(nil),     // 3: policy.testdata.GetProfileRequest
	(*GetProfileResponse)(nil),    // 4: policy.testdata.GetProfileResponse
	(*UpdateProfileRequest)(nil),  // 5: policy.testdata.UpdateProfileRequest
	(*UpdateProfileResponse)(nil), // 6: policy.testdata.UpdateProfileResponse
	(*Unlabeled)(nil),             // 7: policy.testdata.Unlabeled
	(*Node)(nil),                  // 8: policy.testdata.Node
	(*LoopA)(nil),                 // 9: policy.testdata.LoopA
	(*LoopB)(nil),                 // 10: policy.testdata.LoopB
	nil,                           // 11: policy.testdata.Profile.TagsEntry
	nil,                           // 12: policy.testdata.Profile.BillingByIdEntry
	nil,                           // 13: policy.testdata.Profile.AttributesEntry
}
var file_fixture_proto_depIdxs = []int32{
	1,  // 0: policy.testdata.Profile.billing:type_name -> policy.testdata.Billing
	11, // 1: policy.testdata.Profile.tags:type_name -> policy.testdata.Profile.TagsEntry
	12, // 2: policy.testdata.Profile.billing_by_id:type_name -> policy.testdata.Profile.BillingByIdEntry
	13, // 3: policy.testdata.Profile.attributes:type_name -> policy.testdata.Profile.AttributesEntry
	0,  // 4: policy.testdata.SearchResponse.profiles:type_name -> policy.testdata.Profile
	0,  // 5: policy.testdata.GetProfileResponse.profile:type_name -> policy.testdata.Profile
	0,  // 6: policy.testdata.UpdateProfileResponse.profile:type_name -> policy.testdata.Profile
	8,  // 7: policy.testdata.Node.child:type_name -> policy.testdata.Node
	10, // 8: policy.testdata.LoopA.b:type_name -> policy.testdata.LoopB
	9,  // 9: policy.testdata.LoopB.a:type_name -> policy.testdata.LoopA
	1,  // 10: policy.testdata.Profile.BillingByIdEntry.value:type_name -> policy.testdata.Billing
	3,  // 11: policy.testdata.TestService.GetProfile:input_type -> policy.testdata.GetProfileRequest
	5,  // 12: policy.testdata.TestService.UpdateProfile:input_type -> policy.testdata.UpdateProfileRequest
	4,  // 13: policy.testdata.TestService.GetProfile:output_type -> policy.testdata.GetProfileResponse
	6,  // 14: policy.testdata.TestService.UpdateProfile:output_type -> policy.testdata.UpdateProfileResponse
	13, // [13:15] is the sub-list for method output_type
	11, // [11:13] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_fixture_proto_init() }
func file_fixture_proto_init() {
	if File_fixture_proto != nil {
		return
	}
	file_fixture_proto_msgTypes[0].OneofWrappers = []any{}
	file_fixture_proto_msgTypes[5].OneofWrappers = []any{}
	file_fixture_proto_msgTypes[8].OneofWrappers = []any{}
	file_fixture_proto_msgTypes[9].OneofWrappers = []any{}
	file_fixture_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fixture_proto_rawDesc), len(file_fixture_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fixture_proto_goTypes,
		DependencyIndexes: file_fixture_proto_depIdxs,
		MessageInfos:      file_fixture_proto_msgTypes,
	}.Build()
	File_fixture_proto = out.File
	file_fixture_proto_goTypes = nil
	file_fixture_proto_depIdxs = nil
}
