// The catalogue: what a garm daemon serves.
//
// A daemon does not know its tools at build time. It loads one of these at
// boot and serves exactly what it declares, which is what makes adding a tool
// a catalogue rebuild rather than a release of the governance binary.
//
// This file is the contract between whoever BUILDS a catalogue and the daemon
// that LOADS one. It lives beside the annotations because it is exactly that:
// a contract, not an implementation detail of either side.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: garm/catalogue/v1/catalogue.proto

package cataloguev1

import (
	v1 "github.com/garm-ai/garm/contracts/garm/tool/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Catalogue is the artifact. One file, self-contained, identified by the
// digest of its own bytes — which is computed by the loader over what it was
// handed, never recorded in here. A digest a producer asserts about itself is
// not a digest.
type Catalogue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The annotation schema this catalogue's declarations were written against.
	//
	// A daemon reads the current version and the two previous, and refuses
	// anything outside that window at boot rather than loading a policy
	// document it only partly understands.
	//
	// Scoped to garm.tool.v1 deliberately. A catalogue may carry declarations
	// annotated in other namespaces — an agent runner's, say — and a daemon
	// ignores those entirely. Widening this check to every extension namespace
	// would refuse such a catalogue at boot, which is agent-awareness acquired
	// through an error message.
	AnnotationSchemaVersion uint32 `protobuf:"varint,1,opt,name=annotation_schema_version,json=annotationSchemaVersion,proto3" json:"annotation_schema_version,omitempty"`
	// Every proto file the declarations need, including their transitive
	// imports. Self-contained on purpose: a daemon resolves nothing at boot and
	// reaches no registry.
	Files *descriptorpb.FileDescriptorSet `protobuf:"bytes,2,opt,name=files,proto3" json:"files,omitempty"`
	// The taxonomy every declaration in `files` refers to, aggregated across
	// packages at build time.
	//
	// Aggregated here rather than derived at load because the build is where
	// two packages declaring the same compartment two ways can be caught, and
	// a daemon that had to reconcile them would be deciding policy.
	Compartments []*v1.Decl `protobuf:"bytes,3,rep,name=compartments,proto3" json:"compartments,omitempty"`
	ToolSets     []*v1.Decl `protobuf:"bytes,4,rep,name=tool_sets,json=toolSets,proto3" json:"tool_sets,omitempty"`
	// Where this came from. Not trusted for anything — it is for the operator
	// reading a startup line and the engineer reading an incident.
	Provenance *Provenance `protobuf:"bytes,5,opt,name=provenance,proto3" json:"provenance,omitempty"`
	// Field documentation, keyed by each field's full proto name — for example
	// "acme.accounts.v1.AccountSummary.iban".
	//
	// It is here because SourceCodeInfo is stripped from `files` before the
	// artifact is written, and that strip is worth roughly half the memory a
	// loaded catalogue retains and half its size on disk. SourceCodeInfo
	// carries spans and paths for every token in every file; a schema only ever
	// needed the prose.
	//
	// Prose matters enough to carry deliberately rather than lose. A projected
	// schema without it shows a model typed fields with no indication of what
	// they mean or why it may read one and not another, which is a large
	// accuracy loss for the one reader the schema exists for.
	//
	// Note what is NOT here: the schemas themselves. Those are projected per
	// principal — a field a caller may not read is absent, not marked — so
	// there is one schema per (tool, clearance, compartments) rather than one
	// per tool. The only schema that could be precomputed is the unprojected
	// one, which is exactly the one that must never be served.
	FieldDocs map[string]string `protobuf:"bytes,6,rep,name=field_docs,json=fieldDocs,proto3" json:"field_docs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The descriptor hash of each proto package that declares tools, keyed by
	// proto package name.
	//
	// This is what makes reconciliation possible, and without it the system's
	// central promise is an assumption. A service advertises the same digest on
	// $SRV.INFO, computed by the generator from the same descriptors; a daemon
	// compares the two and refuses to route on a mismatch.
	//
	// It has to be here rather than recomputed at load. Protobuf's wire format
	// is permissive by design — unknown fields ignored, absent fields
	// defaulted — so a service built from a different contract does not fail,
	// it ANSWERS, with fields read as something else. Governed, ledgered, and
	// wrong. A mismatch that nothing detects is the only failure mode in this
	// design that does not announce itself.
	//
	// Covers the wire shape only: field number, name, cardinality and kind,
	// transitively. Not comments, not options, not the garm annotations —
	// those change redaction, which happens after the response returns, and a
	// hash that moved when a clearance changed would mark every service
	// incompatible over something that cannot break unmarshalling.
	DescriptorHashes map[string]string `protobuf:"bytes,7,rep,name=descriptor_hashes,json=descriptorHashes,proto3" json:"descriptor_hashes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Catalogue) Reset() {
	*x = Catalogue{}
	mi := &file_garm_catalogue_v1_catalogue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Catalogue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Catalogue) ProtoMessage() {}

func (x *Catalogue) ProtoReflect() protoreflect.Message {
	mi := &file_garm_catalogue_v1_catalogue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Catalogue.ProtoReflect.Descriptor instead.
func (*Catalogue) Descriptor() ([]byte, []int) {
	return file_garm_catalogue_v1_catalogue_proto_rawDescGZIP(), []int{0}
}

func (x *Catalogue) GetAnnotationSchemaVersion() uint32 {
	if x != nil {
		return x.AnnotationSchemaVersion
	}
	return 0
}

func (x *Catalogue) GetFiles() *descriptorpb.FileDescriptorSet {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *Catalogue) GetCompartments() []*v1.Decl {
	if x != nil {
		return x.Compartments
	}
	return nil
}

func (x *Catalogue) GetToolSets() []*v1.Decl {
	if x != nil {
		return x.ToolSets
	}
	return nil
}

func (x *Catalogue) GetProvenance() *Provenance {
	if x != nil {
		return x.Provenance
	}
	return nil
}

func (x *Catalogue) GetFieldDocs() map[string]string {
	if x != nil {
		return x.FieldDocs
	}
	return nil
}

func (x *Catalogue) GetDescriptorHashes() map[string]string {
	if x != nil {
		return x.DescriptorHashes
	}
	return nil
}

// Provenance is what a human needs to answer "where did this come from".
type Provenance struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The tool that wrote it, with its version. "garm/v1.4.2".
	Producer string `protobuf:"bytes,1,opt,name=producer,proto3" json:"producer,omitempty"`
	// The proto compiler and version used, because identical source compiled by
	// different compilers can produce different descriptor bytes and therefore
	// a different digest. Recording it makes a digest mismatch diagnosable
	// instead of mysterious.
	Compiler string                 `protobuf:"bytes,2,opt,name=compiler,proto3" json:"compiler,omitempty"`
	BuiltAt  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=built_at,json=builtAt,proto3" json:"built_at,omitempty"`
	// Free-form: a repository and commit, a pipeline id, whatever the builder
	// knows. Never parsed.
	Source        string `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Provenance) Reset() {
	*x = Provenance{}
	mi := &file_garm_catalogue_v1_catalogue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provenance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provenance) ProtoMessage() {}

func (x *Provenance) ProtoReflect() protoreflect.Message {
	mi := &file_garm_catalogue_v1_catalogue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provenance.ProtoReflect.Descriptor instead.
func (*Provenance) Descriptor() ([]byte, []int) {
	return file_garm_catalogue_v1_catalogue_proto_rawDescGZIP(), []int{1}
}

func (x *Provenance) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

func (x *Provenance) GetCompiler() string {
	if x != nil {
		return x.Compiler
	}
	return ""
}

func (x *Provenance) GetBuiltAt() *timestamppb.Timestamp {
	if x != nil {
		return x.BuiltAt
	}
	return nil
}

func (x *Provenance) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

var File_garm_catalogue_v1_catalogue_proto protoreflect.FileDescriptor

const file_garm_catalogue_v1_catalogue_proto_rawDesc = "" +
	"\n" +
	"!garm/catalogue/v1/catalogue.proto\x12\x11garm.catalogue.v1\x1a\x17garm/tool/v1/tool.proto\x1a google/protobuf/descriptor.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd9\x04\n" +
	"\tCatalogue\x12:\n" +
	"\x19annotation_schema_version\x18\x01 \x01(\rR\x17annotationSchemaVersion\x128\n" +
	"\x05files\x18\x02 \x01(\v2\".google.protobuf.FileDescriptorSetR\x05files\x126\n" +
	"\fcompartments\x18\x03 \x03(\v2\x12.garm.tool.v1.DeclR\fcompartments\x12/\n" +
	"\ttool_sets\x18\x04 \x03(\v2\x12.garm.tool.v1.DeclR\btoolSets\x12=\n" +
	"\n" +
	"provenance\x18\x05 \x01(\v2\x1d.garm.catalogue.v1.ProvenanceR\n" +
	"provenance\x12J\n" +
	"\n" +
	"field_docs\x18\x06 \x03(\v2+.garm.catalogue.v1.Catalogue.FieldDocsEntryR\tfieldDocs\x12_\n" +
	"\x11descriptor_hashes\x18\a \x03(\v22.garm.catalogue.v1.Catalogue.DescriptorHashesEntryR\x10descriptorHashes\x1a<\n" +
	"\x0eFieldDocsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aC\n" +
	"\x15DescriptorHashesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x93\x01\n" +
	"\n" +
	"Provenance\x12\x1a\n" +
	"\bproducer\x18\x01 \x01(\tR\bproducer\x12\x1a\n" +
	"\bcompiler\x18\x02 \x01(\tR\bcompiler\x125\n" +
	"\bbuilt_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\abuiltAt\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06sourceBAZ?github.com/garm-ai/garm/contracts/garm/catalogue/v1;cataloguev1b\x06proto3"

var (
	file_garm_catalogue_v1_catalogue_proto_rawDescOnce sync.Once
	file_garm_catalogue_v1_catalogue_proto_rawDescData []byte
)

func file_garm_catalogue_v1_catalogue_proto_rawDescGZIP() []byte {
	file_garm_catalogue_v1_catalogue_proto_rawDescOnce.Do(func() {
		file_garm_catalogue_v1_catalogue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_garm_catalogue_v1_catalogue_proto_rawDesc), len(file_garm_catalogue_v1_catalogue_proto_rawDesc)))
	})
	return file_garm_catalogue_v1_catalogue_proto_rawDescData
}

var file_garm_catalogue_v1_catalogue_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_garm_catalogue_v1_catalogue_proto_goTypes = []any{
	(*Catalogue)(nil),                      // 0: garm.catalogue.v1.Catalogue
	(*Provenance)(nil),                     // 1: garm.catalogue.v1.Provenance
	nil,                                    // 2: garm.catalogue.v1.Catalogue.FieldDocsEntry
	nil,                                    // 3: garm.catalogue.v1.Catalogue.DescriptorHashesEntry
	(*descriptorpb.FileDescriptorSet)(nil), // 4: google.protobuf.FileDescriptorSet
	(*v1.Decl)(nil),                        // 5: garm.tool.v1.Decl
	(*timestamppb.Timestamp)(nil),          // 6: google.protobuf.Timestamp
}
var file_garm_catalogue_v1_catalogue_proto_depIdxs = []int32{
	4, // 0: garm.catalogue.v1.Catalogue.files:type_name -> google.protobuf.FileDescriptorSet
	5, // 1: garm.catalogue.v1.Catalogue.compartments:type_name -> garm.tool.v1.Decl
	5, // 2: garm.catalogue.v1.Catalogue.tool_sets:type_name -> garm.tool.v1.Decl
	1, // 3: garm.catalogue.v1.Catalogue.provenance:type_name -> garm.catalogue.v1.Provenance
	2, // 4: garm.catalogue.v1.Catalogue.field_docs:type_name -> garm.catalogue.v1.Catalogue.FieldDocsEntry
	3, // 5: garm.catalogue.v1.Catalogue.descriptor_hashes:type_name -> garm.catalogue.v1.Catalogue.DescriptorHashesEntry
	6, // 6: garm.catalogue.v1.Provenance.built_at:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_garm_catalogue_v1_catalogue_proto_init() }
func file_garm_catalogue_v1_catalogue_proto_init() {
	if File_garm_catalogue_v1_catalogue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_garm_catalogue_v1_catalogue_proto_rawDesc), len(file_garm_catalogue_v1_catalogue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_garm_catalogue_v1_catalogue_proto_goTypes,
		DependencyIndexes: file_garm_catalogue_v1_catalogue_proto_depIdxs,
		MessageInfos:      file_garm_catalogue_v1_catalogue_proto_msgTypes,
	}.Build()
	File_garm_catalogue_v1_catalogue_proto = out.File
	file_garm_catalogue_v1_catalogue_proto_goTypes = nil
	file_garm_catalogue_v1_catalogue_proto_depIdxs = nil
}
