// The agent manifest, declared on a proto service beside the tools it uses.
//
// A new package rather than a field on garm.tool.v1, because garmd must stay
// agent-blind: it sees Invoke and GetRun as two governed tools and never
// parses anything here. The extension number is outside the 50001-50005 block
// garm.tool.v1 owns, so the two vocabularies can never collide.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: garm/agent/v1/agent.proto

package agentv1

import (
	v1 "github.com/garm-ai/garm/contracts/garm/tool/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mode int32

const (
	Mode_MODE_UNSPECIFIED Mode = 0
	Mode_MODE_REACT       Mode = 1
)

// Enum value maps for Mode.
var (
	Mode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "MODE_REACT",
	}
	Mode_value = map[string]int32{
		"MODE_UNSPECIFIED": 0,
		"MODE_REACT":       1,
	}
)

func (x Mode) Enum() *Mode {
	p := new(Mode)
	*p = x
	return p
}

func (x Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_garm_agent_v1_agent_proto_enumTypes[0].Descriptor()
}

func (Mode) Type() protoreflect.EnumType {
	return &file_garm_agent_v1_agent_proto_enumTypes[0]
}

func (x Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mode.Descriptor instead.
func (Mode) EnumDescriptor() ([]byte, []int) {
	return file_garm_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

type RunState int32

const (
	RunState_RUN_STATE_UNSPECIFIED      RunState = 0
	RunState_RUN_STATE_RUNNING          RunState = 1
	RunState_RUN_STATE_WAITING_APPROVAL RunState = 2
	RunState_RUN_STATE_COMPLETED        RunState = 3
	RunState_RUN_STATE_FAILED           RunState = 4
)

// Enum value maps for RunState.
var (
	RunState_name = map[int32]string{
		0: "RUN_STATE_UNSPECIFIED",
		1: "RUN_STATE_RUNNING",
		2: "RUN_STATE_WAITING_APPROVAL",
		3: "RUN_STATE_COMPLETED",
		4: "RUN_STATE_FAILED",
	}
	RunState_value = map[string]int32{
		"RUN_STATE_UNSPECIFIED":      0,
		"RUN_STATE_RUNNING":          1,
		"RUN_STATE_WAITING_APPROVAL": 2,
		"RUN_STATE_COMPLETED":        3,
		"RUN_STATE_FAILED":           4,
	}
)

func (x RunState) Enum() *RunState {
	p := new(RunState)
	*p = x
	return p
}

func (x RunState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunState) Descriptor() protoreflect.EnumDescriptor {
	return file_garm_agent_v1_agent_proto_enumTypes[1].Descriptor()
}

func (RunState) Type() protoreflect.EnumType {
	return &file_garm_agent_v1_agent_proto_enumTypes[1]
}

func (x RunState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunState.Descriptor instead.
func (RunState) EnumDescriptor() ([]byte, []int) {
	return file_garm_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

type Principal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clearance     v1.Clearance           `protobuf:"varint,1,opt,name=clearance,proto3,enum=garm.tool.v1.Clearance" json:"clearance,omitempty"`
	Compartments  []string               `protobuf:"bytes,2,rep,name=compartments,proto3" json:"compartments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Principal) Reset() {
	*x = Principal{}
	mi := &file_garm_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Principal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Principal) ProtoMessage() {}

func (x *Principal) ProtoReflect() protoreflect.Message {
	mi := &file_garm_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Principal.ProtoReflect.Descriptor instead.
func (*Principal) Descriptor() ([]byte, []int) {
	return file_garm_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Principal) GetClearance() v1.Clearance {
	if x != nil {
		return x.Clearance
	}
	return v1.Clearance(0)
}

func (x *Principal) GetCompartments() []string {
	if x != nil {
		return x.Compartments
	}
	return nil
}

type Model struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_garm_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_garm_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_garm_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Model) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type Bounds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxSteps      uint32                 `protobuf:"varint,1,opt,name=max_steps,json=maxSteps,proto3" json:"max_steps,omitempty"`
	MaxTokens     uint64                 `protobuf:"varint,2,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	MaxToolCalls  uint32                 `protobuf:"varint,3,opt,name=max_tool_calls,json=maxToolCalls,proto3" json:"max_tool_calls,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"` // active time, spec §4.1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bounds) Reset() {
	*x = Bounds{}
	mi := &file_garm_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bounds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bounds) ProtoMessage() {}

func (x *Bounds) ProtoReflect() protoreflect.Message {
	mi := &file_garm_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bounds.ProtoReflect.Descriptor instead.
func (*Bounds) Descriptor() ([]byte, []int) {
	return file_garm_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Bounds) GetMaxSteps() uint32 {
	if x != nil {
		return x.MaxSteps
	}
	return 0
}

func (x *Bounds) GetMaxTokens() uint64 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *Bounds) GetMaxToolCalls() uint32 {
	if x != nil {
		return x.MaxToolCalls
	}
	return 0
}

func (x *Bounds) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Prompt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Sha256        string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Prompt) Reset() {
	*x = Prompt{}
	mi := &file_garm_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prompt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prompt) ProtoMessage() {}

func (x *Prompt) ProtoReflect() protoreflect.Message {
	mi := &file_garm_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prompt.ProtoReflect.Descriptor instead.
func (*Prompt) Descriptor() ([]byte, []int) {
	return file_garm_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *Prompt) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Prompt) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type ToolRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fqn           string                 `protobuf:"bytes,1,opt,name=fqn,proto3" json:"fqn,omitempty"`
	Guard         string                 `protobuf:"bytes,2,opt,name=guard,proto3" json:"guard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolRef) Reset() {
	*x = ToolRef{}
	mi := &file_garm_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolRef) ProtoMessage() {}

func (x *ToolRef) ProtoReflect() protoreflect.Message {
	mi := &file_garm_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolRef.ProtoReflect.Descriptor instead.
func (*ToolRef) Descriptor() ([]byte, []int) {
	return file_garm_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ToolRef) GetFqn() string {
	if x != nil {
		return x.Fqn
	}
	return ""
}

func (x *ToolRef) GetGuard() string {
	if x != nil {
		return x.Guard
	}
	return ""
}

type OutputRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expr          string                 `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputRule) Reset() {
	*x = OutputRule{}
	mi := &file_garm_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputRule) ProtoMessage() {}

func (x *OutputRule) ProtoReflect() protoreflect.Message {
	mi := &file_garm_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputRule.ProtoReflect.Descriptor instead.
func (*OutputRule) Descriptor() ([]byte, []int) {
	return file_garm_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *OutputRule) GetExpr() string {
	if x != nil {
		return x.Expr
	}
	return ""
}

func (x *OutputRule) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AgentPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          Mode                   `protobuf:"varint,1,opt,name=mode,proto3,enum=garm.agent.v1.Mode" json:"mode,omitempty"`
	Principal     *Principal             `protobuf:"bytes,2,opt,name=principal,proto3" json:"principal,omitempty"`
	Model         *Model                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Bounds        *Bounds                `protobuf:"bytes,4,opt,name=bounds,proto3" json:"bounds,omitempty"`
	Prompts       map[string]*Prompt     `protobuf:"bytes,5,rep,name=prompts,proto3" json:"prompts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key "system" is required
	Tools         []*ToolRef             `protobuf:"bytes,6,rep,name=tools,proto3" json:"tools,omitempty"`
	OutputRules   []*OutputRule          `protobuf:"bytes,7,rep,name=output_rules,json=outputRules,proto3" json:"output_rules,omitempty"` // parsed by lint, not evaluated in the MVP
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentPolicy) Reset() {
	*x = AgentPolicy{}
	mi := &file_garm_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentPolicy) ProtoMessage() {}

func (x *AgentPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_garm_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentPolicy.ProtoReflect.Descriptor instead.
func (*AgentPolicy) Descriptor() ([]byte, []int) {
	return file_garm_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *AgentPolicy) GetMode() Mode {
	if x != nil {
		return x.Mode
	}
	return Mode_MODE_UNSPECIFIED
}

func (x *AgentPolicy) GetPrincipal() *Principal {
	if x != nil {
		return x.Principal
	}
	return nil
}

func (x *AgentPolicy) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *AgentPolicy) GetBounds() *Bounds {
	if x != nil {
		return x.Bounds
	}
	return nil
}

func (x *AgentPolicy) GetPrompts() map[string]*Prompt {
	if x != nil {
		return x.Prompts
	}
	return nil
}

func (x *AgentPolicy) GetTools() []*ToolRef {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *AgentPolicy) GetOutputRules() []*OutputRule {
	if x != nil {
		return x.OutputRules
	}
	return nil
}

// Shared by every agent's Invoke and GetRun (spec §2.1). Fields are PUBLIC because
// a caller who can see Invoke at all (A5) is the only caller who can reach them, and
// GetRun additionally refuses runs the caller did not start (spec §4.5, §3.5 there).
//
// The scalars are `optional` because these messages are a governed tool's
// request and response, so garm's own L6 walks them: omit on a singular scalar
// with no presence makes "redacted" and "empty" indistinguishable on the wire,
// and the rule refuses it. Presence costs nothing here and the field numbers,
// wire shape and generated getters are the same either way.
type RunRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         *string                `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3,oneof" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRef) Reset() {
	*x = RunRef{}
	mi := &file_garm_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRef) ProtoMessage() {}

func (x *RunRef) ProtoReflect() protoreflect.Message {
	mi := &file_garm_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRef.ProtoReflect.Descriptor instead.
func (*RunRef) Descriptor() ([]byte, []int) {
	return file_garm_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *RunRef) GetRunId() string {
	if x != nil && x.RunId != nil {
		return *x.RunId
	}
	return ""
}

type RunStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         *string                `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3,oneof" json:"run_id,omitempty"`
	State         *RunState              `protobuf:"varint,2,opt,name=state,proto3,enum=garm.agent.v1.RunState,oneof" json:"state,omitempty"`
	Result        *anypb.Any             `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`     // the agent's declared output message
	Error         *string                `protobuf:"bytes,4,opt,name=error,proto3,oneof" json:"error,omitempty"` // scrubbed, static text; never provider or tool error text
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunStatus) Reset() {
	*x = RunStatus{}
	mi := &file_garm_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunStatus) ProtoMessage() {}

func (x *RunStatus) ProtoReflect() protoreflect.Message {
	mi := &file_garm_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunStatus.ProtoReflect.Descriptor instead.
func (*RunStatus) Descriptor() ([]byte, []int) {
	return file_garm_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *RunStatus) GetRunId() string {
	if x != nil && x.RunId != nil {
		return *x.RunId
	}
	return ""
}

func (x *RunStatus) GetState() RunState {
	if x != nil && x.State != nil {
		return *x.State
	}
	return RunState_RUN_STATE_UNSPECIFIED
}

func (x *RunStatus) GetResult() *anypb.Any {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RunStatus) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *RunStatus) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *RunStatus) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

var file_garm_agent_v1_agent_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*AgentPolicy)(nil),
		Field:         50101,
		Name:          "garm.agent.v1.agent",
		Tag:           "bytes,50101,opt,name=agent",
		Filename:      "garm/agent/v1/agent.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional garm.agent.v1.AgentPolicy agent = 50101;
	E_Agent = &file_garm_agent_v1_agent_proto_extTypes[0]
)

var File_garm_agent_v1_agent_proto protoreflect.FileDescriptor

const file_garm_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x19garm/agent/v1/agent.proto\x12\rgarm.agent.v1\x1a\x19google/protobuf/any.proto\x1a google/protobuf/descriptor.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17garm/tool/v1/tool.proto\"f\n" +
	"\tPrincipal\x125\n" +
	"\tclearance\x18\x01 \x01(\x0e2\x17.garm.tool.v1.ClearanceR\tclearance\x12\"\n" +
	"\fcompartments\x18\x02 \x03(\tR\fcompartments\"\x1d\n" +
	"\x05Model\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\"\x9f\x01\n" +
	"\x06Bounds\x12\x1b\n" +
	"\tmax_steps\x18\x01 \x01(\rR\bmaxSteps\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x02 \x01(\x04R\tmaxTokens\x12$\n" +
	"\x0emax_tool_calls\x18\x03 \x01(\rR\fmaxToolCalls\x123\n" +
	"\atimeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"4\n" +
	"\x06Prompt\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\"1\n" +
	"\aToolRef\x12\x10\n" +
	"\x03fqn\x18\x01 \x01(\tR\x03fqn\x12\x14\n" +
	"\x05guard\x18\x02 \x01(\tR\x05guard\":\n" +
	"\n" +
	"OutputRule\x12\x12\n" +
	"\x04expr\x18\x01 \x01(\tR\x04expr\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xcb\x03\n" +
	"\vAgentPolicy\x12'\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x13.garm.agent.v1.ModeR\x04mode\x126\n" +
	"\tprincipal\x18\x02 \x01(\v2\x18.garm.agent.v1.PrincipalR\tprincipal\x12*\n" +
	"\x05model\x18\x03 \x01(\v2\x14.garm.agent.v1.ModelR\x05model\x12-\n" +
	"\x06bounds\x18\x04 \x01(\v2\x15.garm.agent.v1.BoundsR\x06bounds\x12A\n" +
	"\aprompts\x18\x05 \x03(\v2'.garm.agent.v1.AgentPolicy.PromptsEntryR\aprompts\x12,\n" +
	"\x05tools\x18\x06 \x03(\v2\x16.garm.agent.v1.ToolRefR\x05tools\x12<\n" +
	"\foutput_rules\x18\a \x03(\v2\x19.garm.agent.v1.OutputRuleR\voutputRules\x1aQ\n" +
	"\fPromptsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.garm.agent.v1.PromptR\x05value:\x028\x01\";\n" +
	"\x06RunRef\x12\x1a\n" +
	"\x06run_id\x18\x01 \x01(\tH\x00R\x05runId\x88\x01\x01:\n" +
	"\x9a\xb5\x18\x06\b\n" +
	"\"\x02\n" +
	"\x00B\t\n" +
	"\a_run_id\"\xc7\x02\n" +
	"\tRunStatus\x12\x1a\n" +
	"\x06run_id\x18\x01 \x01(\tH\x00R\x05runId\x88\x01\x01\x122\n" +
	"\x05state\x18\x02 \x01(\x0e2\x17.garm.agent.v1.RunStateH\x01R\x05state\x88\x01\x01\x12,\n" +
	"\x06result\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x06result\x12\x19\n" +
	"\x05error\x18\x04 \x01(\tH\x02R\x05error\x88\x01\x01\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt:\n" +
	"\x9a\xb5\x18\x06\b\n" +
	"\"\x02\n" +
	"\x00B\t\n" +
	"\a_run_idB\b\n" +
	"\x06_stateB\b\n" +
	"\x06_error*,\n" +
	"\x04Mode\x12\x14\n" +
	"\x10MODE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"MODE_REACT\x10\x01*\x8b\x01\n" +
	"\bRunState\x12\x19\n" +
	"\x15RUN_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11RUN_STATE_RUNNING\x10\x01\x12\x1e\n" +
	"\x1aRUN_STATE_WAITING_APPROVAL\x10\x02\x12\x17\n" +
	"\x13RUN_STATE_COMPLETED\x10\x03\x12\x14\n" +
	"\x10RUN_STATE_FAILED\x10\x04:S\n" +
	"\x05agent\x12\x1f.google.protobuf.ServiceOptions\x18\xb5\x87\x03 \x01(\v2\x1a.garm.agent.v1.AgentPolicyR\x05agentB9Z7github.com/garm-ai/garm/contracts/garm/agent/v1;agentv1b\x06proto3"

var (
	file_garm_agent_v1_agent_proto_rawDescOnce sync.Once
	file_garm_agent_v1_agent_proto_rawDescData []byte
)

func file_garm_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_garm_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_garm_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_garm_agent_v1_agent_proto_rawDesc), len(file_garm_agent_v1_agent_proto_rawDesc)))
	})
	return file_garm_agent_v1_agent_proto_rawDescData
}

var file_garm_agent_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_garm_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_garm_agent_v1_agent_proto_goTypes = []any{
	(Mode)(0),                           // 0: garm.agent.v1.Mode
	(RunState)(0),                       // 1: garm.agent.v1.RunState
	(*Principal)(nil),                   // 2: garm.agent.v1.Principal
	(*Model)(nil),                       // 3: garm.agent.v1.Model
	(*Bounds)(nil),                      // 4: garm.agent.v1.Bounds
	(*Prompt)(nil),                      // 5: garm.agent.v1.Prompt
	(*ToolRef)(nil),                     // 6: garm.agent.v1.ToolRef
	(*OutputRule)(nil),                  // 7: garm.agent.v1.OutputRule
	(*AgentPolicy)(nil),                 // 8: garm.agent.v1.AgentPolicy
	(*RunRef)(nil),                      // 9: garm.agent.v1.RunRef
	(*RunStatus)(nil),                   // 10: garm.agent.v1.RunStatus
	nil,                                 // 11: garm.agent.v1.AgentPolicy.PromptsEntry
	(v1.Clearance)(0),                   // 12: garm.tool.v1.Clearance
	(*durationpb.Duration)(nil),         // 13: google.protobuf.Duration
	(*anypb.Any)(nil),                   // 14: google.protobuf.Any
	(*timestamppb.Timestamp)(nil),       // 15: google.protobuf.Timestamp
	(*descriptorpb.ServiceOptions)(nil), // 16: google.protobuf.ServiceOptions
}
var file_garm_agent_v1_agent_proto_depIdxs = []int32{
	12, // 0: garm.agent.v1.Principal.clearance:type_name -> garm.tool.v1.Clearance
	13, // 1: garm.agent.v1.Bounds.timeout:type_name -> google.protobuf.Duration
	0,  // 2: garm.agent.v1.AgentPolicy.mode:type_name -> garm.agent.v1.Mode
	2,  // 3: garm.agent.v1.AgentPolicy.principal:type_name -> garm.agent.v1.Principal
	3,  // 4: garm.agent.v1.AgentPolicy.model:type_name -> garm.agent.v1.Model
	4,  // 5: garm.agent.v1.AgentPolicy.bounds:type_name -> garm.agent.v1.Bounds
	11, // 6: garm.agent.v1.AgentPolicy.prompts:type_name -> garm.agent.v1.AgentPolicy.PromptsEntry
	6,  // 7: garm.agent.v1.AgentPolicy.tools:type_name -> garm.agent.v1.ToolRef
	7,  // 8: garm.agent.v1.AgentPolicy.output_rules:type_name -> garm.agent.v1.OutputRule
	1,  // 9: garm.agent.v1.RunStatus.state:type_name -> garm.agent.v1.RunState
	14, // 10: garm.agent.v1.RunStatus.result:type_name -> google.protobuf.Any
	15, // 11: garm.agent.v1.RunStatus.started_at:type_name -> google.protobuf.Timestamp
	15, // 12: garm.agent.v1.RunStatus.finished_at:type_name -> google.protobuf.Timestamp
	5,  // 13: garm.agent.v1.AgentPolicy.PromptsEntry.value:type_name -> garm.agent.v1.Prompt
	16, // 14: garm.agent.v1.agent:extendee -> google.protobuf.ServiceOptions
	8,  // 15: garm.agent.v1.agent:type_name -> garm.agent.v1.AgentPolicy
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	15, // [15:16] is the sub-list for extension type_name
	14, // [14:15] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_garm_agent_v1_agent_proto_init() }
func file_garm_agent_v1_agent_proto_init() {
	if File_garm_agent_v1_agent_proto != nil {
		return
	}
	file_garm_agent_v1_agent_proto_msgTypes[7].OneofWrappers = []any{}
	file_garm_agent_v1_agent_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_garm_agent_v1_agent_proto_rawDesc), len(file_garm_agent_v1_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_garm_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_garm_agent_v1_agent_proto_depIdxs,
		EnumInfos:         file_garm_agent_v1_agent_proto_enumTypes,
		MessageInfos:      file_garm_agent_v1_agent_proto_msgTypes,
		ExtensionInfos:    file_garm_agent_v1_agent_proto_extTypes,
	}.Build()
	File_garm_agent_v1_agent_proto = out.File
	file_garm_agent_v1_agent_proto_goTypes = nil
	file_garm_agent_v1_agent_proto_depIdxs = nil
}
