// Ownership: who is answerable for a tool service or an agent, shown on every
// card built from it.
//
// Metadata, not policy, so it lives beside the card annotations rather than
// inside garm.tool.v1. garmd stays blind to it: garm.meta.v1 is a namespace
// the catalogue's version check ignores, like garm.agent.v1 and garm.card.v1.
// agentd reads it from the catalogue generation a task or run pinned; ListTools
// does not carry it. The extension numbers are outside every block the other
// garm vocabularies own.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: garm/meta/v1/meta.proto

package metav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Owner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Team          string                 `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`                   // stable identifier, lower-case kebab: "payments-platform"; the unit a ledger row is charged to
	Contact       string                 `protobuf:"bytes,2,opt,name=contact,proto3" json:"contact,omitempty"`             // where a person reaches the team: a mailbox or a channel name, free text
	OnCall        string                 `protobuf:"bytes,3,opt,name=on_call,json=onCall,proto3" json:"on_call,omitempty"` // optional: the rota or escalation name for a stuck approval
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Owner) Reset() {
	*x = Owner{}
	mi := &file_garm_meta_v1_meta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Owner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Owner) ProtoMessage() {}

func (x *Owner) ProtoReflect() protoreflect.Message {
	mi := &file_garm_meta_v1_meta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Owner.ProtoReflect.Descriptor instead.
func (*Owner) Descriptor() ([]byte, []int) {
	return file_garm_meta_v1_meta_proto_rawDescGZIP(), []int{0}
}

func (x *Owner) GetTeam() string {
	if x != nil {
		return x.Team
	}
	return ""
}

func (x *Owner) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

func (x *Owner) GetOnCall() string {
	if x != nil {
		return x.OnCall
	}
	return ""
}

var file_garm_meta_v1_meta_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*Owner)(nil),
		Field:         50301,
		Name:          "garm.meta.v1.owner",
		Tag:           "bytes,50301,opt,name=owner",
		Filename:      "garm/meta/v1/meta.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Owner)(nil),
		Field:         50302,
		Name:          "garm.meta.v1.method_owner",
		Tag:           "bytes,50302,opt,name=method_owner",
		Filename:      "garm/meta/v1/meta.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional garm.meta.v1.Owner owner = 50301;
	E_Owner = &file_garm_meta_v1_meta_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional garm.meta.v1.Owner method_owner = 50302;
	E_MethodOwner = &file_garm_meta_v1_meta_proto_extTypes[1]
)

var File_garm_meta_v1_meta_proto protoreflect.FileDescriptor

const file_garm_meta_v1_meta_proto_rawDesc = "" +
	"\n" +
	"\x17garm/meta/v1/meta.proto\x12\fgarm.meta.v1\x1a google/protobuf/descriptor.proto\"N\n" +
	"\x05Owner\x12\x12\n" +
	"\x04team\x18\x01 \x01(\tR\x04team\x12\x18\n" +
	"\acontact\x18\x02 \x01(\tR\acontact\x12\x17\n" +
	"\aon_call\x18\x03 \x01(\tR\x06onCall:L\n" +
	"\x05owner\x12\x1f.google.protobuf.ServiceOptions\x18\xfd\x88\x03 \x01(\v2\x13.garm.meta.v1.OwnerR\x05owner:X\n" +
	"\fmethod_owner\x12\x1e.google.protobuf.MethodOptions\x18\xfe\x88\x03 \x01(\v2\x13.garm.meta.v1.OwnerR\vmethodOwnerB7Z5github.com/garm-ai/garm/contracts/garm/meta/v1;metav1b\x06proto3"

var (
	file_garm_meta_v1_meta_proto_rawDescOnce sync.Once
	file_garm_meta_v1_meta_proto_rawDescData []byte
)

func file_garm_meta_v1_meta_proto_rawDescGZIP() []byte {
	file_garm_meta_v1_meta_proto_rawDescOnce.Do(func() {
		file_garm_meta_v1_meta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_garm_meta_v1_meta_proto_rawDesc), len(file_garm_meta_v1_meta_proto_rawDesc)))
	})
	return file_garm_meta_v1_meta_proto_rawDescData
}

var file_garm_meta_v1_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_garm_meta_v1_meta_proto_goTypes = []any{
	(*Owner)(nil),                       // 0: garm.meta.v1.Owner
	(*descriptorpb.ServiceOptions)(nil), // 1: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 2: google.protobuf.MethodOptions
}
var file_garm_meta_v1_meta_proto_depIdxs = []int32{
	1, // 0: garm.meta.v1.owner:extendee -> google.protobuf.ServiceOptions
	2, // 1: garm.meta.v1.method_owner:extendee -> google.protobuf.MethodOptions
	0, // 2: garm.meta.v1.owner:type_name -> garm.meta.v1.Owner
	0, // 3: garm.meta.v1.method_owner:type_name -> garm.meta.v1.Owner
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	2, // [2:4] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_garm_meta_v1_meta_proto_init() }
func file_garm_meta_v1_meta_proto_init() {
	if File_garm_meta_v1_meta_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_garm_meta_v1_meta_proto_rawDesc), len(file_garm_meta_v1_meta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_garm_meta_v1_meta_proto_goTypes,
		DependencyIndexes: file_garm_meta_v1_meta_proto_depIdxs,
		MessageInfos:      file_garm_meta_v1_meta_proto_msgTypes,
		ExtensionInfos:    file_garm_meta_v1_meta_proto_extTypes,
	}.Build()
	File_garm_meta_v1_meta_proto = out.File
	file_garm_meta_v1_meta_proto_goTypes = nil
	file_garm_meta_v1_meta_proto_depIdxs = nil
}
