// The card vocabulary: what an inbox renders for one viewer at one moment,
// and the template an author may declare beside a tool or an agent.
//
// A new package rather than a field on garm.tool.v1, because garmd must stay
// card-blind: it projects a tool's typed request and response field by field
// and never reads a template. The extension numbers are outside the
// 50001-50005 block garm.tool.v1 owns and the 50101 garm.agent.v1 owns, so
// the vocabularies can never collide.
//
// Enum values are deliberately unprefixed (TASK, OPEN, SUBTLE) rather than
// buf's KIND_TASK convention: a card crosses the wire as protojson with enums
// as strings, and the JSON shape — "kind": "TASK" — is the contract with the
// renderer. buf.yaml excuses this file from those two rules for that reason.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: garm/card/v1/card.proto

package cardv1

import (
	v1 "github.com/garm-ai/garm/contracts/garm/tool/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Kind int32

const (
	Kind_KIND_UNSPECIFIED Kind = 0
	Kind_START            Kind = 1
	Kind_TASK             Kind = 2
	Kind_RUN              Kind = 3
	Kind_ASK              Kind = 4
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "START",
		2: "TASK",
		3: "RUN",
		4: "ASK",
	}
	Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"START":            1,
		"TASK":             2,
		"RUN":              3,
		"ASK":              4,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_garm_card_v1_card_proto_enumTypes[0].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_garm_card_v1_card_proto_enumTypes[0]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) {
	return file_garm_card_v1_card_proto_rawDescGZIP(), []int{0}
}

type State int32

const (
	State_STATE_UNSPECIFIED State = 0
	State_OPEN              State = 1
	State_ANSWERED          State = 2
	State_EXPIRED           State = 3
	State_RUNNING           State = 4
	State_COMPLETED         State = 5
	State_FAILED            State = 6
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "OPEN",
		2: "ANSWERED",
		3: "EXPIRED",
		4: "RUNNING",
		5: "COMPLETED",
		6: "FAILED",
	}
	State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"OPEN":              1,
		"ANSWERED":          2,
		"EXPIRED":           3,
		"RUNNING":           4,
		"COMPLETED":         5,
		"FAILED":            6,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_garm_card_v1_card_proto_enumTypes[1].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_garm_card_v1_card_proto_enumTypes[1]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_garm_card_v1_card_proto_rawDescGZIP(), []int{1}
}

type Emphasis int32

const (
	Emphasis_DEFAULT Emphasis = 0
	Emphasis_HEADING Emphasis = 1
	Emphasis_SUBTLE  Emphasis = 2
)

// Enum value maps for Emphasis.
var (
	Emphasis_name = map[int32]string{
		0: "DEFAULT",
		1: "HEADING",
		2: "SUBTLE",
	}
	Emphasis_value = map[string]int32{
		"DEFAULT": 0,
		"HEADING": 1,
		"SUBTLE":  2,
	}
)

func (x Emphasis) Enum() *Emphasis {
	p := new(Emphasis)
	*p = x
	return p
}

func (x Emphasis) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Emphasis) Descriptor() protoreflect.EnumDescriptor {
	return file_garm_card_v1_card_proto_enumTypes[2].Descriptor()
}

func (Emphasis) Type() protoreflect.EnumType {
	return &file_garm_card_v1_card_proto_enumTypes[2]
}

func (x Emphasis) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Emphasis.Descriptor instead.
func (Emphasis) EnumDescriptor() ([]byte, []int) {
	return file_garm_card_v1_card_proto_rawDescGZIP(), []int{2}
}

type Style int32

const (
	Style_STYLE_DEFAULT Style = 0
	Style_POSITIVE      Style = 1
	Style_DESTRUCTIVE   Style = 2
)

// Enum value maps for Style.
var (
	Style_name = map[int32]string{
		0: "STYLE_DEFAULT",
		1: "POSITIVE",
		2: "DESTRUCTIVE",
	}
	Style_value = map[string]int32{
		"STYLE_DEFAULT": 0,
		"POSITIVE":      1,
		"DESTRUCTIVE":   2,
	}
)

func (x Style) Enum() *Style {
	p := new(Style)
	*p = x
	return p
}

func (x Style) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Style) Descriptor() protoreflect.EnumDescriptor {
	return file_garm_card_v1_card_proto_enumTypes[3].Descriptor()
}

func (Style) Type() protoreflect.EnumType {
	return &file_garm_card_v1_card_proto_enumTypes[3]
}

func (x Style) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Style.Descriptor instead.
func (Style) EnumDescriptor() ([]byte, []int) {
	return file_garm_card_v1_card_proto_rawDescGZIP(), []int{3}
}

type CardRole int32

const (
	CardRole_CARD_ROLE_UNSPECIFIED CardRole = 0
	CardRole_CARD_ROLE_TITLE       CardRole = 1
	CardRole_CARD_ROLE_VALUE       CardRole = 2
)

// Enum value maps for CardRole.
var (
	CardRole_name = map[int32]string{
		0: "CARD_ROLE_UNSPECIFIED",
		1: "CARD_ROLE_TITLE",
		2: "CARD_ROLE_VALUE",
	}
	CardRole_value = map[string]int32{
		"CARD_ROLE_UNSPECIFIED": 0,
		"CARD_ROLE_TITLE":       1,
		"CARD_ROLE_VALUE":       2,
	}
)

func (x CardRole) Enum() *CardRole {
	p := new(CardRole)
	*p = x
	return p
}

func (x CardRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CardRole) Descriptor() protoreflect.EnumDescriptor {
	return file_garm_card_v1_card_proto_enumTypes[4].Descriptor()
}

func (CardRole) Type() protoreflect.EnumType {
	return &file_garm_card_v1_card_proto_enumTypes[4]
}

func (x CardRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CardRole.Descriptor instead.
func (CardRole) EnumDescriptor() ([]byte, []int) {
	return file_garm_card_v1_card_proto_rawDescGZIP(), []int{4}
}

// Who may see one element of a card.
//
// Read by garmd, which knows this one type and drops what a viewer does not
// reach at step 8 (design 3). Set by the TOOL that serves the card: by the
// generated default from the source field's policy, or by an override.
//
// An absent label is NOT public. It means "the card endpoint's own policy",
// which is the parent tool's clearance and compartments -- so forgetting to
// label an element is as tight as the endpoint, never looser. An element
// labelled BELOW the endpoint's policy fails the whole card
// (500 card_invalid, design 3.2 floor 1).
type Label struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clearance     v1.Clearance           `protobuf:"varint,1,opt,name=clearance,proto3,enum=garm.tool.v1.Clearance" json:"clearance,omitempty"`
	Compartments  []string               `protobuf:"bytes,2,rep,name=compartments,proto3" json:"compartments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_garm_card_v1_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_garm_card_v1_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_garm_card_v1_card_proto_rawDescGZIP(), []int{0}
}

func (x *Label) GetClearance() v1.Clearance {
	if x != nil {
		return x.Clearance
	}
	return v1.Clearance(0)
}

func (x *Label) GetCompartments() []string {
	if x != nil {
		return x.Compartments
	}
	return nil
}

// CallRef names a garmd call: the id every tool sees (callctx.FromContext),
// every ledger row carries, and the answer returns as Garm-Event-Id. It is
// the argument of a tool's ResultCard.
//
// For an agent the call is the Invoke, and the runner records the call id on
// the run row, so one id addresses a run and its card alike. RunRef stays for
// GetRun.
type CallRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        *string                `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3,oneof" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallRef) Reset() {
	*x = CallRef{}
	mi := &file_garm_card_v1_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRef) ProtoMessage() {}

func (x *CallRef) ProtoReflect() protoreflect.Message {
	mi := &file_garm_card_v1_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRef.ProtoReflect.Descriptor instead.
func (*CallRef) Descriptor() ([]byte, []int) {
	return file_garm_card_v1_card_proto_rawDescGZIP(), []int{1}
}

func (x *CallRef) GetCallId() string {
	if x != nil && x.CallId != nil {
		return *x.CallId
	}
	return ""
}

// TaskRef names one open task, and carries the material the viewer's client
// rebuilt from the task card.
//
// The material travels because of an ordering fact: garmd refuses a
// grant-mode call at step 5, before step 6 resolves the tool, so the tool
// NEVER SAW the request that was parked. Its approval card cannot show what
// it never received unless the fetch brings it (design 1.3).
//
// A lying map buys a wrong context beside the right material, never a wrong
// grant: the digest is computed from what the tasks tool stored, and garmd
// compares it with the request actually sent.
type TaskRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        *string                `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3,oneof" json:"task_id,omitempty"`
	Material      map[string]string      `protobuf:"bytes,2,rep,name=material,proto3" json:"material,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // dotted path -> canonical text
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRef) Reset() {
	*x = TaskRef{}
	mi := &file_garm_card_v1_card_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRef) ProtoMessage() {}

func (x *TaskRef) ProtoReflect() protoreflect.Message {
	mi := &file_garm_card_v1_card_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRef.ProtoReflect.Descriptor instead.
func (*TaskRef) Descriptor() ([]byte, []int) {
	return file_garm_card_v1_card_proto_rawDescGZIP(), []int{2}
}

func (x *TaskRef) GetTaskId() string {
	if x != nil && x.TaskId != nil {
		return *x.TaskId
	}
	return ""
}

func (x *TaskRef) GetMaterial() map[string]string {
	if x != nil {
		return x.Material
	}
	return nil
}

// A Card is an OPAQUE VALUE to the field-policy walk, and a structure only to
// the daemon's card walk.
//
// That is the one thing to know before reading the rest of this message. A
// field policy is per descriptor: it says what EVERY caller of this RPC may
// see of this field, decided at compile time. A card's rows do not work that
// way — a queue holds one task per approver, and the same `Fact` is readable
// by one viewer and not the next — so the policy travels on the VALUE, as the
// `access` label on each element. The daemon knows this one type and projects
// it by those labels after the field plan has run.
//
// So `garm.card.v1.Card` is an opaque leaf to policy.Compile and to lint, the
// way `google.protobuf.Timestamp` is: the field that HOLDS a card carries the
// policy for the whole value, and no scalar inside one is classified
// separately. A per-field policy in here would be a second mechanism
// answering the same question differently, which is how a leak gets written.
//
// A Card is a projection of one object — a task, a run, or an agent's
// input — rendered for ONE viewer at ONE moment. It is built by agentd or
// a tool handler, validated at render time (§7), and crosses the policy
// chain like any other response on the governed door.
type Card struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Kind            Kind                   `protobuf:"varint,1,opt,name=kind,proto3,enum=garm.card.v1.Kind" json:"kind,omitempty"`    // START | TASK | RUN
	SubjectId       string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"` // agent name, task id, or run id
	Title           string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	State           State                  `protobuf:"varint,4,opt,name=state,proto3,enum=garm.card.v1.State" json:"state,omitempty"` // see 1.2
	Body            []*Element             `protobuf:"bytes,5,rep,name=body,proto3" json:"body,omitempty"`
	Actions         []*Action              `protobuf:"bytes,6,rep,name=actions,proto3" json:"actions,omitempty"`       // empty unless state == OPEN
	Disclosure      *Disclosure            `protobuf:"bytes,7,opt,name=disclosure,proto3" json:"disclosure,omitempty"` // what was withheld from THIS viewer
	Refs            []*CardRef             `protobuf:"bytes,8,rep,name=refs,proto3" json:"refs,omitempty"`             // pointers to other cards, never copies
	CatalogueDigest string                 `protobuf:"bytes,9,opt,name=catalogue_digest,json=catalogueDigest,proto3" json:"catalogue_digest,omitempty"`
	// The whole card. A viewer who does not reach it gets nothing: dropped
	// from a repeated field, NotFound as a unary answer (design 3.2 rule 1) --
	// the same closed answer step 2 gives for a tool they may not see.
	Access        *Label `protobuf:"bytes,10,opt,name=access,proto3" json:"access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_garm_card_v1_card_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_garm_card_v1_card_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_garm_card_v1_card_proto_rawDescGZIP(), []int{3}
}

func (x *Card) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_KIND_UNSPECIFIED
}

func (x *Card) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *Card) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Card) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_UNSPECIFIED
}

func (x *Card) GetBody() []*Element {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Card) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *Card) GetDisclosure() *Disclosure {
	if x != nil {
		return x.Disclosure
	}
	return nil
}

func (x *Card) GetRefs() []*CardRef {
	if x != nil {
		return x.Refs
	}
	return nil
}

func (x *Card) GetCatalogueDigest() string {
	if x != nil {
		return x.CatalogueDigest
	}
	return ""
}

func (x *Card) GetAccess() *Label {
	if x != nil {
		return x.Access
	}
	return nil
}

// A pointer to another card: a task card at its run, a run card at its tasks.
//
// `tool_fqn` is what makes a ref SELF-ADDRESSING, and it is the field that
// was missing. A kind and an id say which card; they do not say whose
// ResultCard or ApprovalCard to call for it, and a client that started a run
// itself knows the answer while a client that reached the same run from a
// task does not. Without it one page could not show itself. With it, any ref
// is enough to fetch the card it names — no second lookup, and no table of
// the client's own that would go stale the moment a tool moved service.
type CardRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          Kind                   `protobuf:"varint,1,opt,name=kind,proto3,enum=garm.card.v1.Kind" json:"kind,omitempty"`
	SubjectId     string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	State         State                  `protobuf:"varint,4,opt,name=state,proto3,enum=garm.card.v1.State" json:"state,omitempty"`
	ToolFqn       string                 `protobuf:"bytes,5,opt,name=tool_fqn,json=toolFqn,proto3" json:"tool_fqn,omitempty"` // the tool whose service serves the card this names
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardRef) Reset() {
	*x = CardRef{}
	mi := &file_garm_card_v1_card_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardRef) ProtoMessage() {}

func (x *CardRef) ProtoReflect() protoreflect.Message {
	mi := &file_garm_card_v1_card_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardRef.ProtoReflect.Descriptor instead.
func (*CardRef) Descriptor() ([]byte, []int) {
	return file_garm_card_v1_card_proto_rawDescGZIP(), []int{4}
}

func (x *CardRef) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_KIND_UNSPECIFIED
}

func (x *CardRef) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *CardRef) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CardRef) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_UNSPECIFIED
}

func (x *CardRef) GetToolFqn() string {
	if x != nil {
		return x.ToolFqn
	}
	return ""
}

type Element struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Of:
	//
	//	*Element_Text
	//	*Element_Facts
	//	*Element_Divider
	//	*Element_Input
	//	*Element_Section
	Of isElement_Of `protobuf_oneof:"of"`
	// Who may see this element. For a Section, the FLOOR of every element
	// inside it: a child may be labelled higher, never lower (lint C8).
	Access        *Label `protobuf:"bytes,10,opt,name=access,proto3" json:"access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Element) Reset() {
	*x = Element{}
	mi := &file_garm_card_v1_card_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Element) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Element) ProtoMessage() {}

func (x *Element) ProtoReflect() protoreflect.Message {
	mi := &file_garm_card_v1_card_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Element.ProtoReflect.Descriptor instead.
func (*Element) Descriptor() ([]byte, []int) {
	return file_garm_card_v1_card_proto_rawDescGZIP(), []int{5}
}

func (x *Element) GetOf() isElement_Of {
	if x != nil {
		return x.Of
	}
	return nil
}

func (x *Element) GetText() *Text {
	if x != nil {
		if x, ok := x.Of.(*Element_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *Element) GetFacts() *FactSet {
	if x != nil {
		if x, ok := x.Of.(*Element_Facts); ok {
			return x.Facts
		}
	}
	return nil
}

func (x *Element) GetDivider() *Divider {
	if x != nil {
		if x, ok := x.Of.(*Element_Divider); ok {
			return x.Divider
		}
	}
	return nil
}

func (x *Element) GetInput() *Input {
	if x != nil {
		if x, ok := x.Of.(*Element_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *Element) GetSection() *Section {
	if x != nil {
		if x, ok := x.Of.(*Element_Section); ok {
			return x.Section
		}
	}
	return nil
}

func (x *Element) GetAccess() *Label {
	if x != nil {
		return x.Access
	}
	return nil
}

type isElement_Of interface {
	isElement_Of()
}

type Element_Text struct {
	Text *Text `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type Element_Facts struct {
	Facts *FactSet `protobuf:"bytes,2,opt,name=facts,proto3,oneof"`
}

type Element_Divider struct {
	Divider *Divider `protobuf:"bytes,3,opt,name=divider,proto3,oneof"`
}

type Element_Input struct {
	Input *Input `protobuf:"bytes,4,opt,name=input,proto3,oneof"`
}

type Element_Section struct {
	Section *Section `protobuf:"bytes,5,opt,name=section,proto3,oneof"` // a titled group of elements; one level, never nested (1.3)
}

func (*Element_Text) isElement_Of() {}

func (*Element_Facts) isElement_Of() {}

func (*Element_Divider) isElement_Of() {}

func (*Element_Input) isElement_Of() {}

func (*Element_Section) isElement_Of() {}

type Text struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Emphasis      Emphasis               `protobuf:"varint,2,opt,name=emphasis,proto3,enum=garm.card.v1.Emphasis" json:"emphasis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Text) Reset() {
	*x = Text{}
	mi := &file_garm_card_v1_card_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Text) ProtoMessage() {}

func (x *Text) ProtoReflect() protoreflect.Message {
	mi := &file_garm_card_v1_card_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Text.ProtoReflect.Descriptor instead.
func (*Text) Descriptor() ([]byte, []int) {
	return file_garm_card_v1_card_proto_rawDescGZIP(), []int{6}
}

func (x *Text) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Text) GetEmphasis() Emphasis {
	if x != nil {
		return x.Emphasis
	}
	return Emphasis_DEFAULT
}

type FactSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Facts         []*Fact                `protobuf:"bytes,1,rep,name=facts,proto3" json:"facts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactSet) Reset() {
	*x = FactSet{}
	mi := &file_garm_card_v1_card_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactSet) ProtoMessage() {}

func (x *FactSet) ProtoReflect() protoreflect.Message {
	mi := &file_garm_card_v1_card_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactSet.ProtoReflect.Descriptor instead.
func (*FactSet) Descriptor() ([]byte, []int) {
	return file_garm_card_v1_card_proto_rawDescGZIP(), []int{7}
}

func (x *FactSet) GetFacts() []*Fact {
	if x != nil {
		return x.Facts
	}
	return nil
}

// A fact is a caption, a value, and -- when the value came from a field of a
// governed message -- the dotted path it came from.
//
// `field` is what lets a client rebuild TaskRef.material from a task card's
// Material section (design 2.3), and what garmd names in Disclosure instead
// of a positional path when an element is withheld.
type Fact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Field         string                 `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"`
	Access        *Label                 `protobuf:"bytes,4,opt,name=access,proto3" json:"access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fact) Reset() {
	*x = Fact{}
	mi := &file_garm_card_v1_card_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fact) ProtoMessage() {}

func (x *Fact) ProtoReflect() protoreflect.Message {
	mi := &file_garm_card_v1_card_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fact.ProtoReflect.Descriptor instead.
func (*Fact) Descriptor() ([]byte, []int) {
	return file_garm_card_v1_card_proto_rawDescGZIP(), []int{8}
}

func (x *Fact) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Fact) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Fact) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Fact) GetAccess() *Label {
	if x != nil {
		return x.Access
	}
	return nil
}

type Divider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Divider) Reset() {
	*x = Divider{}
	mi := &file_garm_card_v1_card_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Divider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Divider) ProtoMessage() {}

func (x *Divider) ProtoReflect() protoreflect.Message {
	mi := &file_garm_card_v1_card_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Divider.ProtoReflect.Descriptor instead.
func (*Divider) Descriptor() ([]byte, []int) {
	return file_garm_card_v1_card_proto_rawDescGZIP(), []int{9}
}

type Section struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Elements      []*Element             `protobuf:"bytes,2,rep,name=elements,proto3" json:"elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Section) Reset() {
	*x = Section{}
	mi := &file_garm_card_v1_card_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Section) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Section) ProtoMessage() {}

func (x *Section) ProtoReflect() protoreflect.Message {
	mi := &file_garm_card_v1_card_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Section.ProtoReflect.Descriptor instead.
func (*Section) Descriptor() ([]byte, []int) {
	return file_garm_card_v1_card_proto_rawDescGZIP(), []int{10}
}

func (x *Section) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Section) GetElements() []*Element {
	if x != nil {
		return x.Elements
	}
	return nil
}

type Input struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // MUST name a field of the decision message (§3.4 C2)
	Label    string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Required bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Input_Text
	//	*Input_Number
	//	*Input_Date
	//	*Input_Toggle
	//	*Input_Choice
	Kind          isInput_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Input) Reset() {
	*x = Input{}
	mi := &file_garm_card_v1_card_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_garm_card_v1_card_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_garm_card_v1_card_proto_rawDescGZIP(), []int{11}
}

func (x *Input) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Input) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Input) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Input) GetKind() isInput_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Input) GetText() *TextInput {
	if x != nil {
		if x, ok := x.Kind.(*Input_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *Input) GetNumber() *NumberInput {
	if x != nil {
		if x, ok := x.Kind.(*Input_Number); ok {
			return x.Number
		}
	}
	return nil
}

func (x *Input) GetDate() *DateInput {
	if x != nil {
		if x, ok := x.Kind.(*Input_Date); ok {
			return x.Date
		}
	}
	return nil
}

func (x *Input) GetToggle() *ToggleInput {
	if x != nil {
		if x, ok := x.Kind.(*Input_Toggle); ok {
			return x.Toggle
		}
	}
	return nil
}

func (x *Input) GetChoice() *ChoiceInput {
	if x != nil {
		if x, ok := x.Kind.(*Input_Choice); ok {
			return x.Choice
		}
	}
	return nil
}

type isInput_Kind interface {
	isInput_Kind()
}

type Input_Text struct {
	Text *TextInput `protobuf:"bytes,4,opt,name=text,proto3,oneof"`
}

type Input_Number struct {
	Number *NumberInput `protobuf:"bytes,5,opt,name=number,proto3,oneof"`
}

type Input_Date struct {
	Date *DateInput `protobuf:"bytes,6,opt,name=date,proto3,oneof"`
}

type Input_Toggle struct {
	Toggle *ToggleInput `protobuf:"bytes,7,opt,name=toggle,proto3,oneof"`
}

type Input_Choice struct {
	Choice *ChoiceInput `protobuf:"bytes,8,opt,name=choice,proto3,oneof"`
}

func (*Input_Text) isInput_Kind() {}

func (*Input_Number) isInput_Kind() {}

func (*Input_Date) isInput_Kind() {}

func (*Input_Toggle) isInput_Kind() {}

func (*Input_Choice) isInput_Kind() {}

type TextInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxLen        uint32                 `protobuf:"varint,1,opt,name=max_len,json=maxLen,proto3" json:"max_len,omitempty"`
	Multiline     bool                   `protobuf:"varint,2,opt,name=multiline,proto3" json:"multiline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextInput) Reset() {
	*x = TextInput{}
	mi := &file_garm_card_v1_card_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextInput) ProtoMessage() {}

func (x *TextInput) ProtoReflect() protoreflect.Message {
	mi := &file_garm_card_v1_card_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextInput.ProtoReflect.Descriptor instead.
func (*TextInput) Descriptor() ([]byte, []int) {
	return file_garm_card_v1_card_proto_rawDescGZIP(), []int{12}
}

func (x *TextInput) GetMaxLen() uint32 {
	if x != nil {
		return x.MaxLen
	}
	return 0
}

func (x *TextInput) GetMultiline() bool {
	if x != nil {
		return x.Multiline
	}
	return false
}

type NumberInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           float64                `protobuf:"fixed64,1,opt,name=min,proto3" json:"min,omitempty"`
	Max           float64                `protobuf:"fixed64,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumberInput) Reset() {
	*x = NumberInput{}
	mi := &file_garm_card_v1_card_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumberInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberInput) ProtoMessage() {}

func (x *NumberInput) ProtoReflect() protoreflect.Message {
	mi := &file_garm_card_v1_card_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberInput.ProtoReflect.Descriptor instead.
func (*NumberInput) Descriptor() ([]byte, []int) {
	return file_garm_card_v1_card_proto_rawDescGZIP(), []int{13}
}

func (x *NumberInput) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *NumberInput) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

type DateInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateInput) Reset() {
	*x = DateInput{}
	mi := &file_garm_card_v1_card_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateInput) ProtoMessage() {}

func (x *DateInput) ProtoReflect() protoreflect.Message {
	mi := &file_garm_card_v1_card_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateInput.ProtoReflect.Descriptor instead.
func (*DateInput) Descriptor() ([]byte, []int) {
	return file_garm_card_v1_card_proto_rawDescGZIP(), []int{14}
}

type ToggleInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleInput) Reset() {
	*x = ToggleInput{}
	mi := &file_garm_card_v1_card_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleInput) ProtoMessage() {}

func (x *ToggleInput) ProtoReflect() protoreflect.Message {
	mi := &file_garm_card_v1_card_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleInput.ProtoReflect.Descriptor instead.
func (*ToggleInput) Descriptor() ([]byte, []int) {
	return file_garm_card_v1_card_proto_rawDescGZIP(), []int{15}
}

type ChoiceInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Choices       []*Choice              `protobuf:"bytes,1,rep,name=choices,proto3" json:"choices,omitempty"` // a closed list, or
	Query         *Query                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`     // a governed lookup (§4)
	Multi         bool                   `protobuf:"varint,3,opt,name=multi,proto3" json:"multi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChoiceInput) Reset() {
	*x = ChoiceInput{}
	mi := &file_garm_card_v1_card_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChoiceInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChoiceInput) ProtoMessage() {}

func (x *ChoiceInput) ProtoReflect() protoreflect.Message {
	mi := &file_garm_card_v1_card_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChoiceInput.ProtoReflect.Descriptor instead.
func (*ChoiceInput) Descriptor() ([]byte, []int) {
	return file_garm_card_v1_card_proto_rawDescGZIP(), []int{16}
}

func (x *ChoiceInput) GetChoices() []*Choice {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *ChoiceInput) GetQuery() *Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ChoiceInput) GetMulti() bool {
	if x != nil {
		return x.Multi
	}
	return false
}

type Choice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Access        *Label                 `protobuf:"bytes,3,opt,name=access,proto3" json:"access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Choice) Reset() {
	*x = Choice{}
	mi := &file_garm_card_v1_card_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Choice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Choice) ProtoMessage() {}

func (x *Choice) ProtoReflect() protoreflect.Message {
	mi := &file_garm_card_v1_card_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Choice.ProtoReflect.Descriptor instead.
func (*Choice) Descriptor() ([]byte, []int) {
	return file_garm_card_v1_card_proto_rawDescGZIP(), []int{17}
}

func (x *Choice) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Choice) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Choice) GetAccess() *Label {
	if x != nil {
		return x.Access
	}
	return nil
}

// Executes as the VIEWER, bound to the task the card is about (§4).
type Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tool          string                 `protobuf:"bytes,1,opt,name=tool,proto3" json:"tool,omitempty"` // fully-qualified tool name, in THIS contract, unary, VERB_READ
	MinChars      uint32                 `protobuf:"varint,2,opt,name=min_chars,json=minChars,proto3" json:"min_chars,omitempty"`
	PageSize      uint32                 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_garm_card_v1_card_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_garm_card_v1_card_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_garm_card_v1_card_proto_rawDescGZIP(), []int{18}
}

func (x *Query) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *Query) GetMinChars() uint32 {
	if x != nil {
		return x.MinChars
	}
	return 0
}

func (x *Query) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type Action struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // "approve" | "decline" for TASK; "start" for START
	Label string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Style Style                  `protobuf:"varint,3,opt,name=style,proto3,enum=garm.card.v1.Style" json:"style,omitempty"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Action_Submit
	Kind          isAction_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_garm_card_v1_card_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_garm_card_v1_card_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_garm_card_v1_card_proto_rawDescGZIP(), []int{19}
}

func (x *Action) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Action) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Action) GetStyle() Style {
	if x != nil {
		return x.Style
	}
	return Style_STYLE_DEFAULT
}

func (x *Action) GetKind() isAction_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Action) GetSubmit() *Submit {
	if x != nil {
		if x, ok := x.Kind.(*Action_Submit); ok {
			return x.Submit
		}
	}
	return nil
}

type isAction_Kind interface {
	isAction_Kind()
}

type Action_Submit struct {
	Submit *Submit `protobuf:"bytes,4,opt,name=submit,proto3,oneof"`
}

func (*Action_Submit) isAction_Kind() {}

type Submit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfirmText   string                 `protobuf:"bytes,1,opt,name=confirm_text,json=confirmText,proto3" json:"confirm_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Submit) Reset() {
	*x = Submit{}
	mi := &file_garm_card_v1_card_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Submit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Submit) ProtoMessage() {}

func (x *Submit) ProtoReflect() protoreflect.Message {
	mi := &file_garm_card_v1_card_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Submit.ProtoReflect.Descriptor instead.
func (*Submit) Descriptor() ([]byte, []int) {
	return file_garm_card_v1_card_proto_rawDescGZIP(), []int{20}
}

func (x *Submit) GetConfirmText() string {
	if x != nil {
		return x.ConfirmText
	}
	return ""
}

// The viewer's copy of tools-server §5.5: which fields were withheld from
// them, by name, never by value.
type Disclosure struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WithheldFields []string               `protobuf:"bytes,1,rep,name=withheld_fields,json=withheldFields,proto3" json:"withheld_fields,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Disclosure) Reset() {
	*x = Disclosure{}
	mi := &file_garm_card_v1_card_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disclosure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disclosure) ProtoMessage() {}

func (x *Disclosure) ProtoReflect() protoreflect.Message {
	mi := &file_garm_card_v1_card_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disclosure.ProtoReflect.Descriptor instead.
func (*Disclosure) Descriptor() ([]byte, []int) {
	return file_garm_card_v1_card_proto_rawDescGZIP(), []int{21}
}

func (x *Disclosure) GetWithheldFields() []string {
	if x != nil {
		return x.WithheldFields
	}
	return nil
}

type Template struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"` // may reference fields: "Payment {reference}"
	Body          []*TemplateElement     `protobuf:"bytes,2,rep,name=body,proto3" json:"body,omitempty"`
	Context       string                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"` // optional: a context RPC in this package (§3.3); fields as context.<name>
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Template) Reset() {
	*x = Template{}
	mi := &file_garm_card_v1_card_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Template) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Template) ProtoMessage() {}

func (x *Template) ProtoReflect() protoreflect.Message {
	mi := &file_garm_card_v1_card_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Template.ProtoReflect.Descriptor instead.
func (*Template) Descriptor() ([]byte, []int) {
	return file_garm_card_v1_card_proto_rawDescGZIP(), []int{22}
}

func (x *Template) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Template) GetBody() []*TemplateElement {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Template) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

type TemplateElement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Of:
	//
	//	*TemplateElement_Text
	//	*TemplateElement_Facts
	//	*TemplateElement_Divider
	//	*TemplateElement_Section
	Of            isTemplateElement_Of `protobuf_oneof:"of"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateElement) Reset() {
	*x = TemplateElement{}
	mi := &file_garm_card_v1_card_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateElement) ProtoMessage() {}

func (x *TemplateElement) ProtoReflect() protoreflect.Message {
	mi := &file_garm_card_v1_card_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateElement.ProtoReflect.Descriptor instead.
func (*TemplateElement) Descriptor() ([]byte, []int) {
	return file_garm_card_v1_card_proto_rawDescGZIP(), []int{23}
}

func (x *TemplateElement) GetOf() isTemplateElement_Of {
	if x != nil {
		return x.Of
	}
	return nil
}

func (x *TemplateElement) GetText() string {
	if x != nil {
		if x, ok := x.Of.(*TemplateElement_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *TemplateElement) GetFacts() *Facts {
	if x != nil {
		if x, ok := x.Of.(*TemplateElement_Facts); ok {
			return x.Facts
		}
	}
	return nil
}

func (x *TemplateElement) GetDivider() *Divider {
	if x != nil {
		if x, ok := x.Of.(*TemplateElement_Divider); ok {
			return x.Divider
		}
	}
	return nil
}

func (x *TemplateElement) GetSection() *TemplateSection {
	if x != nil {
		if x, ok := x.Of.(*TemplateElement_Section); ok {
			return x.Section
		}
	}
	return nil
}

type isTemplateElement_Of interface {
	isTemplateElement_Of()
}

type TemplateElement_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"` // literal, with {field} references
}

type TemplateElement_Facts struct {
	Facts *Facts `protobuf:"bytes,2,opt,name=facts,proto3,oneof"` // fields by name, in this order, with labels
}

type TemplateElement_Divider struct {
	Divider *Divider `protobuf:"bytes,3,opt,name=divider,proto3,oneof"`
}

type TemplateElement_Section struct {
	Section *TemplateSection `protobuf:"bytes,4,opt,name=section,proto3,oneof"`
}

func (*TemplateElement_Text) isTemplateElement_Of() {}

func (*TemplateElement_Facts) isTemplateElement_Of() {}

func (*TemplateElement_Divider) isTemplateElement_Of() {}

func (*TemplateElement_Section) isTemplateElement_Of() {}

type Facts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Facts         []*FactRef             `protobuf:"bytes,1,rep,name=facts,proto3" json:"facts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Facts) Reset() {
	*x = Facts{}
	mi := &file_garm_card_v1_card_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Facts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Facts) ProtoMessage() {}

func (x *Facts) ProtoReflect() protoreflect.Message {
	mi := &file_garm_card_v1_card_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Facts.ProtoReflect.Descriptor instead.
func (*Facts) Descriptor() ([]byte, []int) {
	return file_garm_card_v1_card_proto_rawDescGZIP(), []int{24}
}

func (x *Facts) GetFacts() []*FactRef {
	if x != nil {
		return x.Facts
	}
	return nil
}

// A declared fact, and optionally who may see it.
//
// `access` unset means the source field's own policy, which is what the
// generated default would have labelled it anyway — so an author only writes
// one when they want it TIGHTER. It can never usefully be looser: an element
// labelled below its card endpoint fails the whole card, and a child labelled
// below its Section is lint C8.
type FactRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Access        *Label                 `protobuf:"bytes,3,opt,name=access,proto3" json:"access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactRef) Reset() {
	*x = FactRef{}
	mi := &file_garm_card_v1_card_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactRef) ProtoMessage() {}

func (x *FactRef) ProtoReflect() protoreflect.Message {
	mi := &file_garm_card_v1_card_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactRef.ProtoReflect.Descriptor instead.
func (*FactRef) Descriptor() ([]byte, []int) {
	return file_garm_card_v1_card_proto_rawDescGZIP(), []int{25}
}

func (x *FactRef) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *FactRef) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *FactRef) GetAccess() *Label {
	if x != nil {
		return x.Access
	}
	return nil
}

// A titled group, and the FLOOR of everything inside it.
//
// A section is how a card says "this block is compliance's". Its label is a
// floor rather than a value: a child may be labelled higher — one fact inside
// a compliance section that only the head of compliance sees — and never
// lower, because a reader who cannot see the heading cannot be shown what was
// under it (lint C8).
type TemplateSection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Elements      []*TemplateElement     `protobuf:"bytes,2,rep,name=elements,proto3" json:"elements,omitempty"`
	Access        *Label                 `protobuf:"bytes,3,opt,name=access,proto3" json:"access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateSection) Reset() {
	*x = TemplateSection{}
	mi := &file_garm_card_v1_card_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateSection) ProtoMessage() {}

func (x *TemplateSection) ProtoReflect() protoreflect.Message {
	mi := &file_garm_card_v1_card_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateSection.ProtoReflect.Descriptor instead.
func (*TemplateSection) Descriptor() ([]byte, []int) {
	return file_garm_card_v1_card_proto_rawDescGZIP(), []int{26}
}

func (x *TemplateSection) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TemplateSection) GetElements() []*TemplateElement {
	if x != nil {
		return x.Elements
	}
	return nil
}

func (x *TemplateSection) GetAccess() *Label {
	if x != nil {
		return x.Access
	}
	return nil
}

var file_garm_card_v1_card_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*Template)(nil),
		Field:         50201,
		Name:          "garm.card.v1.result_card",
		Tag:           "bytes,50201,opt,name=result_card",
		Filename:      "garm/card/v1/card.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Template)(nil),
		Field:         50202,
		Name:          "garm.card.v1.task_card",
		Tag:           "bytes,50202,opt,name=task_card",
		Filename:      "garm/card/v1/card.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*CardRole)(nil),
		Field:         50203,
		Name:          "garm.card.v1.card_role",
		Tag:           "varint,50203,opt,name=card_role,enum=garm.card.v1.CardRole",
		Filename:      "garm/card/v1/card.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional garm.card.v1.Template result_card = 50201;
	E_ResultCard = &file_garm_card_v1_card_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional garm.card.v1.Template task_card = 50202;
	E_TaskCard = &file_garm_card_v1_card_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional garm.card.v1.CardRole card_role = 50203;
	E_CardRole = &file_garm_card_v1_card_proto_extTypes[2]
)

var File_garm_card_v1_card_proto protoreflect.FileDescriptor

const file_garm_card_v1_card_proto_rawDesc = "" +
	"\n" +
	"\x17garm/card/v1/card.proto\x12\fgarm.card.v1\x1a google/protobuf/descriptor.proto\x1a\x17garm/tool/v1/tool.proto\"b\n" +
	"\x05Label\x125\n" +
	"\tclearance\x18\x01 \x01(\x0e2\x17.garm.tool.v1.ClearanceR\tclearance\x12\"\n" +
	"\fcompartments\x18\x02 \x03(\tR\fcompartments\"?\n" +
	"\aCallRef\x12\x1c\n" +
	"\acall_id\x18\x01 \x01(\tH\x00R\x06callId\x88\x01\x01:\n" +
	"\x9a\xb5\x18\x06\b\n" +
	"\"\x02\n" +
	"\x00B\n" +
	"\n" +
	"\b_call_id\"\xbd\x01\n" +
	"\aTaskRef\x12\x1c\n" +
	"\atask_id\x18\x01 \x01(\tH\x00R\x06taskId\x88\x01\x01\x12?\n" +
	"\bmaterial\x18\x02 \x03(\v2#.garm.card.v1.TaskRef.MaterialEntryR\bmaterial\x1a;\n" +
	"\rMaterialEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:\n" +
	"\x9a\xb5\x18\x06\b\n" +
	"\"\x02\n" +
	"\x00B\n" +
	"\n" +
	"\b_task_id\"\xa6\x03\n" +
	"\x04Card\x12&\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x12.garm.card.v1.KindR\x04kind\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12)\n" +
	"\x05state\x18\x04 \x01(\x0e2\x13.garm.card.v1.StateR\x05state\x12)\n" +
	"\x04body\x18\x05 \x03(\v2\x15.garm.card.v1.ElementR\x04body\x12.\n" +
	"\aactions\x18\x06 \x03(\v2\x14.garm.card.v1.ActionR\aactions\x128\n" +
	"\n" +
	"disclosure\x18\a \x01(\v2\x18.garm.card.v1.DisclosureR\n" +
	"disclosure\x12)\n" +
	"\x04refs\x18\b \x03(\v2\x15.garm.card.v1.CardRefR\x04refs\x12)\n" +
	"\x10catalogue_digest\x18\t \x01(\tR\x0fcatalogueDigest\x12+\n" +
	"\x06access\x18\n" +
	" \x01(\v2\x13.garm.card.v1.LabelR\x06access\"\xac\x01\n" +
	"\aCardRef\x12&\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x12.garm.card.v1.KindR\x04kind\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12)\n" +
	"\x05state\x18\x04 \x01(\x0e2\x13.garm.card.v1.StateR\x05state\x12\x19\n" +
	"\btool_fqn\x18\x05 \x01(\tR\atoolFqn\"\xa8\x02\n" +
	"\aElement\x12(\n" +
	"\x04text\x18\x01 \x01(\v2\x12.garm.card.v1.TextH\x00R\x04text\x12-\n" +
	"\x05facts\x18\x02 \x01(\v2\x15.garm.card.v1.FactSetH\x00R\x05facts\x121\n" +
	"\adivider\x18\x03 \x01(\v2\x15.garm.card.v1.DividerH\x00R\adivider\x12+\n" +
	"\x05input\x18\x04 \x01(\v2\x13.garm.card.v1.InputH\x00R\x05input\x121\n" +
	"\asection\x18\x05 \x01(\v2\x15.garm.card.v1.SectionH\x00R\asection\x12+\n" +
	"\x06access\x18\n" +
	" \x01(\v2\x13.garm.card.v1.LabelR\x06accessB\x04\n" +
	"\x02of\"N\n" +
	"\x04Text\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x122\n" +
	"\bemphasis\x18\x02 \x01(\x0e2\x16.garm.card.v1.EmphasisR\bemphasis\"3\n" +
	"\aFactSet\x12(\n" +
	"\x05facts\x18\x01 \x03(\v2\x12.garm.card.v1.FactR\x05facts\"u\n" +
	"\x04Fact\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x14\n" +
	"\x05field\x18\x03 \x01(\tR\x05field\x12+\n" +
	"\x06access\x18\x04 \x01(\v2\x13.garm.card.v1.LabelR\x06access\"\t\n" +
	"\aDivider\"R\n" +
	"\aSection\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x121\n" +
	"\belements\x18\x02 \x03(\v2\x15.garm.card.v1.ElementR\belements\"\xce\x02\n" +
	"\x05Input\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12-\n" +
	"\x04text\x18\x04 \x01(\v2\x17.garm.card.v1.TextInputH\x00R\x04text\x123\n" +
	"\x06number\x18\x05 \x01(\v2\x19.garm.card.v1.NumberInputH\x00R\x06number\x12-\n" +
	"\x04date\x18\x06 \x01(\v2\x17.garm.card.v1.DateInputH\x00R\x04date\x123\n" +
	"\x06toggle\x18\a \x01(\v2\x19.garm.card.v1.ToggleInputH\x00R\x06toggle\x123\n" +
	"\x06choice\x18\b \x01(\v2\x19.garm.card.v1.ChoiceInputH\x00R\x06choiceB\x06\n" +
	"\x04kind\"B\n" +
	"\tTextInput\x12\x17\n" +
	"\amax_len\x18\x01 \x01(\rR\x06maxLen\x12\x1c\n" +
	"\tmultiline\x18\x02 \x01(\bR\tmultiline\"1\n" +
	"\vNumberInput\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x01R\x03max\"\v\n" +
	"\tDateInput\"\r\n" +
	"\vToggleInput\"~\n" +
	"\vChoiceInput\x12.\n" +
	"\achoices\x18\x01 \x03(\v2\x14.garm.card.v1.ChoiceR\achoices\x12)\n" +
	"\x05query\x18\x02 \x01(\v2\x13.garm.card.v1.QueryR\x05query\x12\x14\n" +
	"\x05multi\x18\x03 \x01(\bR\x05multi\"a\n" +
	"\x06Choice\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12+\n" +
	"\x06access\x18\x03 \x01(\v2\x13.garm.card.v1.LabelR\x06access\"U\n" +
	"\x05Query\x12\x12\n" +
	"\x04tool\x18\x01 \x01(\tR\x04tool\x12\x1b\n" +
	"\tmin_chars\x18\x02 \x01(\rR\bminChars\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSize\"\x91\x01\n" +
	"\x06Action\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12)\n" +
	"\x05style\x18\x03 \x01(\x0e2\x13.garm.card.v1.StyleR\x05style\x12.\n" +
	"\x06submit\x18\x04 \x01(\v2\x14.garm.card.v1.SubmitH\x00R\x06submitB\x06\n" +
	"\x04kind\"+\n" +
	"\x06Submit\x12!\n" +
	"\fconfirm_text\x18\x01 \x01(\tR\vconfirmText\"5\n" +
	"\n" +
	"Disclosure\x12'\n" +
	"\x0fwithheld_fields\x18\x01 \x03(\tR\x0ewithheldFields\"m\n" +
	"\bTemplate\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x121\n" +
	"\x04body\x18\x02 \x03(\v2\x1d.garm.card.v1.TemplateElementR\x04body\x12\x18\n" +
	"\acontext\x18\x03 \x01(\tR\acontext\"\xc8\x01\n" +
	"\x0fTemplateElement\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x12+\n" +
	"\x05facts\x18\x02 \x01(\v2\x13.garm.card.v1.FactsH\x00R\x05facts\x121\n" +
	"\adivider\x18\x03 \x01(\v2\x15.garm.card.v1.DividerH\x00R\adivider\x129\n" +
	"\asection\x18\x04 \x01(\v2\x1d.garm.card.v1.TemplateSectionH\x00R\asectionB\x04\n" +
	"\x02of\"4\n" +
	"\x05Facts\x12+\n" +
	"\x05facts\x18\x01 \x03(\v2\x15.garm.card.v1.FactRefR\x05facts\"b\n" +
	"\aFactRef\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12+\n" +
	"\x06access\x18\x03 \x01(\v2\x13.garm.card.v1.LabelR\x06access\"\x8f\x01\n" +
	"\x0fTemplateSection\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x129\n" +
	"\belements\x18\x02 \x03(\v2\x1d.garm.card.v1.TemplateElementR\belements\x12+\n" +
	"\x06access\x18\x03 \x01(\v2\x13.garm.card.v1.LabelR\x06access*C\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05START\x10\x01\x12\b\n" +
	"\x04TASK\x10\x02\x12\a\n" +
	"\x03RUN\x10\x03\x12\a\n" +
	"\x03ASK\x10\x04*k\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04OPEN\x10\x01\x12\f\n" +
	"\bANSWERED\x10\x02\x12\v\n" +
	"\aEXPIRED\x10\x03\x12\v\n" +
	"\aRUNNING\x10\x04\x12\r\n" +
	"\tCOMPLETED\x10\x05\x12\n" +
	"\n" +
	"\x06FAILED\x10\x06*0\n" +
	"\bEmphasis\x12\v\n" +
	"\aDEFAULT\x10\x00\x12\v\n" +
	"\aHEADING\x10\x01\x12\n" +
	"\n" +
	"\x06SUBTLE\x10\x02*9\n" +
	"\x05Style\x12\x11\n" +
	"\rSTYLE_DEFAULT\x10\x00\x12\f\n" +
	"\bPOSITIVE\x10\x01\x12\x0f\n" +
	"\vDESTRUCTIVE\x10\x02*O\n" +
	"\bCardRole\x12\x19\n" +
	"\x15CARD_ROLE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCARD_ROLE_TITLE\x10\x01\x12\x13\n" +
	"\x0fCARD_ROLE_VALUE\x10\x02:Z\n" +
	"\vresult_card\x12\x1f.google.protobuf.ServiceOptions\x18\x99\x88\x03 \x01(\v2\x16.garm.card.v1.TemplateR\n" +
	"resultCard:U\n" +
	"\ttask_card\x12\x1e.google.protobuf.MethodOptions\x18\x9a\x88\x03 \x01(\v2\x16.garm.card.v1.TemplateR\btaskCard:T\n" +
	"\tcard_role\x12\x1d.google.protobuf.FieldOptions\x18\x9b\x88\x03 \x01(\x0e2\x16.garm.card.v1.CardRoleR\bcardRoleB7Z5github.com/garm-ai/garm/contracts/garm/card/v1;cardv1b\x06proto3"

var (
	file_garm_card_v1_card_proto_rawDescOnce sync.Once
	file_garm_card_v1_card_proto_rawDescData []byte
)

func file_garm_card_v1_card_proto_rawDescGZIP() []byte {
	file_garm_card_v1_card_proto_rawDescOnce.Do(func() {
		file_garm_card_v1_card_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_garm_card_v1_card_proto_rawDesc), len(file_garm_card_v1_card_proto_rawDesc)))
	})
	return file_garm_card_v1_card_proto_rawDescData
}

var file_garm_card_v1_card_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_garm_card_v1_card_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_garm_card_v1_card_proto_goTypes = []any{
	(Kind)(0),                           // 0: garm.card.v1.Kind
	(State)(0),                          // 1: garm.card.v1.State
	(Emphasis)(0),                       // 2: garm.card.v1.Emphasis
	(Style)(0),                          // 3: garm.card.v1.Style
	(CardRole)(0),                       // 4: garm.card.v1.CardRole
	(*Label)(nil),                       // 5: garm.card.v1.Label
	(*CallRef)(nil),                     // 6: garm.card.v1.CallRef
	(*TaskRef)(nil),                     // 7: garm.card.v1.TaskRef
	(*Card)(nil),                        // 8: garm.card.v1.Card
	(*CardRef)(nil),                     // 9: garm.card.v1.CardRef
	(*Element)(nil),                     // 10: garm.card.v1.Element
	(*Text)(nil),                        // 11: garm.card.v1.Text
	(*FactSet)(nil),                     // 12: garm.card.v1.FactSet
	(*Fact)(nil),                        // 13: garm.card.v1.Fact
	(*Divider)(nil),                     // 14: garm.card.v1.Divider
	(*Section)(nil),                     // 15: garm.card.v1.Section
	(*Input)(nil),                       // 16: garm.card.v1.Input
	(*TextInput)(nil),                   // 17: garm.card.v1.TextInput
	(*NumberInput)(nil),                 // 18: garm.card.v1.NumberInput
	(*DateInput)(nil),                   // 19: garm.card.v1.DateInput
	(*ToggleInput)(nil),                 // 20: garm.card.v1.ToggleInput
	(*ChoiceInput)(nil),                 // 21: garm.card.v1.ChoiceInput
	(*Choice)(nil),                      // 22: garm.card.v1.Choice
	(*Query)(nil),                       // 23: garm.card.v1.Query
	(*Action)(nil),                      // 24: garm.card.v1.Action
	(*Submit)(nil),                      // 25: garm.card.v1.Submit
	(*Disclosure)(nil),                  // 26: garm.card.v1.Disclosure
	(*Template)(nil),                    // 27: garm.card.v1.Template
	(*TemplateElement)(nil),             // 28: garm.card.v1.TemplateElement
	(*Facts)(nil),                       // 29: garm.card.v1.Facts
	(*FactRef)(nil),                     // 30: garm.card.v1.FactRef
	(*TemplateSection)(nil),             // 31: garm.card.v1.TemplateSection
	nil,                                 // 32: garm.card.v1.TaskRef.MaterialEntry
	(v1.Clearance)(0),                   // 33: garm.tool.v1.Clearance
	(*descriptorpb.ServiceOptions)(nil), // 34: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 35: google.protobuf.MethodOptions
	(*descriptorpb.FieldOptions)(nil),   // 36: google.protobuf.FieldOptions
}
var file_garm_card_v1_card_proto_depIdxs = []int32{
	33, // 0: garm.card.v1.Label.clearance:type_name -> garm.tool.v1.Clearance
	32, // 1: garm.card.v1.TaskRef.material:type_name -> garm.card.v1.TaskRef.MaterialEntry
	0,  // 2: garm.card.v1.Card.kind:type_name -> garm.card.v1.Kind
	1,  // 3: garm.card.v1.Card.state:type_name -> garm.card.v1.State
	10, // 4: garm.card.v1.Card.body:type_name -> garm.card.v1.Element
	24, // 5: garm.card.v1.Card.actions:type_name -> garm.card.v1.Action
	26, // 6: garm.card.v1.Card.disclosure:type_name -> garm.card.v1.Disclosure
	9,  // 7: garm.card.v1.Card.refs:type_name -> garm.card.v1.CardRef
	5,  // 8: garm.card.v1.Card.access:type_name -> garm.card.v1.Label
	0,  // 9: garm.card.v1.CardRef.kind:type_name -> garm.card.v1.Kind
	1,  // 10: garm.card.v1.CardRef.state:type_name -> garm.card.v1.State
	11, // 11: garm.card.v1.Element.text:type_name -> garm.card.v1.Text
	12, // 12: garm.card.v1.Element.facts:type_name -> garm.card.v1.FactSet
	14, // 13: garm.card.v1.Element.divider:type_name -> garm.card.v1.Divider
	16, // 14: garm.card.v1.Element.input:type_name -> garm.card.v1.Input
	15, // 15: garm.card.v1.Element.section:type_name -> garm.card.v1.Section
	5,  // 16: garm.card.v1.Element.access:type_name -> garm.card.v1.Label
	2,  // 17: garm.card.v1.Text.emphasis:type_name -> garm.card.v1.Emphasis
	13, // 18: garm.card.v1.FactSet.facts:type_name -> garm.card.v1.Fact
	5,  // 19: garm.card.v1.Fact.access:type_name -> garm.card.v1.Label
	10, // 20: garm.card.v1.Section.elements:type_name -> garm.card.v1.Element
	17, // 21: garm.card.v1.Input.text:type_name -> garm.card.v1.TextInput
	18, // 22: garm.card.v1.Input.number:type_name -> garm.card.v1.NumberInput
	19, // 23: garm.card.v1.Input.date:type_name -> garm.card.v1.DateInput
	20, // 24: garm.card.v1.Input.toggle:type_name -> garm.card.v1.ToggleInput
	21, // 25: garm.card.v1.Input.choice:type_name -> garm.card.v1.ChoiceInput
	22, // 26: garm.card.v1.ChoiceInput.choices:type_name -> garm.card.v1.Choice
	23, // 27: garm.card.v1.ChoiceInput.query:type_name -> garm.card.v1.Query
	5,  // 28: garm.card.v1.Choice.access:type_name -> garm.card.v1.Label
	3,  // 29: garm.card.v1.Action.style:type_name -> garm.card.v1.Style
	25, // 30: garm.card.v1.Action.submit:type_name -> garm.card.v1.Submit
	28, // 31: garm.card.v1.Template.body:type_name -> garm.card.v1.TemplateElement
	29, // 32: garm.card.v1.TemplateElement.facts:type_name -> garm.card.v1.Facts
	14, // 33: garm.card.v1.TemplateElement.divider:type_name -> garm.card.v1.Divider
	31, // 34: garm.card.v1.TemplateElement.section:type_name -> garm.card.v1.TemplateSection
	30, // 35: garm.card.v1.Facts.facts:type_name -> garm.card.v1.FactRef
	5,  // 36: garm.card.v1.FactRef.access:type_name -> garm.card.v1.Label
	28, // 37: garm.card.v1.TemplateSection.elements:type_name -> garm.card.v1.TemplateElement
	5,  // 38: garm.card.v1.TemplateSection.access:type_name -> garm.card.v1.Label
	34, // 39: garm.card.v1.result_card:extendee -> google.protobuf.ServiceOptions
	35, // 40: garm.card.v1.task_card:extendee -> google.protobuf.MethodOptions
	36, // 41: garm.card.v1.card_role:extendee -> google.protobuf.FieldOptions
	27, // 42: garm.card.v1.result_card:type_name -> garm.card.v1.Template
	27, // 43: garm.card.v1.task_card:type_name -> garm.card.v1.Template
	4,  // 44: garm.card.v1.card_role:type_name -> garm.card.v1.CardRole
	45, // [45:45] is the sub-list for method output_type
	45, // [45:45] is the sub-list for method input_type
	42, // [42:45] is the sub-list for extension type_name
	39, // [39:42] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_garm_card_v1_card_proto_init() }
func file_garm_card_v1_card_proto_init() {
	if File_garm_card_v1_card_proto != nil {
		return
	}
	file_garm_card_v1_card_proto_msgTypes[1].OneofWrappers = []any{}
	file_garm_card_v1_card_proto_msgTypes[2].OneofWrappers = []any{}
	file_garm_card_v1_card_proto_msgTypes[5].OneofWrappers = []any{
		(*Element_Text)(nil),
		(*Element_Facts)(nil),
		(*Element_Divider)(nil),
		(*Element_Input)(nil),
		(*Element_Section)(nil),
	}
	file_garm_card_v1_card_proto_msgTypes[11].OneofWrappers = []any{
		(*Input_Text)(nil),
		(*Input_Number)(nil),
		(*Input_Date)(nil),
		(*Input_Toggle)(nil),
		(*Input_Choice)(nil),
	}
	file_garm_card_v1_card_proto_msgTypes[19].OneofWrappers = []any{
		(*Action_Submit)(nil),
	}
	file_garm_card_v1_card_proto_msgTypes[23].OneofWrappers = []any{
		(*TemplateElement_Text)(nil),
		(*TemplateElement_Facts)(nil),
		(*TemplateElement_Divider)(nil),
		(*TemplateElement_Section)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_garm_card_v1_card_proto_rawDesc), len(file_garm_card_v1_card_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   28,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_garm_card_v1_card_proto_goTypes,
		DependencyIndexes: file_garm_card_v1_card_proto_depIdxs,
		EnumInfos:         file_garm_card_v1_card_proto_enumTypes,
		MessageInfos:      file_garm_card_v1_card_proto_msgTypes,
		ExtensionInfos:    file_garm_card_v1_card_proto_extTypes,
	}.Build()
	File_garm_card_v1_card_proto = out.File
	file_garm_card_v1_card_proto_goTypes = nil
	file_garm_card_v1_card_proto_depIdxs = nil
}
