// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: fixture.proto

package testdataconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	testdata "github.com/garm-ai/garm/policy/testdata"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TestServiceName is the fully-qualified name of the TestService service.
	TestServiceName = "policy.testdata.TestService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TestServiceGetProfileProcedure is the fully-qualified name of the TestService's GetProfile RPC.
	TestServiceGetProfileProcedure = "/policy.testdata.TestService/GetProfile"
	// TestServiceUpdateProfileProcedure is the fully-qualified name of the TestService's UpdateProfile
	// RPC.
	TestServiceUpdateProfileProcedure = "/policy.testdata.TestService/UpdateProfile"
)

// TestServiceClient is a client for the policy.testdata.TestService service.
type TestServiceClient interface {
	GetProfile(context.Context, *connect.Request[testdata.GetProfileRequest]) (*connect.Response[testdata.GetProfileResponse], error)
	UpdateProfile(context.Context, *connect.Request[testdata.UpdateProfileRequest]) (*connect.Response[testdata.UpdateProfileResponse], error)
}

// NewTestServiceClient constructs a client for the policy.testdata.TestService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTestServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TestServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	testServiceMethods := testdata.File_fixture_proto.Services().ByName("TestService").Methods()
	return &testServiceClient{
		getProfile: connect.NewClient[testdata.GetProfileRequest, testdata.GetProfileResponse](
			httpClient,
			baseURL+TestServiceGetProfileProcedure,
			connect.WithSchema(testServiceMethods.ByName("GetProfile")),
			connect.WithClientOptions(opts...),
		),
		updateProfile: connect.NewClient[testdata.UpdateProfileRequest, testdata.UpdateProfileResponse](
			httpClient,
			baseURL+TestServiceUpdateProfileProcedure,
			connect.WithSchema(testServiceMethods.ByName("UpdateProfile")),
			connect.WithClientOptions(opts...),
		),
	}
}

// testServiceClient implements TestServiceClient.
type testServiceClient struct {
	getProfile    *connect.Client[testdata.GetProfileRequest, testdata.GetProfileResponse]
	updateProfile *connect.Client[testdata.UpdateProfileRequest, testdata.UpdateProfileResponse]
}

// GetProfile calls policy.testdata.TestService.GetProfile.
func (c *testServiceClient) GetProfile(ctx context.Context, req *connect.Request[testdata.GetProfileRequest]) (*connect.Response[testdata.GetProfileResponse], error) {
	return c.getProfile.CallUnary(ctx, req)
}

// UpdateProfile calls policy.testdata.TestService.UpdateProfile.
func (c *testServiceClient) UpdateProfile(ctx context.Context, req *connect.Request[testdata.UpdateProfileRequest]) (*connect.Response[testdata.UpdateProfileResponse], error) {
	return c.updateProfile.CallUnary(ctx, req)
}

// TestServiceHandler is an implementation of the policy.testdata.TestService service.
type TestServiceHandler interface {
	GetProfile(context.Context, *connect.Request[testdata.GetProfileRequest]) (*connect.Response[testdata.GetProfileResponse], error)
	UpdateProfile(context.Context, *connect.Request[testdata.UpdateProfileRequest]) (*connect.Response[testdata.UpdateProfileResponse], error)
}

// NewTestServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTestServiceHandler(svc TestServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	testServiceMethods := testdata.File_fixture_proto.Services().ByName("TestService").Methods()
	testServiceGetProfileHandler := connect.NewUnaryHandler(
		TestServiceGetProfileProcedure,
		svc.GetProfile,
		connect.WithSchema(testServiceMethods.ByName("GetProfile")),
		connect.WithHandlerOptions(opts...),
	)
	testServiceUpdateProfileHandler := connect.NewUnaryHandler(
		TestServiceUpdateProfileProcedure,
		svc.UpdateProfile,
		connect.WithSchema(testServiceMethods.ByName("UpdateProfile")),
		connect.WithHandlerOptions(opts...),
	)
	return "/policy.testdata.TestService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TestServiceGetProfileProcedure:
			testServiceGetProfileHandler.ServeHTTP(w, r)
		case TestServiceUpdateProfileProcedure:
			testServiceUpdateProfileHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTestServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTestServiceHandler struct{}

func (UnimplementedTestServiceHandler) GetProfile(context.Context, *connect.Request[testdata.GetProfileRequest]) (*connect.Response[testdata.GetProfileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("policy.testdata.TestService.GetProfile is not implemented"))
}

func (UnimplementedTestServiceHandler) UpdateProfile(context.Context, *connect.Request[testdata.UpdateProfileRequest]) (*connect.Response[testdata.UpdateProfileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("policy.testdata.TestService.UpdateProfile is not implemented"))
}
