// The record of one call, on the wire.
//
// This is the transport form of contracts/ledger.Event. It exists as a proto
// rather than as JSON of the Go struct because the thing that READS it is a
// different binary, in a different repository, with a different release
// cadence — and may one day not be Go at all. A Go struct serialised to JSON
// is a schema with no versioning story and no way to add a field without
// hoping every reader tolerated it.
//
// It is deliberately SELF-CONTAINED: nothing here imports the tool contract.
// A forwarder that turns these into Parquet has no business linking the
// annotation schema, the policy compiler, or anything else it would inherit
// by importing garm.tool.v1.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: garm/ledger/v1/event.proto

package ledgerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event is one call, published on garm.v1.ledger.<tenant>.<app> or
// garm.v1.audit.<tenant>.<app>.
//
// Delivery is at-least-once, so the lake WILL hold duplicates and consumers
// must dedupe on event_id. That is not a defect to be engineered away: the
// alternative to at-least-once is at-most-once, which for a ledger means
// losing rows on exactly the failures anyone would want a row for.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// event_id is the idempotency key, and it must be assigned ONCE, when the
	// event is created — never at publish time.
	//
	// A publisher that generates it while sending gives a retried batch new
	// ids, so the duplicates it produces are indistinguishable from distinct
	// calls and dedupe silently stops working. The whole at-least-once story
	// rests on this one field being stable across retries.
	EventId string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Time    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	// Attribution: who and what, independent of the call itself.
	Tenant        string            `protobuf:"bytes,10,opt,name=tenant,proto3" json:"tenant,omitempty"`
	App           string            `protobuf:"bytes,11,opt,name=app,proto3" json:"app,omitempty"`
	Feature       string            `protobuf:"bytes,12,opt,name=feature,proto3" json:"feature,omitempty"`
	RunId         string            `protobuf:"bytes,13,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	CorrelationId string            `protobuf:"bytes,14,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	CausationId   string            `protobuf:"bytes,15,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	BudgetId      string            `protobuf:"bytes,16,opt,name=budget_id,json=budgetId,proto3" json:"budget_id,omitempty"`
	Tags          map[string]string `protobuf:"bytes,17,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The generation plane's half. Empty on a tool call, and that is how the
	// two are told apart in the lake — one Event type for both planes, because
	// "what did this agent cost and what did it touch" is one question.
	PromptName        string  `protobuf:"bytes,20,opt,name=prompt_name,json=promptName,proto3" json:"prompt_name,omitempty"` // "raw" for message-path calls
	PromptHash        string  `protobuf:"bytes,21,opt,name=prompt_hash,json=promptHash,proto3" json:"prompt_hash,omitempty"`
	Alias             string  `protobuf:"bytes,22,opt,name=alias,proto3" json:"alias,omitempty"`
	ResolvedModel     string  `protobuf:"bytes,23,opt,name=resolved_model,json=resolvedModel,proto3" json:"resolved_model,omitempty"`
	ModelOverridden   bool    `protobuf:"varint,24,opt,name=model_overridden,json=modelOverridden,proto3" json:"model_overridden,omitempty"`
	Usage             *Usage  `protobuf:"bytes,30,opt,name=usage,proto3" json:"usage,omitempty"`
	CostUsd           float64 `protobuf:"fixed64,31,opt,name=cost_usd,json=costUsd,proto3" json:"cost_usd,omitempty"`
	CostSource        string  `protobuf:"bytes,32,opt,name=cost_source,json=costSource,proto3" json:"cost_source,omitempty"` // "computed", or empty when no price is known
	LatencyMs         int64   `protobuf:"varint,33,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	ProviderRequestId string  `protobuf:"bytes,40,opt,name=provider_request_id,json=providerRequestId,proto3" json:"provider_request_id,omitempty"`
	FallbackUsed      bool    `protobuf:"varint,41,opt,name=fallback_used,json=fallbackUsed,proto3" json:"fallback_used,omitempty"`
	// "ok" | "error" | "interrupted" | "denied" | "intent".
	//
	// "intent" is an audit-stream row written BEFORE the call ran, and it never
	// appears in the ledger. An intent with no matching outcome means a call
	// was authorised, started, and never accounted for.
	Outcome          string   `protobuf:"bytes,42,opt,name=outcome,proto3" json:"outcome,omitempty"`
	ErrorKind        string   `protobuf:"bytes,43,opt,name=error_kind,json=errorKind,proto3" json:"error_kind,omitempty"`
	PolicyMode       string   `protobuf:"bytes,50,opt,name=policy_mode,json=policyMode,proto3" json:"policy_mode,omitempty"`
	PolicyViolations []string `protobuf:"bytes,51,rep,name=policy_violations,json=policyViolations,proto3" json:"policy_violations,omitempty"`
	// The tool plane's half: paths and plan hashes only.
	//
	// No redacted VALUE may reach here. The ledger is queried by people who are
	// not the caller and is retained far longer than any response, so a value
	// withheld from the caller and written here would be disclosed to a wider
	// audience for longer — the precise inversion the redaction prevented.
	Tool                  string   `protobuf:"bytes,60,opt,name=tool,proto3" json:"tool,omitempty"`
	PrincipalSubject      string   `protobuf:"bytes,61,opt,name=principal_subject,json=principalSubject,proto3" json:"principal_subject,omitempty"`
	PrincipalActor        string   `protobuf:"bytes,62,opt,name=principal_actor,json=principalActor,proto3" json:"principal_actor,omitempty"`
	PrincipalKind         string   `protobuf:"bytes,63,opt,name=principal_kind,json=principalKind,proto3" json:"principal_kind,omitempty"`
	ChainDepth            int32    `protobuf:"varint,64,opt,name=chain_depth,json=chainDepth,proto3" json:"chain_depth,omitempty"`
	ClearanceEffective    string   `protobuf:"bytes,65,opt,name=clearance_effective,json=clearanceEffective,proto3" json:"clearance_effective,omitempty"`
	CompartmentsEffective []string `protobuf:"bytes,66,rep,name=compartments_effective,json=compartmentsEffective,proto3" json:"compartments_effective,omitempty"`
	RedactionPlan         string   `protobuf:"bytes,67,opt,name=redaction_plan,json=redactionPlan,proto3" json:"redaction_plan,omitempty"`
	RedactionCount        int32    `protobuf:"varint,68,opt,name=redaction_count,json=redactionCount,proto3" json:"redaction_count,omitempty"`
	DisclosedCount        int32    `protobuf:"varint,69,opt,name=disclosed_count,json=disclosedCount,proto3" json:"disclosed_count,omitempty"`
	// error_detail is the pre-scrub error text, and the ONLY field here that
	// may carry unsanitized free text.
	//
	// A resolver error routinely interpolates the value it was protecting
	// ("user with email ada@corp.com not found") and the response sanitizer
	// never sees it. What reaches the caller is a code and a static message;
	// the detail lands here so it is not simply destroyed — destroying it is
	// the pressure that makes someone log the error inside a handler and leak
	// exactly what the scrubbing prevented.
	//
	// It therefore inherits the retention and access controls of the most
	// sensitive field of the tool that produced it. A lake that treats this
	// column like the others has undone the redaction.
	ErrorDetail   string `protobuf:"bytes,70,opt,name=error_detail,json=errorDetail,proto3" json:"error_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_garm_ledger_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_garm_ledger_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_garm_ledger_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Event) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *Event) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *Event) GetFeature() string {
	if x != nil {
		return x.Feature
	}
	return ""
}

func (x *Event) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Event) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Event) GetCausationId() string {
	if x != nil {
		return x.CausationId
	}
	return ""
}

func (x *Event) GetBudgetId() string {
	if x != nil {
		return x.BudgetId
	}
	return ""
}

func (x *Event) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Event) GetPromptName() string {
	if x != nil {
		return x.PromptName
	}
	return ""
}

func (x *Event) GetPromptHash() string {
	if x != nil {
		return x.PromptHash
	}
	return ""
}

func (x *Event) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *Event) GetResolvedModel() string {
	if x != nil {
		return x.ResolvedModel
	}
	return ""
}

func (x *Event) GetModelOverridden() bool {
	if x != nil {
		return x.ModelOverridden
	}
	return false
}

func (x *Event) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *Event) GetCostUsd() float64 {
	if x != nil {
		return x.CostUsd
	}
	return 0
}

func (x *Event) GetCostSource() string {
	if x != nil {
		return x.CostSource
	}
	return ""
}

func (x *Event) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *Event) GetProviderRequestId() string {
	if x != nil {
		return x.ProviderRequestId
	}
	return ""
}

func (x *Event) GetFallbackUsed() bool {
	if x != nil {
		return x.FallbackUsed
	}
	return false
}

func (x *Event) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *Event) GetErrorKind() string {
	if x != nil {
		return x.ErrorKind
	}
	return ""
}

func (x *Event) GetPolicyMode() string {
	if x != nil {
		return x.PolicyMode
	}
	return ""
}

func (x *Event) GetPolicyViolations() []string {
	if x != nil {
		return x.PolicyViolations
	}
	return nil
}

func (x *Event) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *Event) GetPrincipalSubject() string {
	if x != nil {
		return x.PrincipalSubject
	}
	return ""
}

func (x *Event) GetPrincipalActor() string {
	if x != nil {
		return x.PrincipalActor
	}
	return ""
}

func (x *Event) GetPrincipalKind() string {
	if x != nil {
		return x.PrincipalKind
	}
	return ""
}

func (x *Event) GetChainDepth() int32 {
	if x != nil {
		return x.ChainDepth
	}
	return 0
}

func (x *Event) GetClearanceEffective() string {
	if x != nil {
		return x.ClearanceEffective
	}
	return ""
}

func (x *Event) GetCompartmentsEffective() []string {
	if x != nil {
		return x.CompartmentsEffective
	}
	return nil
}

func (x *Event) GetRedactionPlan() string {
	if x != nil {
		return x.RedactionPlan
	}
	return ""
}

func (x *Event) GetRedactionCount() int32 {
	if x != nil {
		return x.RedactionCount
	}
	return 0
}

func (x *Event) GetDisclosedCount() int32 {
	if x != nil {
		return x.DisclosedCount
	}
	return 0
}

func (x *Event) GetErrorDetail() string {
	if x != nil {
		return x.ErrorDetail
	}
	return ""
}

type Usage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InputTokens     int64                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens    int64                  `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	CachedTokens    int64                  `protobuf:"varint,3,opt,name=cached_tokens,json=cachedTokens,proto3" json:"cached_tokens,omitempty"`
	ReasoningTokens int64                  `protobuf:"varint,4,opt,name=reasoning_tokens,json=reasoningTokens,proto3" json:"reasoning_tokens,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_garm_ledger_v1_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_garm_ledger_v1_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_garm_ledger_v1_event_proto_rawDescGZIP(), []int{1}
}

func (x *Usage) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *Usage) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *Usage) GetCachedTokens() int64 {
	if x != nil {
		return x.CachedTokens
	}
	return 0
}

func (x *Usage) GetReasoningTokens() int64 {
	if x != nil {
		return x.ReasoningTokens
	}
	return 0
}

// Batch is what a publisher actually sends, and the reason it exists is the
// publisher's cost rather than the reader's convenience.
//
// One JetStream publish per call means one in-flight ack and one goroutine
// per call, and a bounded pending window that, once full, silently degrades
// metering to log lines under exactly the load worth metering. Batching
// amortises all three.
//
// The audit stream never uses this. A fail_closed tool's intent must be
// durable BEFORE the tool runs, and a batched write is by definition not yet
// written — batching a write-ahead is the same as not having one.
type Batch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Batch) Reset() {
	*x = Batch{}
	mi := &file_garm_ledger_v1_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batch) ProtoMessage() {}

func (x *Batch) ProtoReflect() protoreflect.Message {
	mi := &file_garm_ledger_v1_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batch.ProtoReflect.Descriptor instead.
func (*Batch) Descriptor() ([]byte, []int) {
	return file_garm_ledger_v1_event_proto_rawDescGZIP(), []int{2}
}

func (x *Batch) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_garm_ledger_v1_event_proto protoreflect.FileDescriptor

const file_garm_ledger_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x1agarm/ledger/v1/event.proto\x12\x0egarm.ledger.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc6\n" +
	"\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12.\n" +
	"\x04time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x16\n" +
	"\x06tenant\x18\n" +
	" \x01(\tR\x06tenant\x12\x10\n" +
	"\x03app\x18\v \x01(\tR\x03app\x12\x18\n" +
	"\afeature\x18\f \x01(\tR\afeature\x12\x15\n" +
	"\x06run_id\x18\r \x01(\tR\x05runId\x12%\n" +
	"\x0ecorrelation_id\x18\x0e \x01(\tR\rcorrelationId\x12!\n" +
	"\fcausation_id\x18\x0f \x01(\tR\vcausationId\x12\x1b\n" +
	"\tbudget_id\x18\x10 \x01(\tR\bbudgetId\x123\n" +
	"\x04tags\x18\x11 \x03(\v2\x1f.garm.ledger.v1.Event.TagsEntryR\x04tags\x12\x1f\n" +
	"\vprompt_name\x18\x14 \x01(\tR\n" +
	"promptName\x12\x1f\n" +
	"\vprompt_hash\x18\x15 \x01(\tR\n" +
	"promptHash\x12\x14\n" +
	"\x05alias\x18\x16 \x01(\tR\x05alias\x12%\n" +
	"\x0eresolved_model\x18\x17 \x01(\tR\rresolvedModel\x12)\n" +
	"\x10model_overridden\x18\x18 \x01(\bR\x0fmodelOverridden\x12+\n" +
	"\x05usage\x18\x1e \x01(\v2\x15.garm.ledger.v1.UsageR\x05usage\x12\x19\n" +
	"\bcost_usd\x18\x1f \x01(\x01R\acostUsd\x12\x1f\n" +
	"\vcost_source\x18  \x01(\tR\n" +
	"costSource\x12\x1d\n" +
	"\n" +
	"latency_ms\x18! \x01(\x03R\tlatencyMs\x12.\n" +
	"\x13provider_request_id\x18( \x01(\tR\x11providerRequestId\x12#\n" +
	"\rfallback_used\x18) \x01(\bR\ffallbackUsed\x12\x18\n" +
	"\aoutcome\x18* \x01(\tR\aoutcome\x12\x1d\n" +
	"\n" +
	"error_kind\x18+ \x01(\tR\terrorKind\x12\x1f\n" +
	"\vpolicy_mode\x182 \x01(\tR\n" +
	"policyMode\x12+\n" +
	"\x11policy_violations\x183 \x03(\tR\x10policyViolations\x12\x12\n" +
	"\x04tool\x18< \x01(\tR\x04tool\x12+\n" +
	"\x11principal_subject\x18= \x01(\tR\x10principalSubject\x12'\n" +
	"\x0fprincipal_actor\x18> \x01(\tR\x0eprincipalActor\x12%\n" +
	"\x0eprincipal_kind\x18? \x01(\tR\rprincipalKind\x12\x1f\n" +
	"\vchain_depth\x18@ \x01(\x05R\n" +
	"chainDepth\x12/\n" +
	"\x13clearance_effective\x18A \x01(\tR\x12clearanceEffective\x125\n" +
	"\x16compartments_effective\x18B \x03(\tR\x15compartmentsEffective\x12%\n" +
	"\x0eredaction_plan\x18C \x01(\tR\rredactionPlan\x12'\n" +
	"\x0fredaction_count\x18D \x01(\x05R\x0eredactionCount\x12'\n" +
	"\x0fdisclosed_count\x18E \x01(\x05R\x0edisclosedCount\x12!\n" +
	"\ferror_detail\x18F \x01(\tR\verrorDetail\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9f\x01\n" +
	"\x05Usage\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x03R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x03R\foutputTokens\x12#\n" +
	"\rcached_tokens\x18\x03 \x01(\x03R\fcachedTokens\x12)\n" +
	"\x10reasoning_tokens\x18\x04 \x01(\x03R\x0freasoningTokens\"6\n" +
	"\x05Batch\x12-\n" +
	"\x06events\x18\x01 \x03(\v2\x15.garm.ledger.v1.EventR\x06eventsB;Z9github.com/garm-ai/garm/contracts/garm/ledger/v1;ledgerv1b\x06proto3"

var (
	file_garm_ledger_v1_event_proto_rawDescOnce sync.Once
	file_garm_ledger_v1_event_proto_rawDescData []byte
)

func file_garm_ledger_v1_event_proto_rawDescGZIP() []byte {
	file_garm_ledger_v1_event_proto_rawDescOnce.Do(func() {
		file_garm_ledger_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_garm_ledger_v1_event_proto_rawDesc), len(file_garm_ledger_v1_event_proto_rawDesc)))
	})
	return file_garm_ledger_v1_event_proto_rawDescData
}

var file_garm_ledger_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_garm_ledger_v1_event_proto_goTypes = []any{
	(*Event)(nil),                 // 0: garm.ledger.v1.Event
	(*Usage)(nil),                 // 1: garm.ledger.v1.Usage
	(*Batch)(nil),                 // 2: garm.ledger.v1.Batch
	nil,                           // 3: garm.ledger.v1.Event.TagsEntry
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_garm_ledger_v1_event_proto_depIdxs = []int32{
	4, // 0: garm.ledger.v1.Event.time:type_name -> google.protobuf.Timestamp
	3, // 1: garm.ledger.v1.Event.tags:type_name -> garm.ledger.v1.Event.TagsEntry
	1, // 2: garm.ledger.v1.Event.usage:type_name -> garm.ledger.v1.Usage
	0, // 3: garm.ledger.v1.Batch.events:type_name -> garm.ledger.v1.Event
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_garm_ledger_v1_event_proto_init() }
func file_garm_ledger_v1_event_proto_init() {
	if File_garm_ledger_v1_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_garm_ledger_v1_event_proto_rawDesc), len(file_garm_ledger_v1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_garm_ledger_v1_event_proto_goTypes,
		DependencyIndexes: file_garm_ledger_v1_event_proto_depIdxs,
		MessageInfos:      file_garm_ledger_v1_event_proto_msgTypes,
	}.Build()
	File_garm_ledger_v1_event_proto = out.File
	file_garm_ledger_v1_event_proto_goTypes = nil
	file_garm_ledger_v1_event_proto_depIdxs = nil
}
