// Attribution: who a call is for and what it belongs to.
//
// Shared vocabulary rather than tool-specific. The ledger reads it, the
// generation plane produces it, and the tool plane carries it across the hop
// — "reused, never duplicated", as the envelope that carries it puts it.
//
// It lives in garm.tool.v1 because the tool plane is the only consumer that
// has moved out of the monorepo so far, and inventing a third proto package
// for one message would be paying now for a split nobody needs yet.
//
// THE TRIGGER for that split is named rather than left to judgement: the
// moment a SECOND plane outside this contract needs CallContext — the
// generation API moving out, or the ledger becoming its own artifact —
// attribution gets its own package. Until then a move would be churn.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: garm/tool/v1/attribution.proto

package toolv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	App           string                 `protobuf:"bytes,2,opt,name=app,proto3" json:"app,omitempty"`
	RunId         string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	CausationId   string                 `protobuf:"bytes,5,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	BudgetId      string                 `protobuf:"bytes,6,opt,name=budget_id,json=budgetId,proto3" json:"budget_id,omitempty"` // unused in steel thread; reserved for budget plan
	Tags          map[string]string      `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Static policy/attribution bucket between app and prompt (spec §4):
	// a product capability, a LangGraph graph, a MAF agent. Optional;
	// empty resolves against the manifest's app-level defaults.
	Feature       string `protobuf:"bytes,8,opt,name=feature,proto3" json:"feature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallContext) Reset() {
	*x = CallContext{}
	mi := &file_garm_tool_v1_attribution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallContext) ProtoMessage() {}

func (x *CallContext) ProtoReflect() protoreflect.Message {
	mi := &file_garm_tool_v1_attribution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallContext.ProtoReflect.Descriptor instead.
func (*CallContext) Descriptor() ([]byte, []int) {
	return file_garm_tool_v1_attribution_proto_rawDescGZIP(), []int{0}
}

func (x *CallContext) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *CallContext) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *CallContext) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *CallContext) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CallContext) GetCausationId() string {
	if x != nil {
		return x.CausationId
	}
	return ""
}

func (x *CallContext) GetBudgetId() string {
	if x != nil {
		return x.BudgetId
	}
	return ""
}

func (x *CallContext) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CallContext) GetFeature() string {
	if x != nil {
		return x.Feature
	}
	return ""
}

var File_garm_tool_v1_attribution_proto protoreflect.FileDescriptor

const file_garm_tool_v1_attribution_proto_rawDesc = "" +
	"\n" +
	"\x1egarm/tool/v1/attribution.proto\x12\fgarm.tool.v1\"\xc1\x02\n" +
	"\vCallContext\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x10\n" +
	"\x03app\x18\x02 \x01(\tR\x03app\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\x12%\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\tR\rcorrelationId\x12!\n" +
	"\fcausation_id\x18\x05 \x01(\tR\vcausationId\x12\x1b\n" +
	"\tbudget_id\x18\x06 \x01(\tR\bbudgetId\x127\n" +
	"\x04tags\x18\a \x03(\v2#.garm.tool.v1.CallContext.TagsEntryR\x04tags\x12\x18\n" +
	"\afeature\x18\b \x01(\tR\afeature\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B7Z5github.com/garm-ai/garm/contracts/garm/tool/v1;toolv1b\x06proto3"

var (
	file_garm_tool_v1_attribution_proto_rawDescOnce sync.Once
	file_garm_tool_v1_attribution_proto_rawDescData []byte
)

func file_garm_tool_v1_attribution_proto_rawDescGZIP() []byte {
	file_garm_tool_v1_attribution_proto_rawDescOnce.Do(func() {
		file_garm_tool_v1_attribution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_garm_tool_v1_attribution_proto_rawDesc), len(file_garm_tool_v1_attribution_proto_rawDesc)))
	})
	return file_garm_tool_v1_attribution_proto_rawDescData
}

var file_garm_tool_v1_attribution_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_garm_tool_v1_attribution_proto_goTypes = []any{
	(*CallContext)(nil), // 0: garm.tool.v1.CallContext
	nil,                 // 1: garm.tool.v1.CallContext.TagsEntry
}
var file_garm_tool_v1_attribution_proto_depIdxs = []int32{
	1, // 0: garm.tool.v1.CallContext.tags:type_name -> garm.tool.v1.CallContext.TagsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_garm_tool_v1_attribution_proto_init() }
func file_garm_tool_v1_attribution_proto_init() {
	if File_garm_tool_v1_attribution_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_garm_tool_v1_attribution_proto_rawDesc), len(file_garm_tool_v1_attribution_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_garm_tool_v1_attribution_proto_goTypes,
		DependencyIndexes: file_garm_tool_v1_attribution_proto_depIdxs,
		MessageInfos:      file_garm_tool_v1_attribution_proto_msgTypes,
	}.Build()
	File_garm_tool_v1_attribution_proto = out.File
	file_garm_tool_v1_attribution_proto_goTypes = nil
	file_garm_tool_v1_attribution_proto_depIdxs = nil
}
