// Typed, machine-readable error info attached as a connect error detail
// (spec §8): SDKs map on `code`, never on message text.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: garm/tool/v1/errors.proto

package toolv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One of: unknown_alias | prompt_hash_mismatch | invalid_request |
	// rate_limited | provider_unavailable | policy_violation (G1).
	Code          string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	RetryAfterMs  int64  `protobuf:"varint,2,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"` // set when code == rate_limited and known
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorInfo) Reset() {
	*x = ErrorInfo{}
	mi := &file_garm_tool_v1_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorInfo) ProtoMessage() {}

func (x *ErrorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_garm_tool_v1_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorInfo.ProtoReflect.Descriptor instead.
func (*ErrorInfo) Descriptor() ([]byte, []int) {
	return file_garm_tool_v1_errors_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorInfo) GetRetryAfterMs() int64 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

var File_garm_tool_v1_errors_proto protoreflect.FileDescriptor

const file_garm_tool_v1_errors_proto_rawDesc = "" +
	"\n" +
	"\x19garm/tool/v1/errors.proto\x12\fgarm.tool.v1\"E\n" +
	"\tErrorInfo\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12$\n" +
	"\x0eretry_after_ms\x18\x02 \x01(\x03R\fretryAfterMsB7Z5github.com/garm-ai/garm/contracts/garm/tool/v1;toolv1b\x06proto3"

var (
	file_garm_tool_v1_errors_proto_rawDescOnce sync.Once
	file_garm_tool_v1_errors_proto_rawDescData []byte
)

func file_garm_tool_v1_errors_proto_rawDescGZIP() []byte {
	file_garm_tool_v1_errors_proto_rawDescOnce.Do(func() {
		file_garm_tool_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_garm_tool_v1_errors_proto_rawDesc), len(file_garm_tool_v1_errors_proto_rawDesc)))
	})
	return file_garm_tool_v1_errors_proto_rawDescData
}

var file_garm_tool_v1_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_garm_tool_v1_errors_proto_goTypes = []any{
	(*ErrorInfo)(nil), // 0: garm.tool.v1.ErrorInfo
}
var file_garm_tool_v1_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_garm_tool_v1_errors_proto_init() }
func file_garm_tool_v1_errors_proto_init() {
	if File_garm_tool_v1_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_garm_tool_v1_errors_proto_rawDesc), len(file_garm_tool_v1_errors_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_garm_tool_v1_errors_proto_goTypes,
		DependencyIndexes: file_garm_tool_v1_errors_proto_depIdxs,
		MessageInfos:      file_garm_tool_v1_errors_proto_msgTypes,
	}.Build()
	File_garm_tool_v1_errors_proto = out.File
	file_garm_tool_v1_errors_proto_goTypes = nil
	file_garm_tool_v1_errors_proto_depIdxs = nil
}
