// What garm asserts to a tool for one invocation (tool-service-shell spec §4).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: garm/tool/v1/invocation.proto

package toolv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InvocationPrincipal is who the call is for. Named to avoid colliding with
// toolplane.Principal, which carries the policy inputs this deliberately
// does not.
type InvocationPrincipal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Kind          PrincipalKind          `protobuf:"varint,2,opt,name=kind,proto3,enum=garm.tool.v1.PrincipalKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvocationPrincipal) Reset() {
	*x = InvocationPrincipal{}
	mi := &file_garm_tool_v1_invocation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvocationPrincipal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvocationPrincipal) ProtoMessage() {}

func (x *InvocationPrincipal) ProtoReflect() protoreflect.Message {
	mi := &file_garm_tool_v1_invocation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvocationPrincipal.ProtoReflect.Descriptor instead.
func (*InvocationPrincipal) Descriptor() ([]byte, []int) {
	return file_garm_tool_v1_invocation_proto_rawDescGZIP(), []int{0}
}

func (x *InvocationPrincipal) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *InvocationPrincipal) GetKind() PrincipalKind {
	if x != nil {
		return x.Kind
	}
	return PrincipalKind_PRINCIPAL_KIND_UNSPECIFIED
}

// Act is one hop of a delegation chain (tools-server-design §6.2).
type Act struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Kind          PrincipalKind          `protobuf:"varint,2,opt,name=kind,proto3,enum=garm.tool.v1.PrincipalKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Act) Reset() {
	*x = Act{}
	mi := &file_garm_tool_v1_invocation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Act) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Act) ProtoMessage() {}

func (x *Act) ProtoReflect() protoreflect.Message {
	mi := &file_garm_tool_v1_invocation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Act.ProtoReflect.Descriptor instead.
func (*Act) Descriptor() ([]byte, []int) {
	return file_garm_tool_v1_invocation_proto_rawDescGZIP(), []int{1}
}

func (x *Act) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Act) GetKind() PrincipalKind {
	if x != nil {
		return x.Kind
	}
	return PrincipalKind_PRINCIPAL_KIND_UNSPECIFIED
}

// InvocationContext is what crosses the NATS hop beside the request.
//
// It carries ASSERTIONS, never credentials: forwarding the caller's token
// would hand every tool a replayable bearer credential and undo the §6.2
// intersection property that makes delegation safe.
//
// It deliberately does NOT carry clearance or compartments. The tool returns
// the full message and garm redacts; a tool that can see clearance is a tool
// that will eventually filter, which is a second unreviewed copy of the
// policy (spec §4.4).
type InvocationContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Attribution the ledger already understands. Reused, never duplicated.
	Attribution *CallContext         `protobuf:"bytes,1,opt,name=attribution,proto3" json:"attribution,omitempty"`
	Principal   *InvocationPrincipal `protobuf:"bytes,2,opt,name=principal,proto3" json:"principal,omitempty"`
	Act         []*Act               `protobuf:"bytes,3,rep,name=act,proto3" json:"act,omitempty"`
	// Delegation only: for attenuating a DOWNSTREAM call made on the caller's
	// behalf. Never an access decision (spec §4.4).
	Scopes      []string `protobuf:"bytes,4,rep,name=scopes,proto3" json:"scopes,omitempty"`
	Traceparent string   `protobuf:"bytes,5,opt,name=traceparent,proto3" json:"traceparent,omitempty"`
	Tracestate  string   `protobuf:"bytes,6,opt,name=tracestate,proto3" json:"tracestate,omitempty"`
	// Absolute, not a duration: a relative deadline restarts on every hop.
	Deadline        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=deadline,proto3" json:"deadline,omitempty"`
	CallId          string                 `protobuf:"bytes,8,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,9,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	ContractVersion string                 `protobuf:"bytes,10,opt,name=contract_version,json=contractVersion,proto3" json:"contract_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InvocationContext) Reset() {
	*x = InvocationContext{}
	mi := &file_garm_tool_v1_invocation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvocationContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvocationContext) ProtoMessage() {}

func (x *InvocationContext) ProtoReflect() protoreflect.Message {
	mi := &file_garm_tool_v1_invocation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvocationContext.ProtoReflect.Descriptor instead.
func (*InvocationContext) Descriptor() ([]byte, []int) {
	return file_garm_tool_v1_invocation_proto_rawDescGZIP(), []int{2}
}

func (x *InvocationContext) GetAttribution() *CallContext {
	if x != nil {
		return x.Attribution
	}
	return nil
}

func (x *InvocationContext) GetPrincipal() *InvocationPrincipal {
	if x != nil {
		return x.Principal
	}
	return nil
}

func (x *InvocationContext) GetAct() []*Act {
	if x != nil {
		return x.Act
	}
	return nil
}

func (x *InvocationContext) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *InvocationContext) GetTraceparent() string {
	if x != nil {
		return x.Traceparent
	}
	return ""
}

func (x *InvocationContext) GetTracestate() string {
	if x != nil {
		return x.Tracestate
	}
	return ""
}

func (x *InvocationContext) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *InvocationContext) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *InvocationContext) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *InvocationContext) GetContractVersion() string {
	if x != nil {
		return x.ContractVersion
	}
	return ""
}

var File_garm_tool_v1_invocation_proto protoreflect.FileDescriptor

const file_garm_tool_v1_invocation_proto_rawDesc = "" +
	"\n" +
	"\x1dgarm/tool/v1/invocation.proto\x12\fgarm.tool.v1\x1a\x1egarm/tool/v1/attribution.proto\x1a\x17garm/tool/v1/tool.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"`\n" +
	"\x13InvocationPrincipal\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12/\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1b.garm.tool.v1.PrincipalKindR\x04kind\"P\n" +
	"\x03Act\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12/\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1b.garm.tool.v1.PrincipalKindR\x04kind\"\xb5\x03\n" +
	"\x11InvocationContext\x12;\n" +
	"\vattribution\x18\x01 \x01(\v2\x19.garm.tool.v1.CallContextR\vattribution\x12?\n" +
	"\tprincipal\x18\x02 \x01(\v2!.garm.tool.v1.InvocationPrincipalR\tprincipal\x12#\n" +
	"\x03act\x18\x03 \x03(\v2\x11.garm.tool.v1.ActR\x03act\x12\x16\n" +
	"\x06scopes\x18\x04 \x03(\tR\x06scopes\x12 \n" +
	"\vtraceparent\x18\x05 \x01(\tR\vtraceparent\x12\x1e\n" +
	"\n" +
	"tracestate\x18\x06 \x01(\tR\n" +
	"tracestate\x126\n" +
	"\bdeadline\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12\x17\n" +
	"\acall_id\x18\b \x01(\tR\x06callId\x12'\n" +
	"\x0fidempotency_key\x18\t \x01(\tR\x0eidempotencyKey\x12)\n" +
	"\x10contract_version\x18\n" +
	" \x01(\tR\x0fcontractVersionB7Z5github.com/garm-ai/garm/contracts/garm/tool/v1;toolv1b\x06proto3"

var (
	file_garm_tool_v1_invocation_proto_rawDescOnce sync.Once
	file_garm_tool_v1_invocation_proto_rawDescData []byte
)

func file_garm_tool_v1_invocation_proto_rawDescGZIP() []byte {
	file_garm_tool_v1_invocation_proto_rawDescOnce.Do(func() {
		file_garm_tool_v1_invocation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_garm_tool_v1_invocation_proto_rawDesc), len(file_garm_tool_v1_invocation_proto_rawDesc)))
	})
	return file_garm_tool_v1_invocation_proto_rawDescData
}

var file_garm_tool_v1_invocation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_garm_tool_v1_invocation_proto_goTypes = []any{
	(*InvocationPrincipal)(nil),   // 0: garm.tool.v1.InvocationPrincipal
	(*Act)(nil),                   // 1: garm.tool.v1.Act
	(*InvocationContext)(nil),     // 2: garm.tool.v1.InvocationContext
	(PrincipalKind)(0),            // 3: garm.tool.v1.PrincipalKind
	(*CallContext)(nil),           // 4: garm.tool.v1.CallContext
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_garm_tool_v1_invocation_proto_depIdxs = []int32{
	3, // 0: garm.tool.v1.InvocationPrincipal.kind:type_name -> garm.tool.v1.PrincipalKind
	3, // 1: garm.tool.v1.Act.kind:type_name -> garm.tool.v1.PrincipalKind
	4, // 2: garm.tool.v1.InvocationContext.attribution:type_name -> garm.tool.v1.CallContext
	0, // 3: garm.tool.v1.InvocationContext.principal:type_name -> garm.tool.v1.InvocationPrincipal
	1, // 4: garm.tool.v1.InvocationContext.act:type_name -> garm.tool.v1.Act
	5, // 5: garm.tool.v1.InvocationContext.deadline:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_garm_tool_v1_invocation_proto_init() }
func file_garm_tool_v1_invocation_proto_init() {
	if File_garm_tool_v1_invocation_proto != nil {
		return
	}
	file_garm_tool_v1_attribution_proto_init()
	file_garm_tool_v1_tool_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_garm_tool_v1_invocation_proto_rawDesc), len(file_garm_tool_v1_invocation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_garm_tool_v1_invocation_proto_goTypes,
		DependencyIndexes: file_garm_tool_v1_invocation_proto_depIdxs,
		MessageInfos:      file_garm_tool_v1_invocation_proto_msgTypes,
	}.Build()
	File_garm_tool_v1_invocation_proto = out.File
	file_garm_tool_v1_invocation_proto_goTypes = nil
	file_garm_tool_v1_invocation_proto_depIdxs = nil
}
