// Annotation vocabulary for the tools server (tools spec §3).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: garm/tool/v1/tool.proto

package toolv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The enum number is the ordinal. Values are spaced by ten so a level can be
// inserted later; existing values must never be renumbered.
type Clearance int32

const (
	Clearance_CLEARANCE_UNSPECIFIED  Clearance = 0 // never a valid caller or field value
	Clearance_CLEARANCE_PUBLIC       Clearance = 10
	Clearance_CLEARANCE_INTERNAL     Clearance = 20
	Clearance_CLEARANCE_CONFIDENTIAL Clearance = 30
	Clearance_CLEARANCE_RESTRICTED   Clearance = 40
)

// Enum value maps for Clearance.
var (
	Clearance_name = map[int32]string{
		0:  "CLEARANCE_UNSPECIFIED",
		10: "CLEARANCE_PUBLIC",
		20: "CLEARANCE_INTERNAL",
		30: "CLEARANCE_CONFIDENTIAL",
		40: "CLEARANCE_RESTRICTED",
	}
	Clearance_value = map[string]int32{
		"CLEARANCE_UNSPECIFIED":  0,
		"CLEARANCE_PUBLIC":       10,
		"CLEARANCE_INTERNAL":     20,
		"CLEARANCE_CONFIDENTIAL": 30,
		"CLEARANCE_RESTRICTED":   40,
	}
)

func (x Clearance) Enum() *Clearance {
	p := new(Clearance)
	*p = x
	return p
}

func (x Clearance) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Clearance) Descriptor() protoreflect.EnumDescriptor {
	return file_garm_tool_v1_tool_proto_enumTypes[0].Descriptor()
}

func (Clearance) Type() protoreflect.EnumType {
	return &file_garm_tool_v1_tool_proto_enumTypes[0]
}

func (x Clearance) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Clearance.Descriptor instead.
func (Clearance) EnumDescriptor() ([]byte, []int) {
	return file_garm_tool_v1_tool_proto_rawDescGZIP(), []int{0}
}

type Verb int32

const (
	Verb_VERB_UNSPECIFIED Verb = 0
	Verb_VERB_READ        Verb = 1
	Verb_VERB_WRITE       Verb = 2
	Verb_VERB_DESTRUCTIVE Verb = 3
)

// Enum value maps for Verb.
var (
	Verb_name = map[int32]string{
		0: "VERB_UNSPECIFIED",
		1: "VERB_READ",
		2: "VERB_WRITE",
		3: "VERB_DESTRUCTIVE",
	}
	Verb_value = map[string]int32{
		"VERB_UNSPECIFIED": 0,
		"VERB_READ":        1,
		"VERB_WRITE":       2,
		"VERB_DESTRUCTIVE": 3,
	}
)

func (x Verb) Enum() *Verb {
	p := new(Verb)
	*p = x
	return p
}

func (x Verb) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Verb) Descriptor() protoreflect.EnumDescriptor {
	return file_garm_tool_v1_tool_proto_enumTypes[1].Descriptor()
}

func (Verb) Type() protoreflect.EnumType {
	return &file_garm_tool_v1_tool_proto_enumTypes[1]
}

func (x Verb) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Verb.Descriptor instead.
func (Verb) EnumDescriptor() ([]byte, []int) {
	return file_garm_tool_v1_tool_proto_rawDescGZIP(), []int{1}
}

// PrincipalKind says WHAT is calling, not what it may do.
//
// It is attribution, never authorization. Nothing in the chain reads it: the
// ten steps decide on clearance, compartments, verbs and tool sets, and
// adding a fifth vocabulary that can deny a call would mean two places to
// look when a call is refused. It exists because "which of these ledger rows
// were agents" is a question people ask constantly and cannot currently
// answer, and because the tool on the far side of the resolver is entitled
// to know whether a human is waiting on it.
//
// If gating on kind is ever wanted, it belongs in a declared field on
// ToolPolicy — reviewed like any other governance — not in an ad-hoc check.
type PrincipalKind int32

const (
	PrincipalKind_PRINCIPAL_KIND_UNSPECIFIED PrincipalKind = 0 // a token that did not say; attribution only, never a denial
	PrincipalKind_PRINCIPAL_KIND_USER        PrincipalKind = 1 // a person
	PrincipalKind_PRINCIPAL_KIND_AGENT       PrincipalKind = 2 // an autonomous loop acting for someone
	PrincipalKind_PRINCIPAL_KIND_SERVICE     PrincipalKind = 3 // a system calling on its own behalf
)

// Enum value maps for PrincipalKind.
var (
	PrincipalKind_name = map[int32]string{
		0: "PRINCIPAL_KIND_UNSPECIFIED",
		1: "PRINCIPAL_KIND_USER",
		2: "PRINCIPAL_KIND_AGENT",
		3: "PRINCIPAL_KIND_SERVICE",
	}
	PrincipalKind_value = map[string]int32{
		"PRINCIPAL_KIND_UNSPECIFIED": 0,
		"PRINCIPAL_KIND_USER":        1,
		"PRINCIPAL_KIND_AGENT":       2,
		"PRINCIPAL_KIND_SERVICE":     3,
	}
)

func (x PrincipalKind) Enum() *PrincipalKind {
	p := new(PrincipalKind)
	*p = x
	return p
}

func (x PrincipalKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrincipalKind) Descriptor() protoreflect.EnumDescriptor {
	return file_garm_tool_v1_tool_proto_enumTypes[2].Descriptor()
}

func (PrincipalKind) Type() protoreflect.EnumType {
	return &file_garm_tool_v1_tool_proto_enumTypes[2]
}

func (x PrincipalKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrincipalKind.Descriptor instead.
func (PrincipalKind) EnumDescriptor() ([]byte, []int) {
	return file_garm_tool_v1_tool_proto_rawDescGZIP(), []int{2}
}

type Reversibility int32

const (
	Reversibility_REVERSIBILITY_UNSPECIFIED Reversibility = 0 // fails closed to NONE
	Reversibility_REVERSIBILITY_NONE        Reversibility = 1
	Reversibility_REVERSIBILITY_COMPENSABLE Reversibility = 2
	Reversibility_REVERSIBILITY_FULL        Reversibility = 3
)

// Enum value maps for Reversibility.
var (
	Reversibility_name = map[int32]string{
		0: "REVERSIBILITY_UNSPECIFIED",
		1: "REVERSIBILITY_NONE",
		2: "REVERSIBILITY_COMPENSABLE",
		3: "REVERSIBILITY_FULL",
	}
	Reversibility_value = map[string]int32{
		"REVERSIBILITY_UNSPECIFIED": 0,
		"REVERSIBILITY_NONE":        1,
		"REVERSIBILITY_COMPENSABLE": 2,
		"REVERSIBILITY_FULL":        3,
	}
)

func (x Reversibility) Enum() *Reversibility {
	p := new(Reversibility)
	*p = x
	return p
}

func (x Reversibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Reversibility) Descriptor() protoreflect.EnumDescriptor {
	return file_garm_tool_v1_tool_proto_enumTypes[3].Descriptor()
}

func (Reversibility) Type() protoreflect.EnumType {
	return &file_garm_tool_v1_tool_proto_enumTypes[3]
}

func (x Reversibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Reversibility.Descriptor instead.
func (Reversibility) EnumDescriptor() ([]byte, []int) {
	return file_garm_tool_v1_tool_proto_rawDescGZIP(), []int{3}
}

type Grain int32

const (
	Grain_GRAIN_UNSPECIFIED Grain = 0
	Grain_GRAIN_DAY         Grain = 1
	Grain_GRAIN_MONTH       Grain = 2
	Grain_GRAIN_YEAR        Grain = 3
)

// Enum value maps for Grain.
var (
	Grain_name = map[int32]string{
		0: "GRAIN_UNSPECIFIED",
		1: "GRAIN_DAY",
		2: "GRAIN_MONTH",
		3: "GRAIN_YEAR",
	}
	Grain_value = map[string]int32{
		"GRAIN_UNSPECIFIED": 0,
		"GRAIN_DAY":         1,
		"GRAIN_MONTH":       2,
		"GRAIN_YEAR":        3,
	}
)

func (x Grain) Enum() *Grain {
	p := new(Grain)
	*p = x
	return p
}

func (x Grain) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Grain) Descriptor() protoreflect.EnumDescriptor {
	return file_garm_tool_v1_tool_proto_enumTypes[4].Descriptor()
}

func (Grain) Type() protoreflect.EnumType {
	return &file_garm_tool_v1_tool_proto_enumTypes[4]
}

func (x Grain) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Grain.Descriptor instead.
func (Grain) EnumDescriptor() ([]byte, []int) {
	return file_garm_tool_v1_tool_proto_rawDescGZIP(), []int{4}
}

type Approval_Mode int32

const (
	Approval_MODE_UNSPECIFIED Approval_Mode = 0
	Approval_MODE_NONE        Approval_Mode = 1
	Approval_MODE_NOTIFY      Approval_Mode = 2
	Approval_MODE_GRANT       Approval_Mode = 3
)

// Enum value maps for Approval_Mode.
var (
	Approval_Mode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "MODE_NONE",
		2: "MODE_NOTIFY",
		3: "MODE_GRANT",
	}
	Approval_Mode_value = map[string]int32{
		"MODE_UNSPECIFIED": 0,
		"MODE_NONE":        1,
		"MODE_NOTIFY":      2,
		"MODE_GRANT":       3,
	}
)

func (x Approval_Mode) Enum() *Approval_Mode {
	p := new(Approval_Mode)
	*p = x
	return p
}

func (x Approval_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Approval_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_garm_tool_v1_tool_proto_enumTypes[5].Descriptor()
}

func (Approval_Mode) Type() protoreflect.EnumType {
	return &file_garm_tool_v1_tool_proto_enumTypes[5]
}

func (x Approval_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Approval_Mode.Descriptor instead.
func (Approval_Mode) EnumDescriptor() ([]byte, []int) {
	return file_garm_tool_v1_tool_proto_rawDescGZIP(), []int{14, 0}
}

type Audit_Level int32

const (
	Audit_LEVEL_UNSPECIFIED Audit_Level = 0 // = LEVEL_LEDGER
	Audit_LEVEL_LEDGER      Audit_Level = 1
	Audit_LEVEL_AUDIT       Audit_Level = 2
)

// Enum value maps for Audit_Level.
var (
	Audit_Level_name = map[int32]string{
		0: "LEVEL_UNSPECIFIED",
		1: "LEVEL_LEDGER",
		2: "LEVEL_AUDIT",
	}
	Audit_Level_value = map[string]int32{
		"LEVEL_UNSPECIFIED": 0,
		"LEVEL_LEDGER":      1,
		"LEVEL_AUDIT":       2,
	}
)

func (x Audit_Level) Enum() *Audit_Level {
	p := new(Audit_Level)
	*p = x
	return p
}

func (x Audit_Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Audit_Level) Descriptor() protoreflect.EnumDescriptor {
	return file_garm_tool_v1_tool_proto_enumTypes[6].Descriptor()
}

func (Audit_Level) Type() protoreflect.EnumType {
	return &file_garm_tool_v1_tool_proto_enumTypes[6]
}

func (x Audit_Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Audit_Level.Descriptor instead.
func (Audit_Level) EnumDescriptor() ([]byte, []int) {
	return file_garm_tool_v1_tool_proto_rawDescGZIP(), []int{20, 0}
}

type Omit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Omit) Reset() {
	*x = Omit{}
	mi := &file_garm_tool_v1_tool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Omit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Omit) ProtoMessage() {}

func (x *Omit) ProtoReflect() protoreflect.Message {
	mi := &file_garm_tool_v1_tool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Omit.ProtoReflect.Descriptor instead.
func (*Omit) Descriptor() ([]byte, []int) {
	return file_garm_tool_v1_tool_proto_rawDescGZIP(), []int{0}
}

type Mask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	With          string                 `protobuf:"bytes,1,opt,name=with,proto3" json:"with,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mask) Reset() {
	*x = Mask{}
	mi := &file_garm_tool_v1_tool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mask) ProtoMessage() {}

func (x *Mask) ProtoReflect() protoreflect.Message {
	mi := &file_garm_tool_v1_tool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mask.ProtoReflect.Descriptor instead.
func (*Mask) Descriptor() ([]byte, []int) {
	return file_garm_tool_v1_tool_proto_rawDescGZIP(), []int{1}
}

func (x *Mask) GetWith() string {
	if x != nil {
		return x.With
	}
	return ""
}

type Hash struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PerTenantSalt bool                   `protobuf:"varint,1,opt,name=per_tenant_salt,json=perTenantSalt,proto3" json:"per_tenant_salt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hash) Reset() {
	*x = Hash{}
	mi := &file_garm_tool_v1_tool_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hash) ProtoMessage() {}

func (x *Hash) ProtoReflect() protoreflect.Message {
	mi := &file_garm_tool_v1_tool_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hash.ProtoReflect.Descriptor instead.
func (*Hash) Descriptor() ([]byte, []int) {
	return file_garm_tool_v1_tool_proto_rawDescGZIP(), []int{2}
}

func (x *Hash) GetPerTenantSalt() bool {
	if x != nil {
		return x.PerTenantSalt
	}
	return false
}

type EmailDomain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailDomain) Reset() {
	*x = EmailDomain{}
	mi := &file_garm_tool_v1_tool_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailDomain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailDomain) ProtoMessage() {}

func (x *EmailDomain) ProtoReflect() protoreflect.Message {
	mi := &file_garm_tool_v1_tool_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailDomain.ProtoReflect.Descriptor instead.
func (*EmailDomain) Descriptor() ([]byte, []int) {
	return file_garm_tool_v1_tool_proto_rawDescGZIP(), []int{3}
}

type KeepLast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	N             uint32                 `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	Runes         bool                   `protobuf:"varint,2,opt,name=runes,proto3" json:"runes,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepLast) Reset() {
	*x = KeepLast{}
	mi := &file_garm_tool_v1_tool_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepLast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepLast) ProtoMessage() {}

func (x *KeepLast) ProtoReflect() protoreflect.Message {
	mi := &file_garm_tool_v1_tool_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepLast.ProtoReflect.Descriptor instead.
func (*KeepLast) Descriptor() ([]byte, []int) {
	return file_garm_tool_v1_tool_proto_rawDescGZIP(), []int{4}
}

func (x *KeepLast) GetN() uint32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *KeepLast) GetRunes() bool {
	if x != nil {
		return x.Runes
	}
	return false
}

func (x *KeepLast) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Truncate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	N             uint32                 `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	Runes         bool                   `protobuf:"varint,2,opt,name=runes,proto3" json:"runes,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Truncate) Reset() {
	*x = Truncate{}
	mi := &file_garm_tool_v1_tool_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Truncate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Truncate) ProtoMessage() {}

func (x *Truncate) ProtoReflect() protoreflect.Message {
	mi := &file_garm_tool_v1_tool_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Truncate.ProtoReflect.Descriptor instead.
func (*Truncate) Descriptor() ([]byte, []int) {
	return file_garm_tool_v1_tool_proto_rawDescGZIP(), []int{5}
}

func (x *Truncate) GetN() uint32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *Truncate) GetRunes() bool {
	if x != nil {
		return x.Runes
	}
	return false
}

func (x *Truncate) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CardBinLast4 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardBinLast4) Reset() {
	*x = CardBinLast4{}
	mi := &file_garm_tool_v1_tool_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardBinLast4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardBinLast4) ProtoMessage() {}

func (x *CardBinLast4) ProtoReflect() protoreflect.Message {
	mi := &file_garm_tool_v1_tool_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardBinLast4.ProtoReflect.Descriptor instead.
func (*CardBinLast4) Descriptor() ([]byte, []int) {
	return file_garm_tool_v1_tool_proto_rawDescGZIP(), []int{6}
}

type IpPrefix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bits          uint32                 `protobuf:"varint,1,opt,name=bits,proto3" json:"bits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpPrefix) Reset() {
	*x = IpPrefix{}
	mi := &file_garm_tool_v1_tool_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpPrefix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpPrefix) ProtoMessage() {}

func (x *IpPrefix) ProtoReflect() protoreflect.Message {
	mi := &file_garm_tool_v1_tool_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpPrefix.ProtoReflect.Descriptor instead.
func (*IpPrefix) Descriptor() ([]byte, []int) {
	return file_garm_tool_v1_tool_proto_rawDescGZIP(), []int{7}
}

func (x *IpPrefix) GetBits() uint32 {
	if x != nil {
		return x.Bits
	}
	return 0
}

type UrlOrigin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UrlOrigin) Reset() {
	*x = UrlOrigin{}
	mi := &file_garm_tool_v1_tool_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UrlOrigin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlOrigin) ProtoMessage() {}

func (x *UrlOrigin) ProtoReflect() protoreflect.Message {
	mi := &file_garm_tool_v1_tool_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlOrigin.ProtoReflect.Descriptor instead.
func (*UrlOrigin) Descriptor() ([]byte, []int) {
	return file_garm_tool_v1_tool_proto_rawDescGZIP(), []int{8}
}

type DateGrain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grain         Grain                  `protobuf:"varint,1,opt,name=grain,proto3,enum=garm.tool.v1.Grain" json:"grain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateGrain) Reset() {
	*x = DateGrain{}
	mi := &file_garm_tool_v1_tool_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateGrain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateGrain) ProtoMessage() {}

func (x *DateGrain) ProtoReflect() protoreflect.Message {
	mi := &file_garm_tool_v1_tool_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateGrain.ProtoReflect.Descriptor instead.
func (*DateGrain) Descriptor() ([]byte, []int) {
	return file_garm_tool_v1_tool_proto_rawDescGZIP(), []int{9}
}

func (x *DateGrain) GetGrain() Grain {
	if x != nil {
		return x.Grain
	}
	return Grain_GRAIN_UNSPECIFIED
}

type Custom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Custom) Reset() {
	*x = Custom{}
	mi := &file_garm_tool_v1_tool_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Custom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Custom) ProtoMessage() {}

func (x *Custom) ProtoReflect() protoreflect.Message {
	mi := &file_garm_tool_v1_tool_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Custom.ProtoReflect.Descriptor instead.
func (*Custom) Descriptor() ([]byte, []int) {
	return file_garm_tool_v1_tool_proto_rawDescGZIP(), []int{10}
}

func (x *Custom) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Redaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Redaction_Omit
	//	*Redaction_Mask
	//	*Redaction_Hash
	//	*Redaction_EmailDomain
	//	*Redaction_KeepLast
	//	*Redaction_Truncate
	//	*Redaction_CardBinLast4
	//	*Redaction_IpPrefix
	//	*Redaction_UrlOrigin
	//	*Redaction_DateGrain
	//	*Redaction_Custom
	Kind          isRedaction_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Redaction) Reset() {
	*x = Redaction{}
	mi := &file_garm_tool_v1_tool_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Redaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Redaction) ProtoMessage() {}

func (x *Redaction) ProtoReflect() protoreflect.Message {
	mi := &file_garm_tool_v1_tool_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Redaction.ProtoReflect.Descriptor instead.
func (*Redaction) Descriptor() ([]byte, []int) {
	return file_garm_tool_v1_tool_proto_rawDescGZIP(), []int{11}
}

func (x *Redaction) GetKind() isRedaction_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Redaction) GetOmit() *Omit {
	if x != nil {
		if x, ok := x.Kind.(*Redaction_Omit); ok {
			return x.Omit
		}
	}
	return nil
}

func (x *Redaction) GetMask() *Mask {
	if x != nil {
		if x, ok := x.Kind.(*Redaction_Mask); ok {
			return x.Mask
		}
	}
	return nil
}

func (x *Redaction) GetHash() *Hash {
	if x != nil {
		if x, ok := x.Kind.(*Redaction_Hash); ok {
			return x.Hash
		}
	}
	return nil
}

func (x *Redaction) GetEmailDomain() *EmailDomain {
	if x != nil {
		if x, ok := x.Kind.(*Redaction_EmailDomain); ok {
			return x.EmailDomain
		}
	}
	return nil
}

func (x *Redaction) GetKeepLast() *KeepLast {
	if x != nil {
		if x, ok := x.Kind.(*Redaction_KeepLast); ok {
			return x.KeepLast
		}
	}
	return nil
}

func (x *Redaction) GetTruncate() *Truncate {
	if x != nil {
		if x, ok := x.Kind.(*Redaction_Truncate); ok {
			return x.Truncate
		}
	}
	return nil
}

func (x *Redaction) GetCardBinLast4() *CardBinLast4 {
	if x != nil {
		if x, ok := x.Kind.(*Redaction_CardBinLast4); ok {
			return x.CardBinLast4
		}
	}
	return nil
}

func (x *Redaction) GetIpPrefix() *IpPrefix {
	if x != nil {
		if x, ok := x.Kind.(*Redaction_IpPrefix); ok {
			return x.IpPrefix
		}
	}
	return nil
}

func (x *Redaction) GetUrlOrigin() *UrlOrigin {
	if x != nil {
		if x, ok := x.Kind.(*Redaction_UrlOrigin); ok {
			return x.UrlOrigin
		}
	}
	return nil
}

func (x *Redaction) GetDateGrain() *DateGrain {
	if x != nil {
		if x, ok := x.Kind.(*Redaction_DateGrain); ok {
			return x.DateGrain
		}
	}
	return nil
}

func (x *Redaction) GetCustom() *Custom {
	if x != nil {
		if x, ok := x.Kind.(*Redaction_Custom); ok {
			return x.Custom
		}
	}
	return nil
}

type isRedaction_Kind interface {
	isRedaction_Kind()
}

type Redaction_Omit struct {
	Omit *Omit `protobuf:"bytes,1,opt,name=omit,proto3,oneof"`
}

type Redaction_Mask struct {
	Mask *Mask `protobuf:"bytes,2,opt,name=mask,proto3,oneof"`
}

type Redaction_Hash struct {
	Hash *Hash `protobuf:"bytes,3,opt,name=hash,proto3,oneof"`
}

type Redaction_EmailDomain struct {
	EmailDomain *EmailDomain `protobuf:"bytes,4,opt,name=email_domain,json=emailDomain,proto3,oneof"`
}

type Redaction_KeepLast struct {
	KeepLast *KeepLast `protobuf:"bytes,5,opt,name=keep_last,json=keepLast,proto3,oneof"`
}

type Redaction_Truncate struct {
	Truncate *Truncate `protobuf:"bytes,6,opt,name=truncate,proto3,oneof"`
}

type Redaction_CardBinLast4 struct {
	CardBinLast4 *CardBinLast4 `protobuf:"bytes,7,opt,name=card_bin_last4,json=cardBinLast4,proto3,oneof"`
}

type Redaction_IpPrefix struct {
	IpPrefix *IpPrefix `protobuf:"bytes,8,opt,name=ip_prefix,json=ipPrefix,proto3,oneof"`
}

type Redaction_UrlOrigin struct {
	UrlOrigin *UrlOrigin `protobuf:"bytes,9,opt,name=url_origin,json=urlOrigin,proto3,oneof"`
}

type Redaction_DateGrain struct {
	DateGrain *DateGrain `protobuf:"bytes,10,opt,name=date_grain,json=dateGrain,proto3,oneof"`
}

type Redaction_Custom struct {
	Custom *Custom `protobuf:"bytes,15,opt,name=custom,proto3,oneof"`
}

func (*Redaction_Omit) isRedaction_Kind() {}

func (*Redaction_Mask) isRedaction_Kind() {}

func (*Redaction_Hash) isRedaction_Kind() {}

func (*Redaction_EmailDomain) isRedaction_Kind() {}

func (*Redaction_KeepLast) isRedaction_Kind() {}

func (*Redaction_Truncate) isRedaction_Kind() {}

func (*Redaction_CardBinLast4) isRedaction_Kind() {}

func (*Redaction_IpPrefix) isRedaction_Kind() {}

func (*Redaction_UrlOrigin) isRedaction_Kind() {}

func (*Redaction_DateGrain) isRedaction_Kind() {}

func (*Redaction_Custom) isRedaction_Kind() {}

type FieldPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Read          Clearance              `protobuf:"varint,1,opt,name=read,proto3,enum=garm.tool.v1.Clearance" json:"read,omitempty"`
	Write         Clearance              `protobuf:"varint,2,opt,name=write,proto3,enum=garm.tool.v1.Clearance" json:"write,omitempty"` // unset = same as read
	Compartments  []string               `protobuf:"bytes,3,rep,name=compartments,proto3" json:"compartments,omitempty"`
	OnDeny        *Redaction             `protobuf:"bytes,4,opt,name=on_deny,json=onDeny,proto3" json:"on_deny,omitempty"` // unset = omit
	AuditOnRead   bool                   `protobuf:"varint,5,opt,name=audit_on_read,json=auditOnRead,proto3" json:"audit_on_read,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldPolicy) Reset() {
	*x = FieldPolicy{}
	mi := &file_garm_tool_v1_tool_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldPolicy) ProtoMessage() {}

func (x *FieldPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_garm_tool_v1_tool_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldPolicy.ProtoReflect.Descriptor instead.
func (*FieldPolicy) Descriptor() ([]byte, []int) {
	return file_garm_tool_v1_tool_proto_rawDescGZIP(), []int{12}
}

func (x *FieldPolicy) GetRead() Clearance {
	if x != nil {
		return x.Read
	}
	return Clearance_CLEARANCE_UNSPECIFIED
}

func (x *FieldPolicy) GetWrite() Clearance {
	if x != nil {
		return x.Write
	}
	return Clearance_CLEARANCE_UNSPECIFIED
}

func (x *FieldPolicy) GetCompartments() []string {
	if x != nil {
		return x.Compartments
	}
	return nil
}

func (x *FieldPolicy) GetOnDeny() *Redaction {
	if x != nil {
		return x.OnDeny
	}
	return nil
}

func (x *FieldPolicy) GetAuditOnRead() bool {
	if x != nil {
		return x.AuditOnRead
	}
	return false
}

type Effects struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Idempotent       bool                   `protobuf:"varint,1,opt,name=idempotent,proto3" json:"idempotent,omitempty"`
	Reversibility    Reversibility          `protobuf:"varint,2,opt,name=reversibility,proto3,enum=garm.tool.v1.Reversibility" json:"reversibility,omitempty"`
	External         bool                   `protobuf:"varint,3,opt,name=external,proto3" json:"external,omitempty"`
	CompensatingTool string                 `protobuf:"bytes,4,opt,name=compensating_tool,json=compensatingTool,proto3" json:"compensating_tool,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Effects) Reset() {
	*x = Effects{}
	mi := &file_garm_tool_v1_tool_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effects) ProtoMessage() {}

func (x *Effects) ProtoReflect() protoreflect.Message {
	mi := &file_garm_tool_v1_tool_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effects.ProtoReflect.Descriptor instead.
func (*Effects) Descriptor() ([]byte, []int) {
	return file_garm_tool_v1_tool_proto_rawDescGZIP(), []int{13}
}

func (x *Effects) GetIdempotent() bool {
	if x != nil {
		return x.Idempotent
	}
	return false
}

func (x *Effects) GetReversibility() Reversibility {
	if x != nil {
		return x.Reversibility
	}
	return Reversibility_REVERSIBILITY_UNSPECIFIED
}

func (x *Effects) GetExternal() bool {
	if x != nil {
		return x.External
	}
	return false
}

func (x *Effects) GetCompensatingTool() string {
	if x != nil {
		return x.CompensatingTool
	}
	return ""
}

type Approval struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Mode                 Approval_Mode          `protobuf:"varint,1,opt,name=mode,proto3,enum=garm.tool.v1.Approval_Mode" json:"mode,omitempty"`
	ApproverMinClearance Clearance              `protobuf:"varint,2,opt,name=approver_min_clearance,json=approverMinClearance,proto3,enum=garm.tool.v1.Clearance" json:"approver_min_clearance,omitempty"`
	ApproverCompartments []string               `protobuf:"bytes,3,rep,name=approver_compartments,json=approverCompartments,proto3" json:"approver_compartments,omitempty"`
	MaxGrantAgeSeconds   uint32                 `protobuf:"varint,4,opt,name=max_grant_age_seconds,json=maxGrantAgeSeconds,proto3" json:"max_grant_age_seconds,omitempty"`
	Notes                string                 `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Approval) Reset() {
	*x = Approval{}
	mi := &file_garm_tool_v1_tool_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Approval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Approval) ProtoMessage() {}

func (x *Approval) ProtoReflect() protoreflect.Message {
	mi := &file_garm_tool_v1_tool_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Approval.ProtoReflect.Descriptor instead.
func (*Approval) Descriptor() ([]byte, []int) {
	return file_garm_tool_v1_tool_proto_rawDescGZIP(), []int{14}
}

func (x *Approval) GetMode() Approval_Mode {
	if x != nil {
		return x.Mode
	}
	return Approval_MODE_UNSPECIFIED
}

func (x *Approval) GetApproverMinClearance() Clearance {
	if x != nil {
		return x.ApproverMinClearance
	}
	return Clearance_CLEARANCE_UNSPECIFIED
}

func (x *Approval) GetApproverCompartments() []string {
	if x != nil {
		return x.ApproverCompartments
	}
	return nil
}

func (x *Approval) GetMaxGrantAgeSeconds() uint32 {
	if x != nil {
		return x.MaxGrantAgeSeconds
	}
	return 0
}

func (x *Approval) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type Example struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	RequestJson   string                 `protobuf:"bytes,2,opt,name=request_json,json=requestJson,proto3" json:"request_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Example) Reset() {
	*x = Example{}
	mi := &file_garm_tool_v1_tool_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Example) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Example) ProtoMessage() {}

func (x *Example) ProtoReflect() protoreflect.Message {
	mi := &file_garm_tool_v1_tool_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Example.ProtoReflect.Descriptor instead.
func (*Example) Descriptor() ([]byte, []int) {
	return file_garm_tool_v1_tool_proto_rawDescGZIP(), []int{15}
}

func (x *Example) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Example) GetRequestJson() string {
	if x != nil {
		return x.RequestJson
	}
	return ""
}

type Guidance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WhenToUse     string                 `protobuf:"bytes,1,opt,name=when_to_use,json=whenToUse,proto3" json:"when_to_use,omitempty"`
	WhenNotToUse  string                 `protobuf:"bytes,2,opt,name=when_not_to_use,json=whenNotToUse,proto3" json:"when_not_to_use,omitempty"`
	Examples      []*Example             `protobuf:"bytes,3,rep,name=examples,proto3" json:"examples,omitempty"`
	OnError       string                 `protobuf:"bytes,4,opt,name=on_error,json=onError,proto3" json:"on_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Guidance) Reset() {
	*x = Guidance{}
	mi := &file_garm_tool_v1_tool_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Guidance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guidance) ProtoMessage() {}

func (x *Guidance) ProtoReflect() protoreflect.Message {
	mi := &file_garm_tool_v1_tool_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guidance.ProtoReflect.Descriptor instead.
func (*Guidance) Descriptor() ([]byte, []int) {
	return file_garm_tool_v1_tool_proto_rawDescGZIP(), []int{16}
}

func (x *Guidance) GetWhenToUse() string {
	if x != nil {
		return x.WhenToUse
	}
	return ""
}

func (x *Guidance) GetWhenNotToUse() string {
	if x != nil {
		return x.WhenNotToUse
	}
	return ""
}

func (x *Guidance) GetExamples() []*Example {
	if x != nil {
		return x.Examples
	}
	return nil
}

func (x *Guidance) GetOnError() string {
	if x != nil {
		return x.OnError
	}
	return ""
}

type ListFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepeatedField string                 `protobuf:"bytes,1,opt,name=repeated_field,json=repeatedField,proto3" json:"repeated_field,omitempty"`
	IdField       string                 `protobuf:"bytes,2,opt,name=id_field,json=idField,proto3" json:"id_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilter) Reset() {
	*x = ListFilter{}
	mi := &file_garm_tool_v1_tool_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilter) ProtoMessage() {}

func (x *ListFilter) ProtoReflect() protoreflect.Message {
	mi := &file_garm_tool_v1_tool_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilter.ProtoReflect.Descriptor instead.
func (*ListFilter) Descriptor() ([]byte, []int) {
	return file_garm_tool_v1_tool_proto_rawDescGZIP(), []int{17}
}

func (x *ListFilter) GetRepeatedField() string {
	if x != nil {
		return x.RepeatedField
	}
	return ""
}

func (x *ListFilter) GetIdField() string {
	if x != nil {
		return x.IdField
	}
	return ""
}

type Fga struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Relation   string                 `protobuf:"bytes,1,opt,name=relation,proto3" json:"relation,omitempty"`
	ObjectType string                 `protobuf:"bytes,2,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// Types that are valid to be assigned to Object:
	//
	//	*Fga_FromRequestField
	//	*Fga_FromResponseField
	//	*Fga_FilterResponse
	Object        isFga_Object `protobuf_oneof:"object"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fga) Reset() {
	*x = Fga{}
	mi := &file_garm_tool_v1_tool_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fga) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fga) ProtoMessage() {}

func (x *Fga) ProtoReflect() protoreflect.Message {
	mi := &file_garm_tool_v1_tool_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fga.ProtoReflect.Descriptor instead.
func (*Fga) Descriptor() ([]byte, []int) {
	return file_garm_tool_v1_tool_proto_rawDescGZIP(), []int{18}
}

func (x *Fga) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *Fga) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *Fga) GetObject() isFga_Object {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *Fga) GetFromRequestField() string {
	if x != nil {
		if x, ok := x.Object.(*Fga_FromRequestField); ok {
			return x.FromRequestField
		}
	}
	return ""
}

func (x *Fga) GetFromResponseField() string {
	if x != nil {
		if x, ok := x.Object.(*Fga_FromResponseField); ok {
			return x.FromResponseField
		}
	}
	return ""
}

func (x *Fga) GetFilterResponse() *ListFilter {
	if x != nil {
		if x, ok := x.Object.(*Fga_FilterResponse); ok {
			return x.FilterResponse
		}
	}
	return nil
}

type isFga_Object interface {
	isFga_Object()
}

type Fga_FromRequestField struct {
	FromRequestField string `protobuf:"bytes,3,opt,name=from_request_field,json=fromRequestField,proto3,oneof"`
}

type Fga_FromResponseField struct {
	FromResponseField string `protobuf:"bytes,4,opt,name=from_response_field,json=fromResponseField,proto3,oneof"`
}

type Fga_FilterResponse struct {
	FilterResponse *ListFilter `protobuf:"bytes,5,opt,name=filter_response,json=filterResponse,proto3,oneof"`
}

func (*Fga_FromRequestField) isFga_Object() {}

func (*Fga_FromResponseField) isFga_Object() {}

func (*Fga_FilterResponse) isFga_Object() {}

type Authorization struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Backend:
	//
	//	*Authorization_Fga
	Backend       isAuthorization_Backend `protobuf_oneof:"backend"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authorization) Reset() {
	*x = Authorization{}
	mi := &file_garm_tool_v1_tool_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authorization) ProtoMessage() {}

func (x *Authorization) ProtoReflect() protoreflect.Message {
	mi := &file_garm_tool_v1_tool_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authorization.ProtoReflect.Descriptor instead.
func (*Authorization) Descriptor() ([]byte, []int) {
	return file_garm_tool_v1_tool_proto_rawDescGZIP(), []int{19}
}

func (x *Authorization) GetBackend() isAuthorization_Backend {
	if x != nil {
		return x.Backend
	}
	return nil
}

func (x *Authorization) GetFga() *Fga {
	if x != nil {
		if x, ok := x.Backend.(*Authorization_Fga); ok {
			return x.Fga
		}
	}
	return nil
}

type isAuthorization_Backend interface {
	isAuthorization_Backend()
}

type Authorization_Fga struct {
	Fga *Fga `protobuf:"bytes,1,opt,name=fga,proto3,oneof"`
}

func (*Authorization_Fga) isAuthorization_Backend() {}

type Audit struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Level          Audit_Level            `protobuf:"varint,1,opt,name=level,proto3,enum=garm.tool.v1.Audit_Level" json:"level,omitempty"`
	RecordRequest  bool                   `protobuf:"varint,2,opt,name=record_request,json=recordRequest,proto3" json:"record_request,omitempty"`
	RecordResponse bool                   `protobuf:"varint,3,opt,name=record_response,json=recordResponse,proto3" json:"record_response,omitempty"`
	RetainDays     uint32                 `protobuf:"varint,4,opt,name=retain_days,json=retainDays,proto3" json:"retain_days,omitempty"`
	FailClosed     bool                   `protobuf:"varint,5,opt,name=fail_closed,json=failClosed,proto3" json:"fail_closed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Audit) Reset() {
	*x = Audit{}
	mi := &file_garm_tool_v1_tool_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Audit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Audit) ProtoMessage() {}

func (x *Audit) ProtoReflect() protoreflect.Message {
	mi := &file_garm_tool_v1_tool_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Audit.ProtoReflect.Descriptor instead.
func (*Audit) Descriptor() ([]byte, []int) {
	return file_garm_tool_v1_tool_proto_rawDescGZIP(), []int{20}
}

func (x *Audit) GetLevel() Audit_Level {
	if x != nil {
		return x.Level
	}
	return Audit_LEVEL_UNSPECIFIED
}

func (x *Audit) GetRecordRequest() bool {
	if x != nil {
		return x.RecordRequest
	}
	return false
}

func (x *Audit) GetRecordResponse() bool {
	if x != nil {
		return x.RecordResponse
	}
	return false
}

func (x *Audit) GetRetainDays() uint32 {
	if x != nil {
		return x.RetainDays
	}
	return 0
}

func (x *Audit) GetFailClosed() bool {
	if x != nil {
		return x.FailClosed
	}
	return false
}

type ToolPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Verb          Verb                   `protobuf:"varint,4,opt,name=verb,proto3,enum=garm.tool.v1.Verb" json:"verb,omitempty"`
	MinClearance  Clearance              `protobuf:"varint,5,opt,name=min_clearance,json=minClearance,proto3,enum=garm.tool.v1.Clearance" json:"min_clearance,omitempty"`
	Compartments  []string               `protobuf:"bytes,6,rep,name=compartments,proto3" json:"compartments,omitempty"`
	Exclude       bool                   `protobuf:"varint,7,opt,name=exclude,proto3" json:"exclude,omitempty"`
	Effects       *Effects               `protobuf:"bytes,8,opt,name=effects,proto3" json:"effects,omitempty"`
	Approval      *Approval              `protobuf:"bytes,9,opt,name=approval,proto3" json:"approval,omitempty"`
	Guidance      *Guidance              `protobuf:"bytes,10,opt,name=guidance,proto3" json:"guidance,omitempty"`
	Authorization *Authorization         `protobuf:"bytes,11,opt,name=authorization,proto3" json:"authorization,omitempty"`
	Sets          []string               `protobuf:"bytes,12,rep,name=sets,proto3" json:"sets,omitempty"`
	Audit         *Audit                 `protobuf:"bytes,13,opt,name=audit,proto3" json:"audit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolPolicy) Reset() {
	*x = ToolPolicy{}
	mi := &file_garm_tool_v1_tool_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolPolicy) ProtoMessage() {}

func (x *ToolPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_garm_tool_v1_tool_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolPolicy.ProtoReflect.Descriptor instead.
func (*ToolPolicy) Descriptor() ([]byte, []int) {
	return file_garm_tool_v1_tool_proto_rawDescGZIP(), []int{21}
}

func (x *ToolPolicy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolPolicy) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ToolPolicy) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolPolicy) GetVerb() Verb {
	if x != nil {
		return x.Verb
	}
	return Verb_VERB_UNSPECIFIED
}

func (x *ToolPolicy) GetMinClearance() Clearance {
	if x != nil {
		return x.MinClearance
	}
	return Clearance_CLEARANCE_UNSPECIFIED
}

func (x *ToolPolicy) GetCompartments() []string {
	if x != nil {
		return x.Compartments
	}
	return nil
}

func (x *ToolPolicy) GetExclude() bool {
	if x != nil {
		return x.Exclude
	}
	return false
}

func (x *ToolPolicy) GetEffects() *Effects {
	if x != nil {
		return x.Effects
	}
	return nil
}

func (x *ToolPolicy) GetApproval() *Approval {
	if x != nil {
		return x.Approval
	}
	return nil
}

func (x *ToolPolicy) GetGuidance() *Guidance {
	if x != nil {
		return x.Guidance
	}
	return nil
}

func (x *ToolPolicy) GetAuthorization() *Authorization {
	if x != nil {
		return x.Authorization
	}
	return nil
}

func (x *ToolPolicy) GetSets() []string {
	if x != nil {
		return x.Sets
	}
	return nil
}

func (x *ToolPolicy) GetAudit() *Audit {
	if x != nil {
		return x.Audit
	}
	return nil
}

type Decl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decl) Reset() {
	*x = Decl{}
	mi := &file_garm_tool_v1_tool_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decl) ProtoMessage() {}

func (x *Decl) ProtoReflect() protoreflect.Message {
	mi := &file_garm_tool_v1_tool_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decl.ProtoReflect.Descriptor instead.
func (*Decl) Descriptor() ([]byte, []int) {
	return file_garm_tool_v1_tool_proto_rawDescGZIP(), []int{22}
}

func (x *Decl) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Decl) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DeclSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Declared      []*Decl                `protobuf:"bytes,1,rep,name=declared,proto3" json:"declared,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclSet) Reset() {
	*x = DeclSet{}
	mi := &file_garm_tool_v1_tool_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclSet) ProtoMessage() {}

func (x *DeclSet) ProtoReflect() protoreflect.Message {
	mi := &file_garm_tool_v1_tool_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclSet.ProtoReflect.Descriptor instead.
func (*DeclSet) Descriptor() ([]byte, []int) {
	return file_garm_tool_v1_tool_proto_rawDescGZIP(), []int{23}
}

func (x *DeclSet) GetDeclared() []*Decl {
	if x != nil {
		return x.Declared
	}
	return nil
}

var file_garm_tool_v1_tool_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldPolicy)(nil),
		Field:         50001,
		Name:          "garm.tool.v1.field_policy",
		Tag:           "bytes,50001,opt,name=field_policy",
		Filename:      "garm/tool/v1/tool.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*ToolPolicy)(nil),
		Field:         50002,
		Name:          "garm.tool.v1.tool",
		Tag:           "bytes,50002,opt,name=tool",
		Filename:      "garm/tool/v1/tool.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*FieldPolicy)(nil),
		Field:         50003,
		Name:          "garm.tool.v1.default_field_policy",
		Tag:           "bytes,50003,opt,name=default_field_policy",
		Filename:      "garm/tool/v1/tool.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*DeclSet)(nil),
		Field:         50004,
		Name:          "garm.tool.v1.compartments",
		Tag:           "bytes,50004,opt,name=compartments",
		Filename:      "garm/tool/v1/tool.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*DeclSet)(nil),
		Field:         50005,
		Name:          "garm.tool.v1.tool_sets",
		Tag:           "bytes,50005,opt,name=tool_sets",
		Filename:      "garm/tool/v1/tool.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional garm.tool.v1.FieldPolicy field_policy = 50001;
	E_FieldPolicy = &file_garm_tool_v1_tool_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional garm.tool.v1.ToolPolicy tool = 50002;
	E_Tool = &file_garm_tool_v1_tool_proto_extTypes[1]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional garm.tool.v1.FieldPolicy default_field_policy = 50003;
	E_DefaultFieldPolicy = &file_garm_tool_v1_tool_proto_extTypes[2]
)

// Extension fields to descriptorpb.FileOptions.
var (
	// optional garm.tool.v1.DeclSet compartments = 50004;
	E_Compartments = &file_garm_tool_v1_tool_proto_extTypes[3]
	// optional garm.tool.v1.DeclSet tool_sets = 50005;
	E_ToolSets = &file_garm_tool_v1_tool_proto_extTypes[4]
)

var File_garm_tool_v1_tool_proto protoreflect.FileDescriptor

const file_garm_tool_v1_tool_proto_rawDesc = "" +
	"\n" +
	"\x17garm/tool/v1/tool.proto\x12\fgarm.tool.v1\x1a google/protobuf/descriptor.proto\"\x06\n" +
	"\x04Omit\"\x1a\n" +
	"\x04Mask\x12\x12\n" +
	"\x04with\x18\x01 \x01(\tR\x04with\".\n" +
	"\x04Hash\x12&\n" +
	"\x0fper_tenant_salt\x18\x01 \x01(\bR\rperTenantSalt\"\r\n" +
	"\vEmailDomain\"F\n" +
	"\bKeepLast\x12\f\n" +
	"\x01n\x18\x01 \x01(\rR\x01n\x12\x14\n" +
	"\x05runes\x18\x02 \x01(\bR\x05runes\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"F\n" +
	"\bTruncate\x12\f\n" +
	"\x01n\x18\x01 \x01(\rR\x01n\x12\x14\n" +
	"\x05runes\x18\x02 \x01(\bR\x05runes\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x0e\n" +
	"\fCardBinLast4\"\x1e\n" +
	"\bIpPrefix\x12\x12\n" +
	"\x04bits\x18\x01 \x01(\rR\x04bits\"\v\n" +
	"\tUrlOrigin\"6\n" +
	"\tDateGrain\x12)\n" +
	"\x05grain\x18\x01 \x01(\x0e2\x13.garm.tool.v1.GrainR\x05grain\"\x1c\n" +
	"\x06Custom\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xdd\x04\n" +
	"\tRedaction\x12(\n" +
	"\x04omit\x18\x01 \x01(\v2\x12.garm.tool.v1.OmitH\x00R\x04omit\x12(\n" +
	"\x04mask\x18\x02 \x01(\v2\x12.garm.tool.v1.MaskH\x00R\x04mask\x12(\n" +
	"\x04hash\x18\x03 \x01(\v2\x12.garm.tool.v1.HashH\x00R\x04hash\x12>\n" +
	"\femail_domain\x18\x04 \x01(\v2\x19.garm.tool.v1.EmailDomainH\x00R\vemailDomain\x125\n" +
	"\tkeep_last\x18\x05 \x01(\v2\x16.garm.tool.v1.KeepLastH\x00R\bkeepLast\x124\n" +
	"\btruncate\x18\x06 \x01(\v2\x16.garm.tool.v1.TruncateH\x00R\btruncate\x12B\n" +
	"\x0ecard_bin_last4\x18\a \x01(\v2\x1a.garm.tool.v1.CardBinLast4H\x00R\fcardBinLast4\x125\n" +
	"\tip_prefix\x18\b \x01(\v2\x16.garm.tool.v1.IpPrefixH\x00R\bipPrefix\x128\n" +
	"\n" +
	"url_origin\x18\t \x01(\v2\x17.garm.tool.v1.UrlOriginH\x00R\turlOrigin\x128\n" +
	"\n" +
	"date_grain\x18\n" +
	" \x01(\v2\x17.garm.tool.v1.DateGrainH\x00R\tdateGrain\x12.\n" +
	"\x06custom\x18\x0f \x01(\v2\x14.garm.tool.v1.CustomH\x00R\x06customB\x06\n" +
	"\x04kind\"\xe3\x01\n" +
	"\vFieldPolicy\x12+\n" +
	"\x04read\x18\x01 \x01(\x0e2\x17.garm.tool.v1.ClearanceR\x04read\x12-\n" +
	"\x05write\x18\x02 \x01(\x0e2\x17.garm.tool.v1.ClearanceR\x05write\x12\"\n" +
	"\fcompartments\x18\x03 \x03(\tR\fcompartments\x120\n" +
	"\aon_deny\x18\x04 \x01(\v2\x17.garm.tool.v1.RedactionR\x06onDeny\x12\"\n" +
	"\raudit_on_read\x18\x05 \x01(\bR\vauditOnRead\"\xb5\x01\n" +
	"\aEffects\x12\x1e\n" +
	"\n" +
	"idempotent\x18\x01 \x01(\bR\n" +
	"idempotent\x12A\n" +
	"\rreversibility\x18\x02 \x01(\x0e2\x1b.garm.tool.v1.ReversibilityR\rreversibility\x12\x1a\n" +
	"\bexternal\x18\x03 \x01(\bR\bexternal\x12+\n" +
	"\x11compensating_tool\x18\x04 \x01(\tR\x10compensatingTool\"\xd6\x02\n" +
	"\bApproval\x12/\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x1b.garm.tool.v1.Approval.ModeR\x04mode\x12M\n" +
	"\x16approver_min_clearance\x18\x02 \x01(\x0e2\x17.garm.tool.v1.ClearanceR\x14approverMinClearance\x123\n" +
	"\x15approver_compartments\x18\x03 \x03(\tR\x14approverCompartments\x121\n" +
	"\x15max_grant_age_seconds\x18\x04 \x01(\rR\x12maxGrantAgeSeconds\x12\x14\n" +
	"\x05notes\x18\x05 \x01(\tR\x05notes\"L\n" +
	"\x04Mode\x12\x14\n" +
	"\x10MODE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tMODE_NONE\x10\x01\x12\x0f\n" +
	"\vMODE_NOTIFY\x10\x02\x12\x0e\n" +
	"\n" +
	"MODE_GRANT\x10\x03\"N\n" +
	"\aExample\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12!\n" +
	"\frequest_json\x18\x02 \x01(\tR\vrequestJson\"\x9f\x01\n" +
	"\bGuidance\x12\x1e\n" +
	"\vwhen_to_use\x18\x01 \x01(\tR\twhenToUse\x12%\n" +
	"\x0fwhen_not_to_use\x18\x02 \x01(\tR\fwhenNotToUse\x121\n" +
	"\bexamples\x18\x03 \x03(\v2\x15.garm.tool.v1.ExampleR\bexamples\x12\x19\n" +
	"\bon_error\x18\x04 \x01(\tR\aonError\"N\n" +
	"\n" +
	"ListFilter\x12%\n" +
	"\x0erepeated_field\x18\x01 \x01(\tR\rrepeatedField\x12\x19\n" +
	"\bid_field\x18\x02 \x01(\tR\aidField\"\xf3\x01\n" +
	"\x03Fga\x12\x1a\n" +
	"\brelation\x18\x01 \x01(\tR\brelation\x12\x1f\n" +
	"\vobject_type\x18\x02 \x01(\tR\n" +
	"objectType\x12.\n" +
	"\x12from_request_field\x18\x03 \x01(\tH\x00R\x10fromRequestField\x120\n" +
	"\x13from_response_field\x18\x04 \x01(\tH\x00R\x11fromResponseField\x12C\n" +
	"\x0ffilter_response\x18\x05 \x01(\v2\x18.garm.tool.v1.ListFilterH\x00R\x0efilterResponseB\b\n" +
	"\x06object\"A\n" +
	"\rAuthorization\x12%\n" +
	"\x03fga\x18\x01 \x01(\v2\x11.garm.tool.v1.FgaH\x00R\x03fgaB\t\n" +
	"\abackend\"\x8d\x02\n" +
	"\x05Audit\x12/\n" +
	"\x05level\x18\x01 \x01(\x0e2\x19.garm.tool.v1.Audit.LevelR\x05level\x12%\n" +
	"\x0erecord_request\x18\x02 \x01(\bR\rrecordRequest\x12'\n" +
	"\x0frecord_response\x18\x03 \x01(\bR\x0erecordResponse\x12\x1f\n" +
	"\vretain_days\x18\x04 \x01(\rR\n" +
	"retainDays\x12\x1f\n" +
	"\vfail_closed\x18\x05 \x01(\bR\n" +
	"failClosed\"A\n" +
	"\x05Level\x12\x15\n" +
	"\x11LEVEL_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fLEVEL_LEDGER\x10\x01\x12\x0f\n" +
	"\vLEVEL_AUDIT\x10\x02\"\x97\x04\n" +
	"\n" +
	"ToolPolicy\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12&\n" +
	"\x04verb\x18\x04 \x01(\x0e2\x12.garm.tool.v1.VerbR\x04verb\x12<\n" +
	"\rmin_clearance\x18\x05 \x01(\x0e2\x17.garm.tool.v1.ClearanceR\fminClearance\x12\"\n" +
	"\fcompartments\x18\x06 \x03(\tR\fcompartments\x12\x18\n" +
	"\aexclude\x18\a \x01(\bR\aexclude\x12/\n" +
	"\aeffects\x18\b \x01(\v2\x15.garm.tool.v1.EffectsR\aeffects\x122\n" +
	"\bapproval\x18\t \x01(\v2\x16.garm.tool.v1.ApprovalR\bapproval\x122\n" +
	"\bguidance\x18\n" +
	" \x01(\v2\x16.garm.tool.v1.GuidanceR\bguidance\x12A\n" +
	"\rauthorization\x18\v \x01(\v2\x1b.garm.tool.v1.AuthorizationR\rauthorization\x12\x12\n" +
	"\x04sets\x18\f \x03(\tR\x04sets\x12)\n" +
	"\x05audit\x18\r \x01(\v2\x13.garm.tool.v1.AuditR\x05audit\"<\n" +
	"\x04Decl\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"9\n" +
	"\aDeclSet\x12.\n" +
	"\bdeclared\x18\x01 \x03(\v2\x12.garm.tool.v1.DeclR\bdeclared*\x8a\x01\n" +
	"\tClearance\x12\x19\n" +
	"\x15CLEARANCE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10CLEARANCE_PUBLIC\x10\n" +
	"\x12\x16\n" +
	"\x12CLEARANCE_INTERNAL\x10\x14\x12\x1a\n" +
	"\x16CLEARANCE_CONFIDENTIAL\x10\x1e\x12\x18\n" +
	"\x14CLEARANCE_RESTRICTED\x10(*Q\n" +
	"\x04Verb\x12\x14\n" +
	"\x10VERB_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tVERB_READ\x10\x01\x12\x0e\n" +
	"\n" +
	"VERB_WRITE\x10\x02\x12\x14\n" +
	"\x10VERB_DESTRUCTIVE\x10\x03*~\n" +
	"\rPrincipalKind\x12\x1e\n" +
	"\x1aPRINCIPAL_KIND_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13PRINCIPAL_KIND_USER\x10\x01\x12\x18\n" +
	"\x14PRINCIPAL_KIND_AGENT\x10\x02\x12\x1a\n" +
	"\x16PRINCIPAL_KIND_SERVICE\x10\x03*}\n" +
	"\rReversibility\x12\x1d\n" +
	"\x19REVERSIBILITY_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12REVERSIBILITY_NONE\x10\x01\x12\x1d\n" +
	"\x19REVERSIBILITY_COMPENSABLE\x10\x02\x12\x16\n" +
	"\x12REVERSIBILITY_FULL\x10\x03*N\n" +
	"\x05Grain\x12\x15\n" +
	"\x11GRAIN_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tGRAIN_DAY\x10\x01\x12\x0f\n" +
	"\vGRAIN_MONTH\x10\x02\x12\x0e\n" +
	"\n" +
	"GRAIN_YEAR\x10\x03:]\n" +
	"\ffield_policy\x12\x1d.google.protobuf.FieldOptions\x18ц\x03 \x01(\v2\x19.garm.tool.v1.FieldPolicyR\vfieldPolicy:N\n" +
	"\x04tool\x12\x1e.google.protobuf.MethodOptions\x18҆\x03 \x01(\v2\x18.garm.tool.v1.ToolPolicyR\x04tool:n\n" +
	"\x14default_field_policy\x12\x1f.google.protobuf.MessageOptions\x18ӆ\x03 \x01(\v2\x19.garm.tool.v1.FieldPolicyR\x12defaultFieldPolicy:Y\n" +
	"\fcompartments\x12\x1c.google.protobuf.FileOptions\x18Ԇ\x03 \x01(\v2\x15.garm.tool.v1.DeclSetR\fcompartments:R\n" +
	"\ttool_sets\x12\x1c.google.protobuf.FileOptions\x18Ն\x03 \x01(\v2\x15.garm.tool.v1.DeclSetR\btoolSetsB7Z5github.com/garm-ai/garm/contracts/garm/tool/v1;toolv1b\x06proto3"

var (
	file_garm_tool_v1_tool_proto_rawDescOnce sync.Once
	file_garm_tool_v1_tool_proto_rawDescData []byte
)

func file_garm_tool_v1_tool_proto_rawDescGZIP() []byte {
	file_garm_tool_v1_tool_proto_rawDescOnce.Do(func() {
		file_garm_tool_v1_tool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_garm_tool_v1_tool_proto_rawDesc), len(file_garm_tool_v1_tool_proto_rawDesc)))
	})
	return file_garm_tool_v1_tool_proto_rawDescData
}

var file_garm_tool_v1_tool_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_garm_tool_v1_tool_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_garm_tool_v1_tool_proto_goTypes = []any{
	(Clearance)(0),                      // 0: garm.tool.v1.Clearance
	(Verb)(0),                           // 1: garm.tool.v1.Verb
	(PrincipalKind)(0),                  // 2: garm.tool.v1.PrincipalKind
	(Reversibility)(0),                  // 3: garm.tool.v1.Reversibility
	(Grain)(0),                          // 4: garm.tool.v1.Grain
	(Approval_Mode)(0),                  // 5: garm.tool.v1.Approval.Mode
	(Audit_Level)(0),                    // 6: garm.tool.v1.Audit.Level
	(*Omit)(nil),                        // 7: garm.tool.v1.Omit
	(*Mask)(nil),                        // 8: garm.tool.v1.Mask
	(*Hash)(nil),                        // 9: garm.tool.v1.Hash
	(*EmailDomain)(nil),                 // 10: garm.tool.v1.EmailDomain
	(*KeepLast)(nil),                    // 11: garm.tool.v1.KeepLast
	(*Truncate)(nil),                    // 12: garm.tool.v1.Truncate
	(*CardBinLast4)(nil),                // 13: garm.tool.v1.CardBinLast4
	(*IpPrefix)(nil),                    // 14: garm.tool.v1.IpPrefix
	(*UrlOrigin)(nil),                   // 15: garm.tool.v1.UrlOrigin
	(*DateGrain)(nil),                   // 16: garm.tool.v1.DateGrain
	(*Custom)(nil),                      // 17: garm.tool.v1.Custom
	(*Redaction)(nil),                   // 18: garm.tool.v1.Redaction
	(*FieldPolicy)(nil),                 // 19: garm.tool.v1.FieldPolicy
	(*Effects)(nil),                     // 20: garm.tool.v1.Effects
	(*Approval)(nil),                    // 21: garm.tool.v1.Approval
	(*Example)(nil),                     // 22: garm.tool.v1.Example
	(*Guidance)(nil),                    // 23: garm.tool.v1.Guidance
	(*ListFilter)(nil),                  // 24: garm.tool.v1.ListFilter
	(*Fga)(nil),                         // 25: garm.tool.v1.Fga
	(*Authorization)(nil),               // 26: garm.tool.v1.Authorization
	(*Audit)(nil),                       // 27: garm.tool.v1.Audit
	(*ToolPolicy)(nil),                  // 28: garm.tool.v1.ToolPolicy
	(*Decl)(nil),                        // 29: garm.tool.v1.Decl
	(*DeclSet)(nil),                     // 30: garm.tool.v1.DeclSet
	(*descriptorpb.FieldOptions)(nil),   // 31: google.protobuf.FieldOptions
	(*descriptorpb.MethodOptions)(nil),  // 32: google.protobuf.MethodOptions
	(*descriptorpb.MessageOptions)(nil), // 33: google.protobuf.MessageOptions
	(*descriptorpb.FileOptions)(nil),    // 34: google.protobuf.FileOptions
}
var file_garm_tool_v1_tool_proto_depIdxs = []int32{
	4,  // 0: garm.tool.v1.DateGrain.grain:type_name -> garm.tool.v1.Grain
	7,  // 1: garm.tool.v1.Redaction.omit:type_name -> garm.tool.v1.Omit
	8,  // 2: garm.tool.v1.Redaction.mask:type_name -> garm.tool.v1.Mask
	9,  // 3: garm.tool.v1.Redaction.hash:type_name -> garm.tool.v1.Hash
	10, // 4: garm.tool.v1.Redaction.email_domain:type_name -> garm.tool.v1.EmailDomain
	11, // 5: garm.tool.v1.Redaction.keep_last:type_name -> garm.tool.v1.KeepLast
	12, // 6: garm.tool.v1.Redaction.truncate:type_name -> garm.tool.v1.Truncate
	13, // 7: garm.tool.v1.Redaction.card_bin_last4:type_name -> garm.tool.v1.CardBinLast4
	14, // 8: garm.tool.v1.Redaction.ip_prefix:type_name -> garm.tool.v1.IpPrefix
	15, // 9: garm.tool.v1.Redaction.url_origin:type_name -> garm.tool.v1.UrlOrigin
	16, // 10: garm.tool.v1.Redaction.date_grain:type_name -> garm.tool.v1.DateGrain
	17, // 11: garm.tool.v1.Redaction.custom:type_name -> garm.tool.v1.Custom
	0,  // 12: garm.tool.v1.FieldPolicy.read:type_name -> garm.tool.v1.Clearance
	0,  // 13: garm.tool.v1.FieldPolicy.write:type_name -> garm.tool.v1.Clearance
	18, // 14: garm.tool.v1.FieldPolicy.on_deny:type_name -> garm.tool.v1.Redaction
	3,  // 15: garm.tool.v1.Effects.reversibility:type_name -> garm.tool.v1.Reversibility
	5,  // 16: garm.tool.v1.Approval.mode:type_name -> garm.tool.v1.Approval.Mode
	0,  // 17: garm.tool.v1.Approval.approver_min_clearance:type_name -> garm.tool.v1.Clearance
	22, // 18: garm.tool.v1.Guidance.examples:type_name -> garm.tool.v1.Example
	24, // 19: garm.tool.v1.Fga.filter_response:type_name -> garm.tool.v1.ListFilter
	25, // 20: garm.tool.v1.Authorization.fga:type_name -> garm.tool.v1.Fga
	6,  // 21: garm.tool.v1.Audit.level:type_name -> garm.tool.v1.Audit.Level
	1,  // 22: garm.tool.v1.ToolPolicy.verb:type_name -> garm.tool.v1.Verb
	0,  // 23: garm.tool.v1.ToolPolicy.min_clearance:type_name -> garm.tool.v1.Clearance
	20, // 24: garm.tool.v1.ToolPolicy.effects:type_name -> garm.tool.v1.Effects
	21, // 25: garm.tool.v1.ToolPolicy.approval:type_name -> garm.tool.v1.Approval
	23, // 26: garm.tool.v1.ToolPolicy.guidance:type_name -> garm.tool.v1.Guidance
	26, // 27: garm.tool.v1.ToolPolicy.authorization:type_name -> garm.tool.v1.Authorization
	27, // 28: garm.tool.v1.ToolPolicy.audit:type_name -> garm.tool.v1.Audit
	29, // 29: garm.tool.v1.DeclSet.declared:type_name -> garm.tool.v1.Decl
	31, // 30: garm.tool.v1.field_policy:extendee -> google.protobuf.FieldOptions
	32, // 31: garm.tool.v1.tool:extendee -> google.protobuf.MethodOptions
	33, // 32: garm.tool.v1.default_field_policy:extendee -> google.protobuf.MessageOptions
	34, // 33: garm.tool.v1.compartments:extendee -> google.protobuf.FileOptions
	34, // 34: garm.tool.v1.tool_sets:extendee -> google.protobuf.FileOptions
	19, // 35: garm.tool.v1.field_policy:type_name -> garm.tool.v1.FieldPolicy
	28, // 36: garm.tool.v1.tool:type_name -> garm.tool.v1.ToolPolicy
	19, // 37: garm.tool.v1.default_field_policy:type_name -> garm.tool.v1.FieldPolicy
	30, // 38: garm.tool.v1.compartments:type_name -> garm.tool.v1.DeclSet
	30, // 39: garm.tool.v1.tool_sets:type_name -> garm.tool.v1.DeclSet
	40, // [40:40] is the sub-list for method output_type
	40, // [40:40] is the sub-list for method input_type
	35, // [35:40] is the sub-list for extension type_name
	30, // [30:35] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_garm_tool_v1_tool_proto_init() }
func file_garm_tool_v1_tool_proto_init() {
	if File_garm_tool_v1_tool_proto != nil {
		return
	}
	file_garm_tool_v1_tool_proto_msgTypes[11].OneofWrappers = []any{
		(*Redaction_Omit)(nil),
		(*Redaction_Mask)(nil),
		(*Redaction_Hash)(nil),
		(*Redaction_EmailDomain)(nil),
		(*Redaction_KeepLast)(nil),
		(*Redaction_Truncate)(nil),
		(*Redaction_CardBinLast4)(nil),
		(*Redaction_IpPrefix)(nil),
		(*Redaction_UrlOrigin)(nil),
		(*Redaction_DateGrain)(nil),
		(*Redaction_Custom)(nil),
	}
	file_garm_tool_v1_tool_proto_msgTypes[18].OneofWrappers = []any{
		(*Fga_FromRequestField)(nil),
		(*Fga_FromResponseField)(nil),
		(*Fga_FilterResponse)(nil),
	}
	file_garm_tool_v1_tool_proto_msgTypes[19].OneofWrappers = []any{
		(*Authorization_Fga)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_garm_tool_v1_tool_proto_rawDesc), len(file_garm_tool_v1_tool_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   24,
			NumExtensions: 5,
			NumServices:   0,
		},
		GoTypes:           file_garm_tool_v1_tool_proto_goTypes,
		DependencyIndexes: file_garm_tool_v1_tool_proto_depIdxs,
		EnumInfos:         file_garm_tool_v1_tool_proto_enumTypes,
		MessageInfos:      file_garm_tool_v1_tool_proto_msgTypes,
		ExtensionInfos:    file_garm_tool_v1_tool_proto_extTypes,
	}.Build()
	File_garm_tool_v1_tool_proto = out.File
	file_garm_tool_v1_tool_proto_goTypes = nil
	file_garm_tool_v1_tool_proto_depIdxs = nil
}
